### ISSUE TITLE
res.plot() it does not work (it's very urgent)

### ISSUE THREAD

**Issue by hmz123** [pmorissette/bt#100]
Hello
I want to test the bt library first, all goes well except that the graph does not appear res.plot ()
I work with WinPython (python 2.7) but it does not work, so I made another choice, and run the script on the command
Python test.py. But that I said the graph does not show ???
Any ideas ?

**Comment by mobeeze** [comment]
hmz123, try something like:

import matplotlib.pyplot as plt
plt.show()

**Comment by hmz123** [comment]
Add this line
%matplotlib inline
