### ISSUE TITLE
Problem with YAHOO FINANCE

### ISSUE THREAD

**Issue by hmz123** [pmorissette/bt#102]
Hello,
As you know yahoo finance it does not work for a few days, so also the bt library
There is a solution?

**Comment by wlblount** [comment]
this seems to work for now

https://github.com/ranaroussi/fix-yahoo-finance

**Comment by pmorissette** [comment]
Thanks @wlblount 

Fixed in ffn thanks to your link. If you upgrade ffn (used by bt - `pip install --upgrade ffn`) the problem should be fixed (for now). 

Cheers,
Phil

**Comment by hmz123** [comment]
@pmorissette 
Hi Phil , i have problem with upgade ffn (i don't know why ) 


       config.add_subpackage('linalg')
      File "C:\Users\hamza\Anaconda2\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "C:\Users\hamza\Anaconda2\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\hamza\Anaconda2\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
  Rolling back uninstall of scipy
Command "C:\Users\hamza\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\hamza\\appdata\\local\\temp\\pip-build-8523s6\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\hamza\appdata\local\temp\pip-ilipae-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\hamza\appdata\local\temp\pip-build-8523s6\scipy\


i do not know i f i got to upgrade ffn ?
but i does not work with bt

**Comment by hmz123** [comment]
@pmorissette 

this my code of backtest

1. %matplotlib inline 
import bt
from pandas.tseries.offsets import *
from pandas_datareader import data as pdr
from pandas import DataFrame
import fix_yahoo_finance


data = pdr.get_data_yahoo( tickers = ["SPY", "AAPL","QQQ","FB","gd","ge","amz","all"],start = "2011-01-01",end = "2017-04-30",as_panel = False,group_by = 'ticker',auto_adjust = True)

s = bt.Strategy('s1', [bt.algos.RunMonthly(),
                       bt.algos.SelectAll(),
                       bt.algos.SelectMomentum(5,DateOffset(months=6),DateOffset(days=0)),
                       bt.algos.WeighMeanVar(DateOffset(months=6),DateOffset(days=0)),
                       bt.algos.Rebalance()])


test= bt.Backtest(s,data)

res = bt.run(test)
res.display()
res.plot()

this code works if i use  (bt.algos.WeighEqually()) but not with ( bt.algos.WeighMeanVar(DateOffset(months=6),DateOffset(days=0))

error :   float() argument must be a string or a number
