### ISSUE TITLE
Distributed processing

### ISSUE THREAD

**Issue by richardtbenade** [pmorissette/bt#104]
Hi There

I'm using bt in Google's Datalab. Is there a way to enable distributed processing when running backtests with bt? I seem to be limited to one core which results in slow backtesting.

**Comment by atisharma** [comment]
I'm not sure about Datalab, but I've managed to get one backtest per core using the following,
`
from multiprocessing import Pool

tests = [hourly_test, daily_test, weekly_test, monthly_test, quarterly_test]
with Pool(6) as pool:
    results = pool.map(bt.run, tests)
`
