### ISSUE TITLE
Import error in Datalab

### ISSUE THREAD

**Issue by richardtbenade** [pmorissette/bt#105]
Hi there

I've been using bt in Google's Datalab to perform backtests. 

This has been running fine for the last couple of weeks, but when I wanted to rerun a backtest this afternoon, my "import bt" command failed with the following error:
===============================
ImportErrorTraceback (most recent call last)
<ipython-input-2-e01c3dd3682b> in <module>()
----> 1 import bt

/usr/local/lib/python2.7/dist-packages/bt/__init__.py in <module>()
----> 1 from . import core
      2 from . import algos
      3 from . import backtest
      4 
      5 from .backtest import Backtest, run

ImportError: cannot import name core
===============================

Please advise on how I can sort this out?

Note that this happens even after installing the necessary dependencies: 
=========================================
  !apt-get update
  !apt-get install -y build-essential libssl-dev libffi-dev python-dev
  !pip install bt
==========================================

**Comment by richardtbenade** [comment]
My apologies for the formatting glitch.

**Comment by richardtbenade** [comment]
Some more info:

I've been in contact with Google regarding this, their reply: 

After further investigation it appears that for some reason the "bt" module is not working for Python 2.7.X which is the version running for DataLab, you can check this by trying to import it to any Python 2.7.X. The test I did was the following: - On a normal instance with "PIP" and "Python 2.7.X" installed. - Run "pip install bt" - You will see that the installation works without any problem. - Enter into Python shell and import the module you will see below error: 
===================================================================
Python 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] on linux2 Type "help", "copyright", "credits" or "license" for more information. >>> import bt Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python2.7/dist-packages/bt/__init__.py", line 3, in <module> from . import backtest File "/usr/local/lib/python2.7/dist-packages/bt/backtest.py", line 7, in <module> import ffn File "/usr/local/lib/python2.7/dist-packages/ffn/__init__.py", line 2, in <module> from . import data File "/usr/local/lib/python2.7/dist-packages/ffn/data.py", line 5, in <module> import fix_yahoo_finance # noqa File "/usr/local/lib/python2.7/dist-packages/fix_yahoo_finance/__init__.py", line 231 print('\r' + str(self), end='') ^ SyntaxError: invalid syntax 
==================================================================
The last "SyntaxError" its related to a Python 3.X "print" function "print('\r' + str(self), end='')" and Python 2.7.X don't recognize it. 


I've tried installing older versions of bt (0.1.15) to overcome this issue but no luck so far. I'd really appreciate any help.

**Comment by pmorissette** [comment]
Hi,

I actually ran into this issue yesterday. I added fix_yahoo_finance to ffn to patch up the broken API, but this package is only available for Python 3. I think I will have to remove that for now because it is indeed breaking the install.

Thanks for bringing this up and I'll let you know once I have made the changes.

Cheers,
Phil

**Comment by richardtbenade** [comment]
Many thanks. In the mean time I managed to get around it using:
!pip uninstall fix_yahoo_finance
!pip install fix_yahoo_finance==0.0.7 
before importing bt.

Thanks for looking into this.

**Comment by pmorissette** [comment]
Yeah I may do that instead of getting rid of it completely.

**Comment by pmorissette** [comment]
Ok so I just updated `ffn`. I basically just made the same fix you have up above. Let me know if you still run into any issues. Hopefully, `pandas_datareader` will merge in a fix for YF and we won't need this shim anymore.

Cheers,
Phil
