### ISSUE TITLE
Not an issue - just a question.

### ISSUE THREAD

**Issue by jaredpohl** [pmorissette/bt#108]
Hello,

wondering if your backtester supports loading data from a csv file.. if i wanted to load my own dataset, what would the format be for the file and how would i set it to be a csv??

thanks!

**Comment by eurekar** [comment]
Same question here. Thanks!

**Comment by pmorissette** [comment]
Hi both,

Yes this is done via the pandas library. Check out the docs for that package. Basically, you would swap out `data = bt.get(...)` for `data = pandas.read_csv(...)` in the examples.

Hope this helps,
Phil

**Comment by jaredpohl** [comment]
Thank you ! That helps immensely.

I was wondering if it was possible to get pointed in a direction by you.. I'm trying to learn some quant strategies and am trying to - as a way of learning - recreate the Fama French factors. 

I was wondering if you had any example code or suggestions on how to implement it. I've been thinking about it for a while now and am coming up stuck in a few areas on your code base.

Perhaps even some pseudo code to go away and work on it after.

Thank you
