### ISSUE TITLE
cannot import name 'PandasError python'

### ISSUE THREAD

**Issue by oalexandere** [pmorissette/bt#109]
When importing bt with Pandas version 0.20.2 get error: "cannot import name 'PandasError python".
Reinstalling to older version solved the problem: pip install -U pandas==0.19.2

**Comment by gminorcoles** [comment]
bummer

**Comment by gminorcoles** [comment]
actually, I fixed this in my environment by running pip install -U pandas-datareader. They fixed pandas 2.0 incompatibility issues in the latest version.

**Comment by JordanPlatts** [comment]
I am going to close this issue. Reopen it if there is a problem.
