### ISSUE TITLE
Plot not showing

### ISSUE THREAD

**Issue by scorpioneme** [pmorissette/bt#111]
Thanks for the great work first!

I'm not able to get the plot showing, although the package works perfectly otherwise. I use the 
interpreter on terminal and PyCharm but neither works.
Did a little digging, seems like you're using matplotlib, from a quick search I think the problem may be with the fact that you're not using plt.show() after each plotting def? I could be wrong, and I'm not that advanced. Just wanted to point this out, and would appreciate any help!

Thanks!

**Comment by avolution** [comment]
Same Problem

**Comment by fcorrea** [comment]
Confirmed.
Just tried two different virtualenvs (python2.7 and python3) with all dependencies installed and graphing is not working.
Is there a specific backend requirement for matplotlib that is not being installed for some reason?

**Comment by fcorrea** [comment]
Mmm...it seems that using '%matplotlib inline' in the first line of the notebook solves the issue.

**Comment by JimmyWuMadchester** [comment]
The plot wrapper function in f.fn returns nothing. So you won't be able to see it without '%matplotlib inline'.
It also doesn't allow you to save it.

```
def plot(self, freq=None, figsize=(15, 5), title=None,
             logy=False, **kwargs):
        """
        Helper function for plotting the series.
        Args:
            * freq (str): Data frequency used for display purposes.
                Refer to pandas docs for valid freq strings.
            * figsize ((x,y)): figure size
            * title (str): Title if default not appropriate
            * logy (bool): log-scale for y axis
            * kwargs: passed to pandas' plot method
        """
        if title is None:
            title = self._get_default_plot_title(
                self.name, freq, 'Price Series')

        ser = self._get_series(freq)
        ser.plot(figsize=figsize, title=title, logy=logy, **kwargs)
```

It feels to me if you want to save the figure you need to manually call the underlying pandas plot().

**Comment by catherinexiao** [comment]
Confirmed I try to use the package via Pycharm. Once bt is imported, plt.show() is not working. The package is using 'agg' as backend, which is a non-interactive backend for .png output. Would you please use Qt5Agg??
