### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get'

### ISSUE THREAD

**Issue by Megalinux** [pmorissette/bt#112]
Hi,
I run my script bt.py and the following error appears:

Traceback (most recent call last):
  File "bt.py", line 1, in <module>
    import bt
  File "/xxxxxxxx/bt.py", line 2, in <module>
    data = bt.get('aapl',start='2010-01-01')
AttributeError: 'module' object has no attribute 'get'

My version of Python: 2.7.13

pip list | grep 'bt'
bt (0.2.5)

I have installed bt with the following command:
# pip install bt

What's the problem?
Thank you for the reply
bye

**Comment by timkpaine** [comment]
there is no file called bt.py in this repo.
