### ISSUE TITLE
Anaconda 4.4 / Atom / bt

### ISSUE THREAD

**Issue by Vasco10** [pmorissette/bt#114]
I use Anaconda 4.4 and Atom on a USB stick - it works perfectly - already using it since 2 to 3 months.

What can be done that 'bt' runs on a USB stick?

Just installed via 'pip install bt'. It went alright except for something: "Failed building wheel for bt" and "Command "E:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vasco\\AppData\\Local\\Temp\\pip-build-9gn_1rbr\\bt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vasco\AppData\Local\Temp\pip-71cvtm6_-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Vasco\AppData\Local\Temp\pip-build-9gn_1rbr\bt\"

Then I redid the installation via "easy_install bt", now I get this error:
"Searching for bt
Reading https://pypi.python.org/simple/bt/
Downloading https://pypi.python.org/packages/17/47/186238405864113bd6a6d4869d4c0ba2a2d631113f9a6af2af7eb7057f54/bt-0.2.5.tar.gz#md5=4ee3e73a4b54b469148f397e79b1fc15
Best match: bt 0.2.5
Processing bt-0.2.5.tar.gz
Writing C:\Users\Vasco\AppData\Local\Temp\easy_install-0h__1ogk\bt-0.2.5\setup.cfg
Running bt-0.2.5\setup.py -q bdist_egg --dist-dir C:\Users\Vasco\AppData\Local\Temp\easy_install-0h__1ogk\bt-0.2.5\egg-dist-tmp-at2gsqn_
no previously-included directories found matching 'docs\build'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools"

Did a little test:
"Traceback (most recent call last):
  File "E:\Python_Repos\Beginners_English\test.py", line 1, in <module>
    import bt
ModuleNotFoundError: No module named 'bt' "

**Comment by timkpaine** [comment]
The error is self-explanatory. You need a valid compiler to build libraries that require compilation.
