### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by rohithth** [pmorissette/bt#123]
Hi,

I would like to first thank you for the fantastic work and seek some advice as well.

Below is the code. I would like to add threshold of 6%. That is monthly rebalancing frequency but it check if the drift is within the 6% threshold, if not then only it rebalances. Also, is it possible to get the number of times it rebalanced during the backtest period as a part of the results. I find your code extremely useful and simple compared to others, but it is just the threshold that I'm stuck up. Thank you once again.

**Comment by caush** [comment]
Hello.
I would also like to thank you for this work.
The possibility of rebalancing according to a threshold seems interesting. Maybe we can do it already. I confess that I have a little trouble to implant it by myself.
Would anyone have any information in relation to this function?
Thank you again.

**Comment by caush** [comment]
I have adapted the class LimitDeltas. This seems to work for me:
class MinimumDeltas(Algo):
    def __init__(self, limit=0.1):
        super(MinimumDeltas, self).__init__()
        self.limit = limit
        # determine if global or specific
        self.global_limit = True
        if isinstance(limit, dict):
            self.global_limit = False
    def __call__(self, target):
        tw = target.temp['weights']
        all_keys = set(list(target.children.keys()) + list(tw.keys()))
        for k in all_keys:
            tgt = tw[k] if k in tw else 0.
            cur = target.children[k].weight if k in target.children else 0.
            delta = tgt - cur
            # check if we need to limit
            if self.global_limit:
                if abs(delta) > self.limit:
                    return True
                    #tw[k] = cur + (self.limit * np.sign(delta))
            else:
                # make sure we have a limit defined in case of limit dict
                if k in self.limit:
                    lmt = self.limit[k]
                    if abs(delta) > lmt:
                        return True
                        #tw[k] = cur + (lmt * np.sign(delta))
        return False

**Comment by caush** [comment]
I have adapted the class LimitDeltas. This seems to work for me:
```
class MinimumDeltas(Algo):
    def __init__(self, limit=0.1):
        super(MinimumDeltas, self).__init__()
        self.limit = limit
        # determine if global or specific
        self.global_limit = True
        if isinstance(limit, dict):
            self.global_limit = False
    def __call__(self, target):
        tw = target.temp['weights']
        all_keys = set(list(target.children.keys()) + list(tw.keys()))
        for k in all_keys:
            tgt = tw[k] if k in tw else 0.
            cur = target.children[k].weight if k in target.children else 0.
            delta = tgt - cur
            # check if we need to limit
            if self.global_limit:
                if abs(delta) > self.limit:
                    return True
                    #tw[k] = cur + (self.limit * np.sign(delta))
            else:
                # make sure we have a limit defined in case of limit dict
                if k in self.limit:
                    lmt = self.limit[k]
                    if abs(delta) > lmt:
                        return True
                        #tw[k] = cur + (lmt * np.sign(delta))
        return False
```
