### ISSUE TITLE
RemoteDataError: Unable to read URL

### ISSUE THREAD

**Issue by dcshapiro** [pmorissette/bt#124]
I am getting errors running the default examples on a clean install
It seems yahoo is blocking bt's GET requests
Is there a fix or alternate datasource out there?

Here is the post indicating this is an issue: https://forum.xojo.com/40797-problem-with-yahoo-finance-download/0

Thanks,

Stacktrace follows:

---------------------------------------------------------------------------
RemoteDataError                           Traceback (most recent call last)
<ipython-input-11-bf4ec1d8fa0a> in <module>()
      7 get_ipython().magic('matplotlib inline')
      8 # fetch some data
----> 9 data = bt.get('ivv,efa,eem,vig,shy,lqd,emb,mub,tip,vnq,xle', start='2016-01-01', end='2017-01-01')#
     10 print(data.head())
     11 # create the strategy

<decorator-gen-125> in get(tickers, provider, common_dates, forward_fill, clean_tickers, column_names, ticker_field_sep, mrefresh, existing, **kwargs)

/usr/local/lib/python3.5/dist-packages/ffn/utils.py in _memoize(func, *args, **kw)
     30         return cache[key]
     31     else:
---> 32         cache[key] = result = func(*args, **kw)
     33         return result
     34 

/usr/local/lib/python3.5/dist-packages/ffn/data.py in get(tickers, provider, common_dates, forward_fill, clean_tickers, column_names, ticker_field_sep, mrefresh, existing, **kwargs)
     55         if hasattr(provider, 'mcache'):
     56             data[ticker] = provider(ticker=t, field=f,
---> 57                                     mrefresh=mrefresh, **kwargs)
     58         else:
     59             data[ticker] = provider(ticker=t, field=f, **kwargs)

<decorator-gen-128> in yf(ticker, field, start, end, mrefresh)

/usr/local/lib/python3.5/dist-packages/ffn/utils.py in _memoize(func, *args, **kw)
     30         return cache[key]
     31     else:
---> 32         cache[key] = result = func(*args, **kw)
     33         return result
     34 

/usr/local/lib/python3.5/dist-packages/ffn/data.py in yf(ticker, field, start, end, mrefresh)
    119         field = 'Adj Close'
    120 
--> 121     tmp = pdata.get_data_yahoo(ticker, start=start, end=end)
    122 
    123     if tmp is None:

/usr/local/lib/python3.5/dist-packages/pandas_datareader/data.py in get_data_yahoo(*args, **kwargs)
     38 
     39 def get_data_yahoo(*args, **kwargs):
---> 40     return YahooDailyReader(*args, **kwargs).read()
     41 
     42 

/usr/local/lib/python3.5/dist-packages/pandas_datareader/yahoo/daily.py in read(self)
    113         """ read one data from specified URL """
    114         try:
--> 115             df = super(YahooDailyReader, self).read()
    116             if self.ret_index:
    117                 df['Ret_Index'] = _calc_return_index(df['Adj Close'])

/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py in read(self)
    179         if isinstance(self.symbols, (compat.string_types, int)):
    180             df = self._read_one_data(self.url,
--> 181                                      params=self._get_params(self.symbols))
    182         # Or multiple symbols, (e.g., ['GOOG', 'AAPL', 'MSFT'])
    183         elif isinstance(self.symbols, DataFrame):

/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py in _read_one_data(self, url, params)
     77         """ read one data from specified URL """
     78         if self._format == 'string':
---> 79             out = self._read_url_as_StringIO(url, params=params)
     80         elif self._format == 'json':
     81             out = self._get_response(url, params=params).json()

/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py in _read_url_as_StringIO(self, url, params)
     88         Open url (and retry)
     89         """
---> 90         response = self._get_response(url, params=params)
     91         text = self._sanitize_response(response)
     92         out = StringIO()

/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py in _get_response(self, url, params, headers)
    137         if params is not None and len(params) > 0:
    138             url = url + "?" + urlencode(params)
--> 139         raise RemoteDataError('Unable to read URL: {0}'.format(url))
    140 
    141     def _get_crumb(self, *args):

RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/lqd?crumb=1e4%5Cu002F3stNPbl&events=history&period1=1451606400&interval=1d&period2=1483315199

**Comment by issifuadama** [comment]
I am running this code bin collab
google = web.DataReader('GOOGL', 'yahoo', start, end)

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/GOOGL/history?period1=1577851200&period2=1587182399&interval=1d&frequency=1d&filter=history
Response Text:
b'<!DOCTYPE html>\n  <html lang="en-us"><head>\n  <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n      <meta charset="utf-8">\n      <title>Yahoo</title>\n      <meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui">\n      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n      <style>\n  html {\n      height: 100%;\n  }\n  body {\n      background: #fafafc url(https://s.yimg.com/nn/img/sad-panda-201402200631.png) 50% 50%;\n      background-size: cover;\n      height: 100%;\n      text-align: center;\n      font: 300 18px "helvetica neue", helvetica, verdana, tahoma, arial, sans-serif;\n  }\n  table {\n      height: 100%;\n      width: 100%;\n      table-layout: fixed;\n      border-collapse: collapse;\n      border-spacing: 0;\n      border: none;\n  }\n  h1 {\n      font-size: 42px;\n      font-weight: 400;\n      color: #400090;\n  }\n  p {\n      color: #1A1A1A;\n  }\n  #message-1 {\n      font-weight: bold;\n      margin: 0;\n  }\n  #message-2 {\n      display: inline-block;\n      *display: inline;\n      zoom: 1;\n      max-width: 17em;\n      _width: 17em;\n  }\n      </style>\n  <script>\n    document.write(\'<img src="//geo.yahoo.com/b?s=1197757129&t=\'+new Date().getTime()+\'&src=aws&err_url=\'+encodeURIComponent(document.URL)+\'&err=%<pssc>&test=\'+encodeURIComponent(\'%<{Bucket}cqh[:200]>\')+\'" width="0px" height="0px"/>\');var beacon = new Image();beacon.src="//bcn.fp.yahoo.com/p?s=1197757129&t="+ne..

can someone help me, please.
