### ISSUE TITLE
overlay plots

### ISSUE THREAD

**Issue by bgits** [pmorissette/bt#125]
Is it currently possible to overlay result plots? A use case would be to visualize the performance compared with buying and holding.

**Comment by wlblount** [comment]
just create a "long only" strategy for the benchmark. and plot both.  look at the example of comparing sma strat to benchmark "SPY"

```
def long_only_ew(tickers, start='2010-01-01', name='long_only_ew'):
    s = bt.Strategy(name, [bt.algos.RunOnce(),
                           bt.algos.SelectAll(),
                           bt.algos.WeighEqually(),
                           bt.algos.Rebalance()])
```

**Comment by JordanPlatts** [comment]
Some of the new functionality will let you get data from Result objects easier now. Look at some of the examples and let me know if you have any other questions.
