### ISSUE TITLE
bt.backtest not accepting my boolean dataframe

### ISSUE THREAD

**Issue by AlexBThomsen** [pmorissette/bt#126]
When I run the backtest I get this error:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Been looking around but haven't found any solution. Any form of help would be appreciated!

Code example:

        R1:
                         A   B   C.... 
       date
      2017-12-29         12   6   3
      2017-12-30         10   5   4

     df_input = R1 < 6 

     df_input:

                        A         B       C.... 
     date
     2017-12-29       False   False     True
     2017-12-30       False   True      True

     s = bt.Strategy('s', [bt.algos.SelectWhere(df_input),
                      bt.algos.RunQuarterly(),
                      bt.algos.SelectAll(include_no_data=True),
                      bt.algos.WeighEqually(),
                      bt.algos.Rebalance()])

    df2:

                      A      B      C.... 
    date
    2017-12-29       300   200     100
    2017-12-30       350   210      80

    test = bt.backtest.Backtest(s,df2,initial_capital=1000) 
    res = bt.run(test)

output:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-206-705e18e42581> in <module>()
      1 test = bt.backtest.Backtest(s,df2,initial_capital=1000)
----> 2 res = bt.run(test)

/anaconda3/lib/python3.6/site-packages/bt/backtest.py in run(*backtests)
     26     # run each backtest
     27     for bkt in backtests:
---> 28         bkt.run()
     29 
     30     return Result(*backtests)

/anaconda3/lib/python3.6/site-packages/bt/backtest.py in run(self)
    196 
    197             # update strategy
--> 198             self.strategy.update(dt)
    199 
    200             if not self.strategy.bankrupt:

/anaconda3/lib/python3.6/site-packages/bt/core.cpython-36m-darwin.so in bt.core.StrategyBase.update (bt/core.c:7504)()

/anaconda3/lib/python3.6/site-packages/bt/core.cpython-36m-darwin.so in bt.core.SecurityBase.update (bt/core.c:12850)()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by JordanPlatts** [comment]
Can you post more info so I can recreate this issue? Here is what I have so far which throws another error from ffn that is already fixed but not pushed to pip.

    df_input = pd.DataFrame(
        [
            [False, False, True],
            [False, True, True]
        ],
        index = pd.DatetimeIndex(
            [
                pd.Timestamp('2017-12-29'),
                pd.Timestamp('2017-12-30')
            ]
        ),
        columns= ['A','B','C']
    )
    s = bt.Strategy(
        's',
        [
            bt.algos.SelectWhere(df_input),
            bt.algos.RunQuarterly(),
            bt.algos.SelectAll(include_no_data=True),
            bt.algos.WeighEqually(),
            bt.algos.Rebalance()
        ]
    )
    df2 = pd.DataFrame(np.zeros(df_input.shape), index= df_input.index, columns=df_input.columns)
    df2.loc[:, 'A'] = [300, 350]
    df2.loc[:, 'B'] = [200, 210]
    df2.loc[:, 'C'] = [100, 80]
    test = bt.backtest.Backtest(s, df2, initial_capital=1000)

    try:
        res = bt.run(test)
        assert True
    except Exception as e:
        assert False

**Comment by jester94** [comment]
@JordanPlatts

Please understand. I don't understand English. This text was translated using Google translate.

**I also encountered the same problem. I found that when the amount of data is less than 1000(data < 1000), the code can run smoothly. but, when the amount of data is greater than 1000(data > 1000), the code will report an error.**


My environmental information is as follows:
bt (0.2.5)
bfn (0.3.3)
Jupyter (1.0.0)
Jupyter-client (5.2.3)
Jupyter-console (5.2.0)
Jupyter-core (4.4.0)
Numpy (1.14.3)
pandas (0.22.0)
Pandas-datareader (0.6.0)


The data uses the Bitcoin 30min closing price, a total of 36,000 data, some of which are as follows:

0 Close
2017-05-02 14:00:00 1575.2
2017-05-02 14:15:00 1564.7
2017-05-02 14:30:00 1566.1
2017-05-02 14:45:00 1564.9
2017-05-02 15:00:00 1570.0
2017-05-02 15:15:00 1561.9
2017-05-02 15:30:00 1560.1
2017-05-02 15:45:00 1558.5
2017-05-02 16:00:00 1565.0
... ...


Code:
```
data = pd.read_csv('btc-30min.csv')
data.set_index('0', inplace=True)
data.index = pd.to_datetime(data.index, unit='ms')

Sma50 = data.rolling(50).mean()
Sma200 = data.rolling(200).mean()

Tw = sma200.copy()
Tw[sma50 > sma200] = 1.0
Tw[sma50 <= sma200] = -1.0
Tw[sma200.isnull()] = 0.0

Ma_cross = bt.Strategy('ma_cross', [bt.algos.WeighTarget(tw), bt.algos.Rebalance()])
t = bt.Backtest(ma_cross, data)
Res = bt.run(t)
```

Error message:

> Ma_cross
> 0% [###            ] 100% | ETA: 00:00:11
> ---------------------------------------------------------------------------
> ValueError Traceback (most recent call last)
> <ipython-input-12-aeacc6d1d485> in <module>()
>       3
>       4 t = bt.Backtest(ma_cross, data)
> ----> 5 res = bt.run(t)
> 
> ~/.local/lib/python3.6/site-packages/bt/backtest.py in run(*backtests)
>      26 # run each backtest
>      27 for bkt in backtests:
> ---> 28 bkt.run()
> 
>      29
>      30 return Result(*backtests)
> 
> ~/.local/lib/python3.6/site-packages/bt/backtest.py in run(self)
>     196
>     197 # update strategy
> --> 198 self.strategy.update(dt)
>     199
>     200 if not self.strategy.bankrupt:
> 
> ~/.local/lib/python3.6/site-packages/bt/core.cpython-36m-x86_64-linux-gnu.so in bt.core.StrategyBase.update (bt/core.c:7504)()
> 
> ~/.local/lib/python3.6/site-packages/bt/core.cpython-36m-x86_64-linux-gnu.so in bt.core.SecurityBase.update (bt/core.c:12850)()
> 
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by timkpaine** [comment]
closing as stale/can't repro.
