### ISSUE TITLE
Yahoo actions error

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/bt#130]
Hi,

Newbie to python and BT. I'm trying to run the SMA example on the webpage and it's clear that the YAHOO data source is no longer available, however it's not clear to me how I specify a different data provider to the get bt.get function in order to get the example running ?

Simple one, but any pointers would be greatly received.

DD

**Comment by theoky** [comment]
As I just have struggled with the same problem, here my workaround for the bt-quick example.

I use the `ffn.data.web` provider and as source 'iex' (this is one of the possible sources of the pandas-datareader). Additionally I provide field names, in this case 'close'. The default doesn't seem to work with the iex-source or for me.
```python
#additional imports
import ffn
import pandas as pd

# fetch some data
data = bt.get('SPY:close,AGG:close', provider=ffn.data.web, 
              start='2014-01-01', source='iex')
```
As the returned dataframe has string dates as index, this leads to exceptions in the code later on (I'm using pandas 0.22). The following line replaces the string index with a date index:
```python
data.index = pd.to_datetime(data.index)
```
The remaining code lines in the quick example then work unchanged for me.

I don't know if there is a better solution hidden somewhere within the framework. This one at least works for me. Hope this helps.

**Comment by csc5a2g** [comment]
Theoky,

Thanks, this got me working. Did you manage to figure out how to get the graph to display ?

DD

**Comment by theoky** [comment]
The graphs displayed for me in my Jupyter notebook without problems. 
Maybe you are missing a `%matplotlib inline` statement in your notebook?
