### ISSUE TITLE
Rebalancing error: Cash management bug

### ISSUE THREAD

**Issue by suhailmn** [pmorissette/bt#131]
There is a problem in rebalancing implementation (rebalance() and its sister method).  The cash target code goes into a infinite recursive loop if target weights are negative (short positions). (_I've also seen it happen even in a portfolio of positive weights with a commission function which may be causing cash to dip below) 

"Exception: Potentially infinite loop detected. This occured while trying to reduce the amount of shares purchased to respect the outlay <= amount rule. This is most likely due to a commission function that outputs a commission that is greater than the amount of cash a short sale can raise."

############# test.py ###############
import pandas as pd
import bt
import datetime as dt
import random

date_span = pd.DatetimeIndex(start='10/1/2017', end='10/11/2017', freq='B')
numper = len(date_span.values)
comms = 0.01

data  = [[10,15,20,25,30,35,40,45],
         [10,10,10,10,20,20,20,20],
         [20,20,20,30,30,30,40,40],
         [20,10,20,10,20,10,20,10]]
data = [[row[i] for row in data] for i in range(len(data[0]))] #Transpose
price = pd.DataFrame(data=data, index=date_span)
price.columns = ['a', 'b', 'c', 'd']
#price = price[['a', 'b']]

sig1 = pd.DataFrame(price['a'] >= price['b'] +10, columns=['a'])
sig2 = pd.DataFrame(price['a'] < price['b'] +10, columns=['b'])
signal = sig1.join(sig2)

signal1  = price.diff(1) > 0
signal2  = price.diff(1) < 0

tw = price.copy()
tw.set_value(tw.index,tw.columns,0)  # Initialize Set everything to 0

tw[signal1] = -1.0
tw[signal2] = 1.0

s1 = bt.Strategy('long_short', [ bt.algos.WeighTarget(tw),
                                 bt.algos.RunDaily(),
                                 bt.algos.Rebalance()])

####now we create the Backtest , commissions=(lambda q, p: abs(p * q) * comms)
t = bt.Backtest(s1, price, initial_capital=1000000, commissions=(lambda q, p: abs(p * q) * comms) )

####and let's run it!
res = bt.run(t)
########################

**Comment by atisharma** [comment]
I've also encountered this bug.

**Comment by magnumw** [comment]
Same here..

**Comment by JordanPlatts** [comment]
Your example may be throwing the issue because it is only decrementing the quantity by 1 and limiting it to only decreasing the original quantity by 10,000. In this case, it needed to decrease the quantity by somewhere around 20,000 to make the condition ` full_outlay > amount` false and to break out of the while loop.

One idea is to change the way it is searching for the appropriate quantity. We could change it to some kind of newton's method where it first searches for right `q` where ` full_outlay - amount = 0` then we decrement by 1.

I added the example above as a test case by the way.

**Comment by JordanPlatts** [comment]
I fixed this specific issue in the latest commit but I would like more test cases. I am not convinced it is a full proof solution. If anyone could submit more test cases, that would be great.

You can see my logic a little easier by looking at this latex sheet.
https://www.authorea.com/297725/-gGBFpGpf8jPn68M_XDYyg

**Comment by Kinzowa** [comment]
Hi @JordanPlatts ,

I'm facing the same issue with the example above. Wasn't that supposed to be fixed ?

Thanks,
Kinzowa

```

import pandas as pd
import bt
import datetime as dt
import random

date_span = pd.DatetimeIndex(start='10/1/2017', end='10/11/2017', freq='B')
numper = len(date_span.values)
comms = 0.01

data = [[10,15,20,25,30,35,40,45],
[10,10,10,10,20,20,20,20],
[20,20,20,30,30,30,40,40],
[20,10,20,10,20,10,20,10]]
data = [[row[i] for row in data] for i in range(len(data[0]))] #Transpose
price = pd.DataFrame(data=data, index=date_span)
price.columns = ['a', 'b', 'c', 'd']
#price = price[['a', 'b']]

sig1 = pd.DataFrame(price['a'] >= price['b'] +10, columns=['a'])
sig2 = pd.DataFrame(price['a'] < price['b'] +10, columns=['b'])
signal = sig1.join(sig2)

signal1 = price.diff(1) > 0
signal2 = price.diff(1) < 0

tw = price.copy()
tw.set_value(tw.index,tw.columns,0) # Initialize Set everything to 0

tw[signal1] = -1.0
tw[signal2] = 1.0

s1 = bt.Strategy('long_short', [ bt.algos.WeighTarget(tw),
bt.algos.RunDaily(),
bt.algos.Rebalance()])
__main__:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

t = bt.Backtest(s1, price, initial_capital=1000000, commissions=(lambda q, p: abs(p * q) * comms) )

####and let's run it!
res = bt.run(t)
long_short
0% [######## ] 100% | ETA: 00:00:00Traceback (most recent call last):

  File "<ipython-input-1161-bf4398afa807>", line 4, in <module>
    res = bt.run(t)

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/bt/backtest.py", line 28, in run
    bkt.run()

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/bt/backtest.py", line 201, in run
    self.strategy.run()

  File "bt/core.py", line 1261, in bt.core.Strategy.run (bt/core.c:16268)

  File "bt/core.py", line 1206, in bt.core.AlgoStack.__call__ (bt/core.c:15643)

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/bt/algos.py", line 1333, in __call__
    target.rebalance(item[1], child=item[0], base=base)

  File "bt/core.py", line 722, in bt.core.StrategyBase.rebalance (bt/core.c:9929)

  File "bt/core.py", line 1079, in bt.core.SecurityBase.allocate (bt/core.c:14111)

Exception: Potentially infinite loop detected. This occured while trying to reduce the amount of shares purchased to respect the outlay <= amount rule. This is most likely due to a commission function that outputs a commission that is greater than the amount of cash a short sale can raise.


```

**Comment by JordanPlatts** [comment]
I just tried running it and I didn't get any issue. Do you have version [0.2.7](https://pypi.org/project/bt/)?

**Comment by Kinzowa** [comment]
Oh, I had version 0.2.5 !

Thanks !

**Comment by Kinzowa** [comment]
> I just tried running it and I didn't get any issue. Do you have version [0.2.7](https://pypi.org/project/bt/)?

Hi Jordan, 

I'm using the latest version 0.2.8 with another set of data (no short selling) and I face the same issue again. 

The problem to investigate the issue is that the exception is thrown by the function `allocate` which is inside the shared object `core.cpython-36m-x86_64-linux-gnu.so`. It which means there is no possibility to change the code in the function or even add some `print()`. Well at least this is what I understand based on my investigations.

Also, changing the commission to 0 doesn't solve the issue. This is how my commission function looks like : `commissions=(lambda q, p: abs(p * q) * 0)`. And the price series is everything but normal.

I would appreciate if you could give me hint on what could be done to investigate further up.

Thank you,
Kinzowa

**Comment by rajeshyogeshwar** [comment]
@Kinzowa One approach would be to download the source for the library to your system, make changes to core.py for debugging purposes and install the library from filesystem using `pip install -e <path-to-source>`. It helped me.
