### ISSUE TITLE
Bug: RunQuarterly()

### ISSUE THREAD

**Issue by rohithth** [pmorissette/bt#138]
RunQuarterly is supposed to rebalance the portfolio every quarter. But it doesn't mean that during the backtest, the purchase of the asset takes places after one quarter.

For eg. period: Jan 2008 - Dec 2008 | Ticker: BND & VTI
When RunQuarterly strategy is used, the purchase of BND & VTI happens in March 2008, and for the initial 3 months, the returns are 0! Which is a big flaw!

Kindly assist and correct. Thank you.

**Comment by JordanPlatts** [comment]
Just merged the pull request. Try it now.

**Comment by rohithth** [comment]
Below is the strategy code that I was using. Could you kindly let me know which line to replace in order to ensure that purchase happens on day one and then rebalancing trigger quarterly? Thank you!!

s = bt.Strategy('12pcdrift', [bt.algos.RunQuarterly(),
                       bt.algos.SelectAll(),
                       NewOrderedWeights([0.25, 0.75], 0.12),
                       bt.algos.Rebalance()])

**Comment by rohithth** [comment]
Entire code for reference:

import bt
import pandas

dataa = bt.get('BND, VTI',start='2008,01,02',end='2018,01,02')
dataa.head()


class NewOrderedWeights(bt.Algo):

    def __init__(self, weights, threshold=0.1):
        self.target_weights = weights
        self.threshold = threshold

    def __call__(self, target):
        
        if not target.positions.empty:
        
            newest_capital = target.universe.tail(1) * target.positions.tail(1)
            
            newest_capital_weightage = newest_capital / newest_capital.apply(lambda x: x.sum(), axis=1).values[0]
            weightage_deviations = newest_capital_weightage - self.target_weights
                
            if (abs(weightage_deviations) >= self.threshold).values.all():
                target.temp['weights'] = dict(zip(target.temp['selected'], self.target_weights))
        else:    
       
            target.temp['weights'] = dict(zip(target.temp['selected'], self.target_weights))
            
            
        target.last_trade_day = target.universe.tail(1).index    
        
        
        return True

class OrderedWeights(bt.Algo):
    def __init__(self, weights):
        self.target_weights = weights

    def __call__(self, target):
        target.temp['weights'] = dict(zip(target.temp['selected'], self.target_weights))
        return True


def my_comm(q, p):
    return abs(q) * 0.5


buyhold = bt.Strategy('bh', [bt.algos.RunOnce(),
                       bt.algos.SelectAll(),
                       NewOrderedWeights([0.25, 0.75]),
                       bt.algos.Rebalance()])
    
pcdrift = bt.Strategy('12pcdrift', [bt.algos.RunQuarterly(),
                       bt.algos.SelectAll(),
                       NewOrderedWeights([0.25, 0.75], 0.12),
                       bt.algos.Rebalance()])
    
bhport = bt.Backtest(buyhold, dataa, initial_capital=10000, commissions=my_comm)
driftport = bt.Backtest(pcdrift, dataa, initial_capital=10000, commissions=my_comm)


res_new1 = bt.run(bhport, driftport)
res_new1.stats    

res_new1.plot()
