### ISSUE TITLE
Float Division by Zero if not using Rebalance

### ISSUE THREAD

**Issue by yngstr** [pmorissette/bt#141]
Thank you guys for creating this tool, it has been very useful so far in my testing. I apologize if this is not the right place to be asking this question, but I'm running into an issue.

Testing out a simple strategy of 1.0 weight on a single equity, I'm able to produce results that broadly match a simple returns calculation (price.pct_change().cumsum()). I believe the difference in results is due to re-balancing, but when I try to run the test without the Rebalance algo, I get float division by zero error:

```
<ipython-input-53-c33459b5d55d> in <module>()
----> 1 res = bt.run(t)

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\bt\backtest.pyc in run(*backtests)
     28         bkt.run()
     29
---> 30     return Result(*backtests)
     31
     32

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\bt\backtest.pyc in __init__(self, *backtests)
    315     def __init__(self, *backtests):
    316         tmp = [pd.DataFrame({x.name: x.strategy.prices}) for x in backtests]
--> 317         super(Result, self).__init__(*tmp)
    318         self.backtest_list = backtests
    319         self.backtests = {x.name: x for x in backtests}

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in __init__(self, *prices)
    644         self._end = self._prices.index[-1]
    645         # calculate stats for entire series
--> 646         self._update(self._prices)
    647
    648     def __getitem__(self, key):

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in _update(self, data)
    653
    654     def _update(self, data):
--> 655         self._calculate(data)
    656         # lookback returns dataframe
    657         self.lookback_returns = pd.DataFrame(

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in _calculate(self, data)
    666         for c in data.columns:
    667             prc = data[c]
--> 668             self[c] = PerformanceStats(prc)
    669
    670     def _stats(self):

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in __init__(self, prices, rf)
     61         self.rf = rf
     62
---> 63         self._update(self.prices)
     64
     65     def set_riskfree_rate(self, rf):

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in _update(self, obj)
     80     def _update(self, obj):
     81         # calc
---> 82         self._calculate(obj)
     83
     84         # update derived structure

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in _calculate(self, obj)
    188         self.daily_mean = r.mean() * 252
    189         self.daily_vol = r.std() * np.sqrt(252)
--> 190         self.daily_sharpe = r.calc_sharpe(rf=self.rf, nperiods=252)
    191         self.daily_sortino = calc_sortino_ratio(r, rf=self.rf, nperiods=252)
    192         self.best_day = r.max()

C:\Users\dyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\ffn\core.pyc in calc_sharpe(returns, rf, nperiod
s, annualize)
   1181
   1182     er = returns.to_excess_returns(rf, nperiods=nperiods)
-> 1183     res = er.mean() / er.std()
   1184
   1185     if annualize:

ZeroDivisionError: float division by zero
```

I am using the same weights algo as shown in the SMA Cross example:

```
class WeighTarget(bt.Algo):

	def __init__(self, target_weights):
		self.tw = target_weights

	def __call__(self, target):
		if target.now in self.tw.index:
			w = self.tw.loc[target.now]

			target.temp['weights'] = w.dropna()

		return True
```

Again, apologies if this is the wrong place to ask, 99% chance I'm just missing something, 1% chance this is a real "Issue"

**Comment by JordanPlatts** [comment]
I think without the rebalance algo bt wouldn't buy/sell any security. Therefore, you would expect all of the returns to be 0 and the std dev to be 0 which would cause the issue. You can see that issue here. https://github.com/pmorissette/ffn/issues/14

Which rebalance algo we're you using?

**Comment by JordanPlatts** [comment]
Sorry not rebalance algo. I meant which run algo did you use?

**Comment by JordanPlatts** [comment]
I don't know if it is because of the division issue because I fixed that issue and pushed the changes to github but I haven't pushed those changes to pip and it works locally for me.

Try setting `integer_positions=False`

    t = bt.Backtest(s,df_px,integer_positions=False)

**Comment by yngstr** [comment]
Setting` integer_positions=False` worked!

Thanks Jordan! While I'm able to loop through and run separate backtests for each ticker, then get the pnl data from the res.plot using:

`ax = plt.gca()
line = ax.lines[0]
`

I feel like there may be a better way to look at the sub-segments of my back-tested pnl.

**Comment by JordanPlatts** [comment]
To be honest, I haven't done too much analysis on the strategies I have backtested yet.  I got caught up with working on the backtesting tool.

Check out https://github.com/pmorissette/ffn/issues/37

We may switch over to use pyfolio from quantopian. If we did that, then the code to analyze backtests, get returns, evaluate each sub strategy will probably all change.

**Comment by yngstr** [comment]
I'm getting this again, while using `integer_positions=False`

```
df_px = df[cols].fillna(0.0)
twx = tw[cols].fillna(0.0)

s = bt.Strategy('Running',[bt.algos.WeighTarget(twx),bt.algos.Rebalance()])
t = bt.Backtest(s,df_px,integer_positions=False)
res = bt.run(t)
```

**Comment by JordanPlatts** [comment]
I think it should be written where it doesn't calculate the statistics unless you want it too....

Either way this issue should be fixed if you use the code from github. I am working with @pmorissette to push the code updates to pip in an automated way but for now you would need to download the source code directly and reference it like

    import sys
    sys.path.insert(0, "\\\\code\\directory\\")
    import ffn
    sys.path.insert(0, "\\\\code\\directory\\")
    import bt

**Comment by JordanPlatts** [comment]
Ok I just pushed an update to pypi for both bt and ffn. This should be fixed now. I will close the issue but let me know if it isn't.
