### ISSUE TITLE
Example fails with pandas-datareader 0.6.0

### ISSUE THREAD

**Issue by aabdullah-bos** [pmorissette/bt#142]
I've installed bt version `0.2.5`, using `pip install bt`, and tried to run the example:

```python
import bt
data = bt.get('spy,agg', start='2010-01-01')
```

but I get the following error.

```
ImmediateDeprecationError:
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.
```

I looked at the docs for `pandas-datareader` and it mentions that the yahoo and google APIs have been immediately deprecated. Is there a plan for moving forward?

**Comment by JordanPlatts** [comment]
Update the example to use another data source I guess.

https://github.com/wilsonfreitas/awesome-quant#data-sources

Updating and adding more examples is on the to do list.
