### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/bt#146]
Hi, 

I'm trying to run the example as follows:

import bt

# fetch some data
data = bt.get('SPY:close,AGG:close', provider=ffn.data.web, 
              start='2014-01-01', source='iex')
              

# Put the strategy together.
strat = bt.Strategy('strat1', [bt.algos.RunMonthly(),
                    bt.algos.SelectAll(),
                    bt.algos.WeighEqually(),
                    bt.algos.Rebalance()])
                    
# Create a backtest
test = bt.Backtest(strat, data)
res = bt.run(test)

and I'm getting an error:

TypeError: unsupported operand type(s) for -: 'str' and 'relativedelta'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-152-1a1e98e48529> in <module>()
     16 
     17 # Create a backtest
---> 18 test = bt.Backtest(strat, data)
     19 res = bt.run(test)
     20 
C:\PROGRAM FILES\MINICONDA3\lib\site-packages\bt\backtest.py in __init__(self, strategy, data, name, initial_capital, commissions, integer_positions, progress_bar)
    146         data = pd.concat([
    147             pd.DataFrame(np.nan, columns=data.columns,
--> 148                          index=[data.index[0] - pd.DateOffset(days=1)]),
    149             data])
    150 
C:\PROGRAM FILES\MINICONDA3\lib\site-packages\pandas\tseries\offsets.py in __rsub__(self, other)
    407             return other - self
    408         return self.__class__(-self.n, normalize=self.normalize,
--> 409                               **self.kwds) + other
    410 
    411     def __mul__(self, someInt):
C:\PROGRAM FILES\MINICONDA3\lib\site-packages\pandas\tseries\offsets.py in __add__(self, other)
    387             return other + self
    388         try:
--> 389             return self.apply(other)
    390         except ApplyTypeError:
    391             return NotImplemented
C:\PROGRAM FILES\MINICONDA3\lib\site-packages\pandas\tseries\offsets.py in wrapper(self, other)
     68                 other = other.tz_localize(None)
     69 
---> 70             result = func(self, other)
     71             if self._adjust_dst:
     72                 result = tslib._localize_pydatetime(result, tz)
C:\PROGRAM FILES\MINICONDA3\lib\site-packages\pandas\tseries\offsets.py in apply(self, other)
    232             else:
    233                 for i in range(-self.n):
--> 234                     other = other - self._offset
    235 
    236             if tzinfo is not None and self._use_relativedelta:
TypeError: unsupported operand type(s) for -: 'str' and 'relativedelta'

Am I doing something obviously wrong ?

D

**Comment by JordanPlatts** [comment]
I don't have that issue. It seems to be some issue with `pd.DateOffset(days=1)`

Try upgrading pandas.
`conda update pandas`

Also make sure the index of your dataframe is a date.

**Comment by JordanPlatts** [comment]
Check out issue #147

**Comment by csc5a2g** [comment]
Thanks, your tips and issue 147 have got me up and running !

Ta
