### ISSUE TITLE
pandas-datareader has deprecated Yahoo download

### ISSUE THREAD

**Issue by brandon-rhodes** [pmorissette/bt#147]
Your project looks great — the front-page example is well-written and compelling, and lets the curious reader immediately see what the code can do! But I ran into a snag while running it:

```
data = bt.get('spy,agg', start='2010-01-01')
```

```
ImmediateDeprecationError                 Traceback (most recent call last)
<ipython-input-4-d42d1799a47c> in <module>()
----> 1 data = bt.get('spy,agg', start='2010-01-01')
      2 data.head()

...

~/usr/ipynb/lib/python3.6/site-packages/pandas_datareader/data.py in get_data_yahoo(*args, **kwargs)
     61 
     62 def get_data_yahoo(*args, **kwargs):
---> 63     raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Actions'))
     64     return YahooDailyReader(*args, **kwargs).read()
     65 

ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues
```

You might want to pivot your opening example to a different data service — or a different data library — so that users can run it successfully.

**Comment by brandon-rhodes** [comment]
Okay, I figured it out.

First, "pandas-datareader" 0.6.0 doesn't support Yahoo, but the new version will have it working again. So I ran:

```
pip install https://github.com/pydata/pandas-datareader/archive/master.zip
```

Second, it now seems to return a dictionary rather than a plain dataframe, so that I had to adjust this clause:

```
    if field:
        return tmp[field]
    else:
        return tmp
```

so that it instead reads:

```
    if field:
        return tmp['prices'][field]
    else:
        return tmp
```

With those tweaks, I'm now moving again!

**Comment by brandon-rhodes** [comment]
Okay, another problem: the data reader returned a dataframe with Python date objects in the index, leading to an obscure error when your code tried to reindex by month. I fixed it with:
```
data2 = data.copy()
data2.index = pd.to_datetime(data.index)
data2.head()
```
so that my index was a native Pandas date type.

The library's working now! I can see a graph! This is going to be great :)

**Comment by JordanPlatts** [comment]
Awesome! I am working on replacing the example and adding more. Any help would be appreciated.

**Comment by JordanPlatts** [comment]
@csc5a2g
