### ISSUE TITLE
Understanding the Strategy Algo Model

### ISSUE THREAD

**Issue by aabdullah-bos** [pmorissette/bt#148]
Hello @pmorissette ,

Thank you for developing bt. I am trying to implement a backtest for a strategy that trades based on an an indicator basically, I want to go long and stay long while an indicator is positive, and exit my position when the indicator goes negative. I am thinking that I should subclass an Algo that will either give me a 1 or a -1. But it's not clear to me what information needs to be passed on to the target. Do you have any advice on how I can get a better understanding of the object model? Of course, i can look at the code as well ;)

**Comment by JordanPlatts** [comment]
I just uploaded an example that uses trend to go long and to exit the market.

I apologize if there are any issues because I just threw it together.

It's in the examples folder named examples and it is named trend.
