### ISSUE TITLE
Can you confirm that not lag or delay is required to be explicitly stated?

### ISSUE THREAD

**Issue by nikolas-joyce** [pmorissette/bt#149]
Thanks for your work.
I just wanted to confirm that one does not need to explicitly refer  to a lagged bar to eliminated snooping errors.
in this type of way.

df_comms_monthly['GLD_Trade_count'] = np.where(
    df_comms_monthly['GLD_Regime'] != df_comms_monthly['GLD_Regime']**_.shift(1)_**, 1, 0)  <<-----

thx

**Comment by JordanPlatts** [comment]
Just to confirm you are using
    df_comms_monthly['GLD_Trade_count']
as a signal and you aren't sure that
    df_comms_monthly.loc[target.now,'GLD_Trade_count']
Refers to the signal at time target.now or target.now + 1.

If that's the question, then it refers to target.now

If that's not the question, then please clarify.

**Comment by nikolas-joyce** [comment]
Sort of... I am wondering if the default documentation examples are tradable in that they don’t have a look ahead bias.   there is no explicit lag on the entry and exit conditions. If I was to write an entry condition in pandas I need to lag the entry. I am wondering if such a thing is necessary in bt.

Sent from my iPhone

On May 18, 2018, at 5:18 PM, Jordan Platts <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to confirm you are using
df_comms_monthly['GLD_Trade_count']
as a signal and you aren't sure that
df_comms_monthly.loc[target.now,'GLD_Trade_count']
Refers to the signal at time target.now or target.now + 1.

If that's the question, then it refers to target.now

If that's not the question, then please clarify.

**Comment by JordanPlatts** [comment]
The code is set up to update the prices to time t and then run the algos. I don't lag for daily close prices because I think about the strategy trading the next morning (t+1) at the open. So it doesn't have a look ahead bias. With that said, the assumption that you can trade at the current prices may not be appropriate so you can add transaction costs or delay actions if you want.

**Comment by JordanPlatts** [comment]
As an aside, one of the reasons that I like this code base so much is because it is easy to walk through using a debugger. The code isn't too complex to understand what is happening behind the scenes.

I am going to close this issue. Let me know if you have any other questions.

**Comment by nikolas-joyce** [comment]
Thanks very much for your response.  Can you point me to an example somewhere where the choice of execution ( at next bar open versus next bar close) is illustrated? Thx.

Sent from my iPhone

On May 19, 2018, at 8:41 AM, Jordan Platts <notifications@github.com<mailto:notifications@github.com>> wrote:


As an aside, one of the reasons that I like this code base so much is because it is easy to walk through using a debugger. The code isn't too complex to understand what is happening behind the scenes.

I am going to close this issue. Let me know if you have any other questions.
