### ISSUE TITLE
Is there a specific way to control reinvestment in bt?

### ISSUE THREAD

**Issue by nikolas-joyce** [pmorissette/bt#155]
I don't see to be able to see how one could account for the reinvestment of profits and the rate the profits are reinvested. Is this possible though the fund or cash flow functions that are already present?
class bt.algos.CapitalFlow(amount)?
thx

**Comment by JordanPlatts** [comment]
I have not come across this issue so hopefully someone else can help you.

**Comment by nikolas-joyce** [comment]
Is there some kind of default reinvestment contemplated when you specify the initial dollar investment? Are all profits reinvested?

Sent from my iPhone

On Jun 6, 2018, at 11:11 AM, Jordan Platts <notifications@github.com<mailto:notifications@github.com>> wrote:


I have not come across this issue so hopefully someone else can help you.

**Comment by JordanPlatts** [comment]
All profits are reinvested back into the strategy. 

`bt` keeps track of returns by tracking the number of shares you own. Whenever you rebalance you sell some shares that you are overweight(price*# share/sum of all price*#share > x%) and buy some shares that you are underweight.
