### ISSUE TITLE
Which algo for a Pairs strategy

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/bt#157]
Hi,

I'm interested in using bt to try out some pairs ideas. I've had a play around with the examples provided but I'm struggling to see how a I can tell bt that I want it to be simultaneously long one stock and short the other. I could even be flat across both if the signal isn't there, so put simply there are three options (1, -1, 0) 

Does anyone know of an algo that allows me to do this or better still have an example of how I night go about building one?

Thanks.

**Comment by newtux** [comment]
The SMA Crossover Strategy at http://pmorissette.github.io/bt/examples.html has a good example of going long/short. 

My understanding is you either use WeighTarget or implement your own Algo that sets negative weights under the conditions you need.
