### ISSUE TITLE
Backtesting with Shorting

### ISSUE THREAD

**Issue by lschaupp** [pmorissette/bt#158]
Is this feature available in the current version?

**Comment by JordanPlatts** [comment]
Yes it is. You can set the negative weight just like setting a positive weight.

**Comment by Kinzowa** [comment]
But is it possible to allocate negative weights with `bt.algos.WeighMeanVar()` ? from what I understand this is not possible.

What about a workaround that creates a composite security to simulate - or replicate - a short position of a security ? something like `prices[['SPX_short']] = 1/prices[['SPX']]`. 

This is not a propper way of backtesting short, is there another solution ?

**Comment by JordanPlatts** [comment]
You should be able to get negative weights in WeighMeanVar

Try setting `bounds=(None, None)` in the constuctor for WeighMeanVar. The scipy minimization routine should then set no bounds on the weights. It may not always work though.


There is a closed form solution for the mean variance optimal portfolio with only a fully invested constraint and no long only constraint. It is probably better to just use that in this case. It's equation 1.32 in [here](https://faculty.washington.edu/ezivot/econ424/portfolioTheoryMatrix.pdf). Or simply `V^{-1} u / (1^{t} V^{-1} u)` where V is the covariance matrix and u is the expected excess return.

**Comment by Kinzowa** [comment]
> Try setting bounds=(None, None) in the constuctor for WeighMeanVar. The scipy minimization routine should then set no bounds on the weights. It may not always work though.

Interesting. From what I see with `bounds=(None, None)` weights go well above 1 or below -1 (~ from 5 to -25) and the backtest crash before complete. This is the code I use, not sure if I miss something.

```
        securities = ['AAA', 'BBB', 'CCC', 'DDD', 'EEE']
                
        # Create strategy  
        s = bt.Strategy('s1', [
                               bt.algos.RunEveryNPeriods(2),
                               bt.algos.SelectWhere(selection[securities]),
                               bt.algos.SelectMomentum(3, pd.DateOffset(days=3)),
                               bt.algos.WeighMeanVar(lookback=pd.DateOffset(days=15),
                                                     bounds=(None, None)),
                               bt.algos.LimitDeltas(limit=1),
                               bt.algos.Rebalance()
                               ])

        # create a backtest and run it
        test = bt.Backtest(s, 
                           prices[securities], 
                           initial_capital = 10000, 
                           commissions = (lambda q, p: abs(p * q) * 0.0015)
                           )
        res = bt.run(test) 
```
When I set `bounds=(-1, 1)` it works better and I make two observations : 
- sometime weights go below -1 or above 1 (~ from 1.1 to -1.2)
- weights remain between 0 and 1 when there are only one or two securities. Weights go to negative territory when there are at least three securities. 

Do you think this is a normal behavior ? Also I was wondering how `WeighMeanVar()` could allocate negative weights when the selection process uses `SelectMomentum()` which is supposed to select the top n securities based on the total return. Does it means negative weights can be allocated to securities when total return is negative ?
