### ISSUE TITLE
Child strategies

### ISSUE THREAD

**Issue by HedgeShot** [pmorissette/bt#160]
Hi,

First of all, thanks for your lib! I have some questions about:

- strategy of strategies: Is it possible to get the stats/weights of a child strategy? 
- strategy of strategies: Is there a way to get a correlation matrix between children strategies?

Thanks

**Comment by JordanPlatts** [comment]
- strategy of strategies: Is it possible to get the stats/weights of a child strategy?

Yes.

Check out the example I just posted [here](https://github.com/pmorissette/bt/blob/master/examples/Strategy_Combination.ipynb). Hopefully it helps.

- strategy of strategies: Is there a way to get a correlation matrix between children strategies?

Once you have a dataframe of prices, just run `pdf.corr()` and it should return the correlations.

**Comment by HedgeShot** [comment]
Thanks. 

Indeed it works but you need to call `run` at least twice. I was looking for a way of getting the child equity curves after calling `run(multi Strat with children)` to save compute time. 

By the way, is there an issue by simply calling:
`run(strat1, strat2, multi Strat with children)` 
in a single line instead of doing like in your example where you run each strategy first and the merge to run the multi strategy?

It seems to work fine but as you don't do it in your example, I probably miss something.
