### ISSUE TITLE
Total return calculation when shorting

### ISSUE THREAD

**Issue by dcimring** [pmorissette/bt#161]
Hi,

Thanks for a fantastic library.

When using weights of -1 (i.e. shorting) I get different results to what I would expect. For example take a simple test stock that starts at 100, goes up to 110, then falls to 95. Set the weight to -1 for all dates (we are shorting):
```
names = ['test']
dates = pd.date_range(start='2017-01-01',end='2017-01-03')

df = pd.DataFrame(
    [100.0,110.0,95.0],
    index = dates,
    columns = names
)

w = df.copy()
w[:] = -1

test = bt.Strategy('test', [WeighTarget(w),
                                    bt.algos.Rebalance()])

t = bt.Backtest(test, df)
res = bt.run(t)
res.display()

Stat                 test
-------------------  ----------
Start                2016-12-31
End                  2017-01-03
Risk-free rate       0.00%
Total Return         2.27%
....
```

My manual calculation for the total return is 5.26% (you effectively sold at 100 and purchased at 95).

(Perhaps the difference has to do with how much capital is considered allocated. However I have tried a few different assumptions for this but still can't match the reported 2.27%)

Please let me know if you need any more info.

Kind regards
Daniel

**Comment by JordanPlatts** [comment]
Run `res.get_transactions()`


                         price      quantity
    Date       Security                     
    2017-01-01 test      100.0 -10000.000000
    2017-01-02 test      110.0   1818.181818
    2017-01-03 test       95.0  -2583.732057

You can see it rebalances daily.

Change it to 

     test = bt.Strategy('test', [bt.algos.RunOnce(),
                                bt.algos.WeighTarget(w),
                                 bt.algos.Rebalance()
                                ]
     )

The return is now 5%.

You did purchase at 95 and sell at 100. Hence the $5 per share but your initial capital was $1,000,000.

So you sold 10,000 shares @ 100 and bought 10,000 shares @ 95. Hence $50,000/$1,000,000=5% return.

Also I usually set `t = bt.Backtest(test, df,integer_positions=False)` to avoid worrying about getting an exact amount of shares at each purchase but that obviously didn't cause any problems here.
