### ISSUE TITLE
Failed building wheel for bt

### ISSUE THREAD

**Issue by yomoko** [pmorissette/bt#163]
Hi I can't install bt. It says failed building wheel for bt. Why is that? Thanks
![image](https://user-images.githubusercontent.com/33768560/42888110-850b09c2-8a75-11e8-8650-9ab8b0bf02fc.png)

**Comment by JordanPlatts** [comment]
I think it may be because you do not have the right c++ compiler. Not really sure though.

Check out https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required

**Comment by CedricAnover** [comment]
I also have the same issue

![failwheel](https://user-images.githubusercontent.com/27037068/44307645-6a827c80-a3d8-11e8-9387-2a64435ff1dd.PNG)

**Comment by kevinyuehu** [comment]
I met the same problem, but finally I install bt on windows by installing it on WSL first. After installing bt on WSL, just copied the installed library files directly to the python on windows.

**Comment by pymoix** [comment]
Thanks for the info. In the meantime I created an isolated conda environment with Python 3.5 and it works. This is maybe an issue with 3.6

**Comment by timkpaine** [comment]
You need to make sure your compiler paths are setup. , e.g. by running `vcvarsall.bat` which should be in the `VC` directory in your visual studio install.
