### ISSUE TITLE
How to configure SelectHasData() ?

### ISSUE THREAD

**Issue by Kinzowa** [pmorissette/bt#167]
Hello,

Some of my price series start with abnormal values and it causes backtest bias, data looks like this : 

```
timestamp
2017-05-20 00:00:00+00:00         NaN
2017-05-21 00:00:00+00:00         NaN
2017-05-22 00:00:00+00:00         NaN
2017-05-23 00:00:00+00:00    100000.0 # abnormal value here
2017-05-24 00:00:00+00:00    00006.54
2017-05-25 00:00:00+00:00    00006.33
2017-05-26 00:00:00+00:00    00006.13
2017-05-27 00:00:00+00:00    00006.24
```
How can I configure `SelectHasData()` to wait for at least 2 periods after `NaN` ? so that selection will starts the 2017-05-25. 

I have tried `SelectHasData(pd.DateOffset(days=2), min_count=2)` or just `SelectHasData(pd.DateOffset(days=2)` but it doesn't work as expected and I still have the same problem. What am'I missing here ?

Thank you,

**Comment by HedgeShot** [comment]
I have seen a few issues with `SelectHasData()` but what you are describing seems to work for me.

Here is my algo
```
testalgo = bt.Strategy('test', 
                [bt.algos.RunDaily(),
                 bt.algos.SelectHasData(pd.DateOffset(days=2), min_count=2),
                 PrintSelector(), 
                 bt.algos.WeighEqually(),
                 bt.algos.Rebalance()])
```
`PrintSelector` is just printing `target.now` and `target.temp['selected']`.

My data frame as NaN values on the first three dates (2007-05-07, 2007-05-08, 2007-05-09) and values from 2007-05-10 on. I expected to have tickers in `target.temp['selected']`on 2007-05-11, nothing before.

My console shows: 
```
2007-05-07 00:00:00
[]
#######
2007-05-08 00:00:00
[]
#######
2007-05-09 00:00:00
[]
#######
2007-05-10 00:00:00
[]
#######
2007-05-11 00:00:00
['SPY', 'VNQ', 'RWO', 'GLD']
```
So it is avoiding NaN's entries + the first date. What I discovered running this little example is that on every subsequent Monday, `target.temp['selected']` is empty... This is clearly an issue. It should offset by business days or integer position to avoid the problem. 

Hope this helps.

**Comment by JordanPlatts** [comment]
I am checking the functionality using the test case in test_algos.py

    def test_select_has_data():
        algo = algos.SelectHasData(min_count=3, lookback=pd.DateOffset(days=3))

        s = bt.Strategy('s')

        dts = pd.date_range('2010-01-01', periods=10)
        data = pd.DataFrame(index=dts, columns=['c1', 'c2'], data=100.)
        data['c1'].ix[dts[0]] = np.nan
        data['c1'].ix[dts[1]] = np.nan

        s.setup(data)
        s.update(dts[2])

        assert algo(s)
        selected = s.temp['selected']
        assert len(selected) == 1
        assert 'c2' in selected

Stepping through the code in the test case

![image](https://user-images.githubusercontent.com/3238194/43272382-d6534850-90c7-11e8-84d7-2282de422287.png)

You can see filt is the data filtered on only looking back from the current date 2010-01-03 back the lookback and cnt only contains securities in that dataframe with at least the min_count of observations. Then temp['selected'] ends up with the names of the securities.

I agree with @HedgeShot it seems to make more sense to be an integer offset or at least to have that capability as well.

**Comment by HedgeShot** [comment]
The code looks indeed like what Jordan said. `Algo` is a class of the bt package.
