### ISSUE TITLE
How can I use to backtest the bitcoin cryptocurrency

### ISSUE THREAD

**Issue by ramoslin02** [pmorissette/bt#172]
How can I use to backtest the bitcoin cryptocurrency? it seem that the position can be float number , the commission is also different from the traditional market

**Comment by amine988** [comment]
What do you want to achieve exactly ? 
If you describe the assets you have :Do you have bitcoin prices between several market exchanges or is it one bitcoin price asset? Do you want to allocate between cash and bitcoin or other crypto?

Did you define how you will compute the fees you want to take into account?

**Comment by timkpaine** [comment]
not enough information provided
