### ISSUE TITLE
Conda install bt

### ISSUE THREAD

**Issue by raeisi** [pmorissette/bt#173]
Could you please advise how I can install bt from Conda?

**Comment by JordanPlatts** [comment]
You should be able to run

    pip install bt

from an anaconda prompt.

**Comment by LuigiRibon** [comment]
I tried to install bt with the pip install command within an anaconda prompt but I get an error..."Microsoft C++ 14.0 is required...".

Is it possible to use a conda install command?

**Comment by Dougz00** [comment]
I used conda install bt but that failed as conda was unable to find the package using the default channels. I used the pip install and also got the  C++ runtime error. I tried installing the VS 14 redistributable but that also failed citing that conflicted with an existing VS package.

**Comment by timkpaine** [comment]
You need a valid and functioning vc14 compiler for this repo.
