### ISSUE TITLE
bug in get_transactions

### ISSUE THREAD

**Issue by wukan1986** [pmorissette/bt#177]
`positions = pd.DataFrame({x.name: x.positions for x in s.securities})`

if children have same security and with different positions. it only get last position,
not the sum of position.

so the result of get_transactions is not same as below:

```
pos = None
for bl in res.backtest_list:
    for k,v in bl.strategy.children.items():
        if pos is None:
            pos = v.positions
        else:
            pos = v.positions+pos

print(pos)
```

**Comment by exted** [comment]
I am also finding similar issues with the positions calculation method

#175

**Comment by wukan1986** [comment]
> I am also finding similar issues with the positions calculation method
> 
> #175

Good Job!
