### ISSUE TITLE
is there any method we can get p/l for each trade?

### ISSUE THREAD

**Issue by davidhuang123** [pmorissette/bt#178]
Hello, 

Thanks for sharing the project, I found bt a very flexible and useful package for backtesting.
I am writing to ask if there is any method for print out p/l for each trade?
I am aware we can get transactions or positions for each date, but couldn't find methods for p/l for trade.
Please advise.

**Comment by boyac** [comment]
@davidhuang123 maybe you can refer to this article https://www.investopedia.com/ask/answer/07/portfolio_calculations.asp, it seems to be sufficient by knowing the portfolio percentage change due to different purchase prices of a stock.

**Comment by ClovisC86** [comment]
> Thanks for sharing the project, I found bt a very flexible and useful package for backtesting.
> I am writing to ask if there is any method for print out p/l for each trade?
> I am aware we can get transactions or positions for each date, but couldn't find methods for p/l for trade

Not that I know of, I have had to create mine to get daily PnL for each security you've traded in your backtest (you can do a cumsum() to get total PnL if you need)
Pass a list of your securities and backtest object to the function below.

secNames = [c for c in t.strategy.children]

def getDailyPnL(secNames,backtest):
    indx = backtest.strategy.prices.index
    PnL = pd.DataFrame(0,index = indx,columns = secNames)

    for secName in secNames:
        s = backtest.strategy.children[secName]
        pos = s.positions.copy()
        prcs = s.prices.copy()          
        PnL.loc[indx[2]:,secName] = pos.shift(periods=1).loc[indx[2]:indx[-1]] * (prcs.loc[indx[2]:indx[-1]] - prcs.shift(periods=1).loc[indx[2]:indx[-1]])
        
    return PnL

**Comment by boyac** [comment]
@ClovisC86 Thanks for sharing. A quick question, is the cost basis average purchased price or FIFO method? Thanks!

**Comment by ClovisC86** [comment]
@boyac , yes that's how I wrote it. The frequency of your PnL will match that of your backtest (which in my case is daily). If your  strategy rebalances quarterly then you should sum up your daily PnL's from start to end of your rebalancing periods
