### ISSUE TITLE
"pip install bt" fails

### ISSUE THREAD

**Issue by AlexBThomsen** [pmorissette/bt#179]
I had the old bt version and when I updated, it threw an error. I therefore uninstalled and tried to re-install. The error remains. Pip install with other libraries works. 

Failed building wheel for bt
  Running setup.py clean for bt
Failed to build bt
Installing collected packages: bt
  Running setup.py install for bt ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_9/09p9mvmx1837tbfxzxjzg74h0000gn/T/pip-install-q1pecp88/bt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_9/09p9mvmx1837tbfxzxjzg74h0000gn/T/pip-record-oii08qzf/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/bt
    copying bt/algos.py -> build/lib.macosx-10.7-x86_64-3.6/bt
    copying bt/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/bt
    copying bt/core.py -> build/lib.macosx-10.7-x86_64-3.6/bt
    copying bt/backtest.py -> build/lib.macosx-10.7-x86_64-3.6/bt
    running build_ext
    building 'bt.core' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/bt
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -c bt/core.c -o build/temp.macosx-10.7-x86_64-3.6/bt/core.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_9/09p9mvmx1837tbfxzxjzg74h0000gn/T/pip-install-q1pecp88/bt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_9/09p9mvmx1837tbfxzxjzg74h0000gn/T/pip-record-oii08qzf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_9/09p9mvmx1837tbfxzxjzg74h0000gn/T/pip-install-q1pecp88/bt/

**Comment by fheilz** [comment]
@pmorissette Please close this issue.
