### ISSUE TITLE
Updating to bt 0.2.7 created a new error

### ISSUE THREAD

**Issue by AlexBThomsen** [pmorissette/bt#180]
After updating to the new bt, I got the error : TypeError: unsupported operand type(s) for +: 'slice' and 'int' on the "res = bt.run".

**code:**

    `#Format price data
     csv_f = pd.read_csv('cryptodata.csv')
     data = pd.DataFrame(csv_f)
     data['date'] = pd.to_datetime(data['date'])
     data.set_index('date', inplace = True)
     df1 = data[:-1]
     df1 = df1.dropna()

     def momentum_strategy(data, mom1 = 15, mom2 = 30, mom3 = 60, selection = 5 , cost = 0.025):

       #Momentum calc 
       mom_1 = data.pct_change(mom1)
       mom_2 = data.pct_change(mom2)
       mom_3 = data.pct_change(mom3)

       mom_average = (mom_1 + mom_2 + mom_3) / 3
       mom_average = mom_average.dropna()

       #Weight
       mom_average_rank = mom_average.rank(1, ascending = True)
       mom_selection = selection > mom_average_rank

       #create strategy

       s = bt.Strategy('mom_s',[bt.algos.SelectWhere(mom_selection),
                        bt.algos.RunWeekly(),
                        bt.algos.SelectAll(),
                        bt.algos.WeighEqually(),
                        bt.algos.Rebalance()])

       return bt.Backtest(s, data, commissions = lambda q, p: max(100, abs(q) * cost ))

    #create the backtests 
    mom_1 = momentum_strategy(df1, 15, 30, 60, 5, 0.025)

    #run backtests
    res = bt.run(mom_1)`

**Data**

df 1

date                 |        BTC       |      ETH  ....
2016-10-28    |        670        |      11
...
2018-12-27    |        3700      |      122

mom_Selection

date                |         BTC        |     ETH  ....
2017-04-25   |         True         |    False
...
2018-12-27    |         True      |       True

**Full error:**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-87-aa655677d8b1> in <module>()
      1 #run backtests
----> 2 res = bt.run(mom_1, benchmark)

/anaconda3/lib/python3.6/site-packages/bt/backtest.py in run(*backtests)
     26     # run each backtest
     27     for bkt in backtests:
---> 28         bkt.run()
     29 
     30     return Result(*backtests)

/anaconda3/lib/python3.6/site-packages/bt/backtest.py in run(self)
    199 
    200             if not self.strategy.bankrupt:
--> 201                 self.strategy.run()
    202                 # need update after to save weights, values and such
    203                 self.strategy.update(dt)

/anaconda3/lib/python3.6/site-packages/bt/core.cpython-36m-darwin.so in bt.core.Strategy.run()

/anaconda3/lib/python3.6/site-packages/bt/core.cpython-36m-darwin.so in bt.core.AlgoStack.__call__()

/anaconda3/lib/python3.6/site-packages/bt/algos.py in __call__(self, target)
    163                 index_offset = 1
    164 
--> 165             date_to_compare = target.data.index[index + index_offset]
    166             date_to_compare = pd.Timestamp(date_to_compare)
    167 

TypeError: unsupported operand type(s) for +: 'slice' and 'int'

**Comment by AlexBThomsen** [comment]
Finally took a while but somehow got it work to by adding:

df1 = df[~df.index.duplicated(keep = 'first')]

**Comment by timkpaine** [comment]
closing as stale, feel free to reopen if you think theres something that can be improved in `bt` itself (some data-cleaning is to be expected depending on the source and out of scope for this library).
