### ISSUE TITLE
How to specify different commissions to different asset?

### ISSUE THREAD

**Issue by yiwei-prowler** [pmorissette/bt#181]
When backtesting futures for example, different futures have different commissions. How to specify different commissions to different futures? Also, in some market, for example, Chinese, the commission of an asset can change over time. How to deal with this? Thanks.

**Comment by zwdnet** [comment]
I think you can write a commission function and sent it to the Strategy.Like this:
def getFee(quantity, price):
    rate = 0.0003
    fee = quantity*price*rate
    if fee < 0.1:
        fee = 0.1
    return fee
then use strategy.set_commissions(getFee) to sent the function to the Strategy.
By the way, are you Chinese? I'm Chinese too. I have a question that how to create a strategy which can sell the stocks when the return achieve a level?（如何建立带止盈的策略？）Thank you. 
My blog is : https://blog.csdn.net/zwdnet

**Comment by yiwei-prowler** [comment]
Thanks for the reply. I will give it a try.

And yes, I'm Chinese. For Chinese stock strategies. I used the 大智慧 DTS
trading platform. It is a piece of shit but it can trade stocks from your
code, meaning it has APIs to buy and set stocks, including selling stocks
at target price.

I didn't not put my strategy logic in DTS because that would leak our
trading secret. Instead, I run our strategy code in a different process,
and use zeroMQ to communicate between our own strategy and the DTS platform.

Regards,
Yi Wei
