### ISSUE TITLE
Question with RunOnDate(*date)

### ISSUE THREAD

**Issue by davidhuang123** [pmorissette/bt#182]
Hello,
I am trying out the RunOnDate() function witht the code below, it works well.

```
import bt
data = bt.get('aapl,msft',start='2018-01-01',end='2018-12-31')

s = bt.Strategy('s', [                                            
                       bt.algos.RunOnDate('2018-01-08','2018-02-08'),
                       bt.algos.SelectAll(),  
                       bt.algos.WeighEqually(),
                       bt.algos.Rebalance()])  

test = bt.Backtest(s , data, initial_capital=1000000.0) 
res = bt.run(test)
```
but if I replace the date with a list as code below, I will see error:

```
date_list =['2018-01-08','2018-02-08']

s = bt.Strategy('s', [                                            
                       bt.algos.RunOnDate(date_list),
                       bt.algos.SelectAll(),  
                       bt.algos.WeighEqually(),
                       bt.algos.Rebalance()])  

test = bt.Backtest(s , data, initial_capital=1000000.0) 
res = bt.run(test)
```

the error msg is : 

> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Can anyone help to tell me where the issue is?

**Comment by exted** [comment]
Try below:

bt.algos.RunOnDate(*date_list)

More in this: https://stackoverflow.com/questions/36901/what-does-double-star-asterisk-and-star-asterisk-do-for-parameters

Regards,
Eric

**Comment by davidhuang123** [comment]
Thanks for the help, Eric.!
It solves the problem:)
