### ISSUE TITLE
How to run a multi indicator strategy in bt?

### ISSUE THREAD

**Issue by fightthepower** [pmorissette/bt#183]
I want to run a multi indicator strategy. I want to long a stock when **stock price > sma** and also **RSI > 70** else short the stock if **stock price < sma** and **RSI <30** . I have tried this way

```
import bt
import numpy as np

# download data
data = bt.get('aapl', start='2018-01-01')

# calculate moving average DataFrame using pandas' rolling_mean
import pandas as pd
# a rolling mean is a moving average, right?
data['sma'] = data.rolling(50).mean()


import talib as ta

d=data['aapl'].values.reshape(len(data))
data['rsi']=(ta.RSI(d))

signal=(data['aapl']>data['sma']) & (data['rsi']>70)

s = bt.Strategy('multi', [bt.algos.SelectWhere(signal),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()])

# now we create the Backtest
t = bt.Backtest(s, data)

res = bt.run(t)
```

This doesn't work?

**Comment by davidhuang123** [comment]
Try below, I guess you need to feed the right format so that the library understand.

import bt
import numpy as np
import pandas as pd
import talib as ta
import copy #import copy function

# download data
data = bt.get('aapl', start='2018-01-01')

# calculate moving average DataFrame using pandas' rolling_mean
data['sma'] = data.rolling(50).mean()

d=data['aapl'].values.reshape(len(data))
data['rsi']=(ta.RSI(d))

data = data.fillna(0)
data['signal']=(data['aapl']>data['sma']) & (data['rsi']>70)

tw_data = copy.deepcopy(data) #make copy of data without association
#Assign fixed weight to column
tw_data['aapl']=data['signal']

#drop column Unused
data=data.drop(['sma','rsi','signal'], axis=1)
tw_data=tw_data.drop(['sma','rsi','signal'],axis=1)

s = bt.Strategy('multi', [bt.algos.SelectWhere(tw_data),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()])

# now we create the Backtest
t = bt.Backtest(s, data)

res = bt.run(t)

%matplotlib inline
res.plot()

**Comment by fightthepower** [comment]
@daviduang123
Sorry for the late reply and also thank you for the code. But can I ask one doubt. In the sample [SMA strategy](http://pmorissette.github.io/bt/examples.html#sma-strategy). The signal `signal = data > sma` gives true when price is greater than sma

```
2019-06-18   True
2019-06-19   True
2019-06-20   True
2019-06-21   True
2019-06-24   True
2019-06-25   True
2019-06-26   True
2019-06-27   True
2019-06-28   True
2019-07-01   True
2019-07-02   True
2019-07-03   True
2019-07-05   True
2019-07-08   True
2019-07-09   True
```
But in my case `data['signal']=(data['aapl']>data['sma']) & (data['rsi']>70)` signal will only be true when rsi is greater than 70 and when it decreases below 70 it becomes False. 

What I want is I should buy the aapl stock when rsi is 70 and sell it when it reach rsi 30 a long position. Then when rsi is below 30 go for short that is sell at rsi<30 and buy back this at 70

**Comment by davidhuang123** [comment]
It seems it’s easier to dissect your strategy into 2 strategies. You can
write 2 script for each and combine them to see the results .

**Comment by boyac** [comment]
@davidhuang123 , would you mind I'm asking a follow up question. I got a similar issue, but my indicator is the return of the stock over past 3 months, how can I do the calculation? Thanks

**Comment by davidhuang123** [comment]
Hello,Boya,

Maybe you can send the code to me so I can take a look?

thanks

**Comment by boyac** [comment]
Thanks @davidhuang123 I used a similar structure. but I’m not sure how to generate the returns of past 3 months for my portfolio vs. risk free rate as my signal. 

```
import 

Signal: where past 3 month portfolio return > ^tnx
# create the momentum strategy - we will specify the children (3rd argument)
# to limit the universe the strategy can choose from
mom_s = bt.Strategy('mom_s', [bt.algos.RunMonthly(),
                              bt.algos.SelectAll(),
                              bt.algos.SelectMomentum(1),
                              bt.algos.WeighEqually(),
                              bt.algos.Rebalance()],
                    ['spy', 'eem'])

# create the master strategy - this is the top-most node in the tree
# Once again, we are also specifying  the children. In this case, one of the
# children is a Security and the other is a Strategy.
master = bt.Strategy('master', [bt.algos.RunMonthly(),
                                bt.algos.SelectWhere(signal),
                                bt.algos.WeighEqually(),
                                bt.algos.Rebalance()],
                    [mom_s, ‘^tnx'])

# create the backtest and run it
t = bt.Backtest(master, data)
r = bt.run(t)
```

**Comment by davidhuang123** [comment]
Ok I will take a look , it might take sometime.

**Comment by boyac** [comment]
@davidhuang123 thanks a lot!
