### ISSUE TITLE
How can I export bt.backtest.Result to excel or .txt files?

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#184]
How can I export bt.backtest.Result to excel or .txt files?

**Comment by davidhuang123** [comment]
Probably Copy and Paste is the fastest way:)

**Comment by boyac** [comment]
well, this is one option, but not too ideal for > 100 exports daily..

**Comment by boyac** [comment]
well.. this is one option

**Comment by davidhuang123** [comment]
In that case ,maybe you can write some short script to do it. As far as I
know, this library  contains a lot of core backtesting functionality but
does not include this function:)

**Comment by boyac** [comment]
aha, I found the function available in ffn module; res.to_csv(sep=',',path=''), ticket solved

**Comment by boyac** [comment]
aha, I found the function available in ffn module; res.to_csv(sep=',',path=''), ticket solved

**Comment by boyac** [comment]
aha, I found the function available in ffn module; res.to_csv(sep=',',path=''), ticket solved
