### ISSUE TITLE
How can I calculate the total return with dividend reinvested?

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#185]
The total return of res.display(), seems to be price index return if not misunderstood (ticker used: S&P500). Does anyone have tried to calculate the total return with all dividends reinvested?

**Comment by gabrielfior** [comment]
Is there a solution for this problem? I could not find anything in the documentation. Thanks!

**Comment by boyac** [comment]
the ticket is closed, since actually the adj. the price on yahoo finance is
using dividend adjusted price.
Using dividend adjusted price to calculate return, it includes the dividend
reinvested.
