### ISSUE TITLE
Questions with bt.algos.TargetVol()

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#190]
Could someone help to explain more on the concepts for TargetVol()?
According to the modules (excerpt code below), it will adjust the stock weights to meet the target volatility? However, after applying the multiplier, the sum(target.temp['weights'] will > 1, is this correct for target volatility implementation? 
```python
vol = np.sqrt(np.matmul(weights.values.T,np.matmul(covar,weights.values))*self.annualization_factor)

        #vol is too high
        if vol > self.target_volatility:
            mult = self.target_volatility/vol
        #vol is too low, keep as it is
        else:
            mult = 1

        for k in target.temp['weights'].keys():
            target.temp['weights'][k] = target.temp['weights'][k]*mult

        return True
```

**Comment by JordanPlatts** [comment]
Yeah it is meant to mimic using leverage.
