### ISSUE TITLE
Why is the WeighERC() using RunAfterDays() instead of RunMonthly()?

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#191]
Why is the WeighERC() using RunAfterDays() instead of RunMonthly()? Will it cause any difference? Thanks

**Comment by FinQuest** [comment]
Some of Weigh() Algos require a minimal period of time series price data to calculate the Covariance or Volatility.  Depending on the Run() Algo used it may be necessary to call RunAfterDays() or RunAfterDate() first.
