### ISSUE TITLE
Including tax costs

### ISSUE THREAD

**Issue by gawry** [pmorissette/bt#200]
I know that this came up few times, but still not clear to me how could I be able to add tax costs into transaction costs.

As I understood, the commission function receives price and quantity of the assets traded. But to calculate tax, I would have to know how much profit is that transaction making.

For Brazil, we pay 15% on the profits you make. So I would need to know average cost of acquisition and the selling price. Can you see a way to calculate that?

**Comment by boyac** [comment]
@gawry the current solution I can think of right now, is to manipulate the res data. `res.prices * (1-0.15)`

**Comment by gawry** [comment]
I will take a look, but is the res data is available on a transaction basis? I mean, because the commission function runs every time there is a transaction event. If I have to calculate taxes at every transaction I will have to keep track of all transactions.

I think I will need to build an additional class to keep track of all transactions and then be able to calculate taxes.

**Comment by chkuehnel** [comment]
Hi @gawry did you solve your Problem? Have a similar one. I would need to add tax on every sell's profit. But currently I'm not sure where I should add that code.

**Comment by ptomecek** [comment]
With get_transactions now on the strategy, you can write an Algo subclass which calls target.get_transactions and uses that to compute taxes based on the executed transactions. It can then call target.adjust with flow=False to take the amount out of the strategy (in a way that will impact return). You can then run the algo annually, quarterly, etc to represent the frequency of tax payments (or withholding). By storing it on target['temp'], you could also have other algos change their behavior based on your current tax liabilities. Hope that helps.

**Comment by csc5a2g** [comment]
@ptomecek - For me this is a nice way of adding in daily stock borrow fees, however I have one question, currently going through small strategy that has 5K days of history it takes a really long time. Is there a way to speed this up ?
