### ISSUE TITLE
How to view daily return?

### ISSUE THREAD

**Issue by Kinzowa** [pmorissette/bt#201]
Hi, 

I'm looking at the `bt.backtest.Result` object and I find a lot's of information like quantity and price, weights and statistics but I can't find the return rate. How can I see that? 

Thank you

**Comment by boyac** [comment]
@Kinzowa, this could be easily done by doing a self-calculation 
```python 
daily = res.prices / res.prices.shift(1) - 1
```

**Comment by Kinzowa** [comment]
> ```python
> res.prices / res.prices.shift(1) - 1
> ```

Thanks!
