### ISSUE TITLE
bt plotting two strategy showing error

### ISSUE THREAD

**Issue by subinoy** [pmorissette/bt#202]
I was trying to plot two strategy together as shown in the example however, getting some error as below.
res3 = bt.run(test, test2)
AttributeError                            Traceback (most recent call last)
<ipython-input-47-192f5a18262a> in <module>
----> 1 res3 = bt.run(test, test2)
26     # run each backtest
     27     for bkt in backtests:
---> 28         bkt.run()
     29 
     30     return Result(*backtests)

AttributeError: 'function' object has no attribute 'run'

Please help me to sort out the problem

**Comment by boyac** [comment]
Hi @subinoy,
If you'd like to plot to strategy together, you can simply do by res3.plot() and don't need to run a loop.

**Comment by subinoy** [comment]
# create a backtest and run it
test = bt.Backtest(s, df_mcx_bt)
res = bt.run(test)                           # working good
# now let's test it with the same data set. We will also compare it with our first backtest.
test2 = bt.Backtest(s2, df_mcx_bt)
# we include test here to see the results side-by-side
res2 = bt.run(test2)             # working good
res3 = bt.run(test, test2)    # Not WORKING

# http://pmorissette.github.io/bt/

**Comment by subinoy** [comment]
![Screen_Shot_2020-01-20_at_12_18_01_PM](https://user-images.githubusercontent.com/3486473/72704783-b6ae8f00-3b7f-11ea-8315-fe09429ba109.jpg)

**Comment by boyac** [comment]
@subinoy exactly as stated res = bt.run(test2, test2)
