### ISSUE TITLE
Has anyone ever tried export target.temp data?

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#205]
Hi team,

Has anyone ever tried export target.temp data yet?
I'd like to export the weights and groupby asset classes to plot a pie chart.

Thanks

**Comment by boyac** [comment]
found a way to export from Backtest, thanks!

**Comment by posidonius** [comment]
> found a way to export from Backtest, thanks!

Can you explain how you did that? I want to export temp data to a csv file at the end of the backtest.
