### ISSUE TITLE
Incompatible with Pandas 1.0

### ISSUE THREAD

**Issue by jemanuel** [pmorissette/bt#207]
Error because 'ix' was deprecated:

site-packages\ffn\core.py", line 501, in display_monthly_returns
    r = self.return_table.ix[k].values
AttributeError: 'DataFrame' object has no attribute 'ix'

This can be fixed by changing display_monthly_returns as follows:

 def display_monthly_returns(self):
        """
        Display a table containing monthly returns and ytd returns
        for every year in range.
        """
        data = [['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May',
                 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'YTD']]
        for k in self.return_table.index:
            #r = self.return_table.ix[k].values   <----REPLACE THIS WITH LINE BELOW
            r = self.return_table.loc[k,:].values
            data.append([k] + [fmtpn(x) for x in r])
        print(tabulate(data, headers='firstrow'))

There may be other issues like this in the rest of the code, this is just what I've encountered so far. I will let you know if there are more problems.

**Comment by timkpaine** [comment]
#233
