### ISSUE TITLE
Rebalancing: start or end of period 

### ISSUE THREAD

**Issue by BenRollert** [pmorissette/bt#210]
I went through source code and could not find documentation about exactly when rebalancing occurs. That is, if I pass a signal matrix, do I need to lag the signal by a period to avoid leakage? Or does rebalancing occur after the close of the bar? In the Portfolio Analytics package in R, for example, the convention is to assume all weights are "end of period weights" so there is no need to lag a trading signal to avoid leakage.

**Comment by Deamoner** [comment]
I beleive rebalancing is part of the algo stacks. Which allocate Close out positions that are no longer needed and allocate capital to those that were selected and given target weights. This approach seems quite dangerous but It is assuming you are making more trades with all capital allocated.

**Comment by Deamoner** [comment]
```#setup the model and backtest it 
s = bt.Strategy('above50sma', [SelectWhere(data > sma),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()]) ```

```

**Comment by ClovisC86** [comment]
> I went through source code and could not find documentation about exactly when rebalancing occurs. That is, if I pass a signal matrix, do I need to lag the signal by a period to avoid leakage? Or does rebalancing occur after the close of the bar? In the Portfolio Analytics package in R, for example, the convention is to assume all weights are "end of period weights" so there is no need to lag a trading signal to avoid leakage.

On a rebalance date, your strategy's rebalance algo returns True and (if needed) updates the securities prices for that date, using the price data you've passed to your backtest objet. This is in the securityBase update method in the core module:

inow = self.data.index.get_loc(date)

The pandas get_loc method defaults to exactmatch method by the way, so it will return NaN if you're trying to rebalance on a day when there is no price data for your security. So there won't be any data leakage there. 

So as long as the timestamps of your price data is correct (not actually corresponding to a future date), then there will be no leakage. Note that if any of your securities is NaN or 0, the roll will fail.
