### ISSUE TITLE
BT Performance on large number of assets and strategies

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/bt#216]
Hi,

I'm having some issues with the speed of BT. I've got 116 sub strategies that trade across 625 assets. I've followed the "Tree Structure" example as the method for organisation of the strategies (All going into one mast strategy). All goes okay until the actual backtest run when I'm presented with an ETA of 3 hours + !!

Are there any performance tips that anyone can share to get the timing down to something more reasonable ?

A

**Comment by csc5a2g** [comment]
Scrub this. I figured out I was using the Tree structure incorrectly. No down to something I consider more appropriate for 116 sub strategies, approx 10 minutes. Not bad.

A

**Comment by BradKML** [comment]
Just out of curiosity, could you document the process and for mixing assets with dynamic strategies?
