### ISSUE TITLE
Target Volume attribute

### ISSUE THREAD

**Issue by praty98** [pmorissette/bt#220]
Trying to run your package which can be very useful for us.
Getting this error.

AttributeError: module 'bt.algos' has no attribute 'TargetVol'

![error](https://user-images.githubusercontent.com/64798075/83288466-06255b80-a201-11ea-93ed-af2c046b9036.jpg)

**Comment by boyac** [comment]
@praty98 for the TargetVol(), you could check if your current bt package algos.py has 'TargetVol', otherwise I'd update it by the latest version on github, FYI: https://github.com/pmorissette/bt/blob/master/bt/algos.py
hope this helps!
