### ISSUE TITLE
Adding print statements (or logs) in core module to debug 

### ISSUE THREAD

**Issue by ClovisC86** [pmorissette/bt#225]
Hi,
When I go to the source code and add print statements anywhere in the core module, these print statements are not executed (even after I re-import the bt backage). Is there something in the __init__.py module that prevents from editing the core module's source code? 

I want to add those print statements to debug an Exception error I am getting when I run the method securityBase.allocate(amount). It seems the while loop doesn't converge to the number of stocks I need to buy (net of transaction costs) in order to spend no more than the amount I passed to the method.
That seems odd because when I do the math the while loop actually converges so I'd like to add print statements within the allocate method.

**Comment by timkpaine** [comment]
`core.py` is cythonized, if you want to rebuild I recommend running the following:

`pip install -e .`

this will symlink into your `site-packages`.

then after making modifications to setup.py, you can rebuild in place

`python setup.py build_ext --inplace`

or just re-cythonize core.py

`python -c "from Cython.Build import cythonize; cythonize('bt/core.py')"`

**Comment by ClovisC86** [comment]
thanks @timkpaine that worked.
There were a couple of preliminary steps to follow, which may be helpful for anyone not used to Cython:

I downloaded the zipped bt package from the github repo and saved it as bt-master in my site-packages.
From within this bt-master folder, I then ran pip install in editable mode (as you recommended):
`pip install -e .` 
Then I modified the core.py file and ran (from within bt-master again):
`python setup.py build_ext --inplace`

Thanks for your help
