### ISSUE TITLE
bt install fails in fresh Anaconda environment (python3.7) on Win 10

### ISSUE THREAD

**Issue by EcoFin** [pmorissette/bt#227]
This is odd, because I had installed it successfully before in Anaconda on this machine.  But after a fresh Anaconda install, ffn is fine but not bt.  Here is what it tells me:

failed to build bt

    ERROR: Command errored out with exit status 1:
     command: 'E:\Anaconda3\envs\finance\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajryounger\\AppData\\Local\\Temp\\pip-install-p1ipp9lw\\bt\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajryounger\\AppData\\Local\\Temp\\pip-install-p1ipp9lw\\bt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajryounger\AppData\Local\Temp\pip-record-048hfjfz\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Anaconda3\envs\finance\Include\bt'
         cwd: C:\Users\ajryounger\AppData\Local\Temp\pip-install-p1ipp9lw\bt\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\bt
    copying bt\algos.py -> build\lib.win-amd64-3.7\bt
    copying bt\backtest.py -> build\lib.win-amd64-3.7\bt
    copying bt\core.py -> build\lib.win-amd64-3.7\bt
    copying bt\__init__.py -> build\lib.win-amd64-3.7\bt
    running build_ext
    building 'bt.core' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\Anaconda3\envs\finance\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajryounger\\AppData\\Local\\Temp\\pip-install-p1ipp9lw\\bt\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajryounger\\AppData\\Local\\Temp\\pip-install-p1ipp9lw\\bt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajryounger\AppData\Local\Temp\pip-record-048hfjfz\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Anaconda3\envs\finance\Include\bt' Check the logs for full command output.

I am not sure that I **really ** need to install an obsolete MS VC++!  I have every one from  the 2008 to the 2015-19 versions but not 2014 for whatever reasons.

It's not fatal, because what I really use is ffn, but I though I would let you know.  I really do appreciate both libraries and have had students in my financial theory course use bt in the past.

sincerely
a. younger

**Comment by timkpaine** [comment]
You either need a functional VC compiler, and/or have Cython installed (which will itself require a compiler). 

Note that the compiler version required will be dictated by your python installation, not by this package. check `sys.version`, if you installed a pre-built python rather than building from source, its not guaranteed you have the required compilers (you may only have the runtime dependencies).

**Comment by EcoFin** [comment]
I don't think that solves the mystery .  I'm running a fully up to date Anaconda python 3.7 install that includes  both cython  and mingw in  the conda environment in which I installed bt.  Also, bt ran fine before with python 3.4.  So I'm still puzzled.

**Comment by timkpaine** [comment]
The error is clear and unrelated to bt. Mingw won't do anything if your python was built with vc14

**Comment by EcoFin** [comment]
Does that mean that bt does not work with python 3.7 which is compiled using vc14?
If so, why not just say that bt is not compatible with python past ver 3.4?
That would be too bad.

**Comment by timkpaine** [comment]
It's completely compatible, there are no `bt` issues in this thread. You have issues in your environment which cause you to be unable to compile python extensions or use cythonize, if you fix those then any libraries that use this (including bt) will be install.

**Comment by WMQuant** [comment]
Hi, I have the same kind of issue using Anaconda 2019.03 with python 3.7 in Win 10. When trying to install the package it ask for the V C++ 14.0. However, I am running both MS 2015 Visual C++ 14.0.23026, MS V C++ 2017 14.12.25810 and 2019 14.26.28720. All other libraries I have works fine.

Only using this method python is able to import the package: https://github.com/pmorissette/bt/issues/120 ... any chance to have bt installed properly as well?  What else to check?

**Comment by timpaine-iex** [comment]
https://cython.readthedocs.io/en/latest/src/quickstart/install.html
```
Unlike most Python software, Cython requires a C compiler to be present on the system. The details of getting a C compiler varies according to the system used:
```

**Comment by timkpaine** [comment]
https://cython.readthedocs.io/en/latest/src/quickstart/install.html
```
Unlike most Python software, Cython requires a C compiler to be present on the system. The details of getting a C compiler varies according to the system used:
```

**Comment by timkpaine** [comment]
> Note that the compiler version required will be dictated by your python installation, not by this package

**Comment by timkpaine** [comment]
First google result...
https://github.com/benfred/implicit/issues/76

**Comment by timkpaine** [comment]
Again, this has *nothing* to do with this library
