### ISSUE TITLE
Newton Method like root search for quantity is stuck! Consider changing to warning

### ISSUE THREAD

**Issue by Kinzowa** [pmorissette/bt#228]
Hello, I've been playing for a while with the `bt` library and recently I noticed a new error reproductible with a specific set of prices data serie. Everything looks fine in the data: the frequency is right, there is no #NA or Null value. 

What do you think it could be? and how could I investigate it more?
Also my question is in regards to the `Consider changing to warning`, is it something I can do?

Thank you,
K.

 ```
 File "bt/core.py", line 1310, in bt.core.Strategy.run
  File "bt/core.py", line 1253, in bt.core.AlgoStack.__call__
  File "/home/abc/python/envdev/lib/python3.6/site-packages/bt/algos.py", line 1314, in __call__
    target.rebalance(item[1], child=item[0], base=base)
  File "bt/core.py", line 722, in bt.core.StrategyBase.rebalance
  File "bt/core.py", line 668, in bt.core.StrategyBase.allocate
  File "bt/core.py", line 1116, in bt.core.SecurityBase.allocate
Exception: Newton Method like root search for quantity is stuck! q did not change in iterations so it is probably a bug but we are not entirely sure it is wrong! Consider  changing to warning.
```

**Comment by JordanPlatts** [comment]
The best way to debug it is to run it in pycharm and set a break point at the exception.

**Comment by Kinzowa** [comment]
> The best way to debug it is to run it in pycharm and set a break point at the exception.

Hi Jordan, thanks for the great work and for the suggestion! finnaly I found it's related to this issue and I sorted out by turning the parameter `integer_position` to Flase.
https://github.com/pmorissette/bt/issues/97

**Comment by ClovisC86** [comment]
Hi @JordanPlatts ,
I've had similar issues on transaction cost calculations. Is there anything specific to be aware of when editing the core module? 
I have made my edits to the bt.core.SecurityBase.allocate method (either to change the exception to a simple warning, or to add a break point) but my edits are not reflected when I run the backtest.
I have tried to force a reload of the bt library using importlib.reload(bt) but that does not help either.
I did check that I am running bt and making the core.py edits in the same environment.

python 3.8
spyder 4.1.3
windows 10
bt 0.2.7

Thanks a lot

**Comment by x829901** [comment]
Hi, I ran into the following error when trying to run backtests. Could anyone shed some light on what this error means and what I should do about it? 

"Exception: Newton Method like root search for quantity is stuck! q did not change in iterations so it is probably a bug but we are not entirely sure it is wrong! Consider  changing to warning." 

I have been trying to troubleshoot this. My prices and weights appear to be fine. The error disappears if I use different tickers in my portfolios. Something about these particular ticker's prices is throwing this error. 

![image](https://user-images.githubusercontent.com/57601600/140679415-0a298bc3-0c58-43d6-9be7-5d5a4c4c2a4e.png)
