### ISSUE TITLE
Total return -7617.81% when using bt.algos.WeighTarget

### ISSUE THREAD

**Issue by croessert** [pmorissette/bt#230]
I have been using this strategy with external weights w:

`s = bt.Strategy('s1', [bt.algos.WeighTarget(w), bt.algos.Rebalance()])`

This leads to huge negative return of -7617.81% when using on a portfolio of 50 securities.
w is unbounded positive and negative expected next day return for each security.

Is this a bug or did I not properly scale/normalize the weights w?

**Comment by boyac** [comment]
@croessert w should be the weights assigned to the portfolio (50 securities).

**Comment by croessert** [comment]
@boyac yes, but what requirements are there to w? [0,1] or [-1,1] or [-inf, inf] ,.... ??

**Comment by boyac** [comment]
@croessert if you mean range, sum of w should be 1 if no leverage.
