### ISSUE TITLE
Installing BT on Pypy

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/bt#232]
Hi - I'm using BT to test intraday strategies based off of Minbars. I'm finding that trying to test 2 years of minbar data is very laborious (it can take 5 hours to run a simple test). So I'm interested in seeing if using Pypy will speed BT up, however I'can't seem to get it installed in Pypy.

Has anyone managed to get BT working within Pypy ? and if so how did you do it ?

Thanks
Anthony

**Comment by timkpaine** [comment]
closing as out of scope for this repo right now
