### ISSUE TITLE
Cant install pip or easy_install

### ISSUE THREAD

**Issue by wlblount** [pmorissette/bt#237]
Building wheel for bt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\eg_user\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-jccns7o1\\bt\\setup.py'"'"'; __file__='"'"'C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-jccns7o1\\bt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\EG_User\AppData\Local\Temp\pip-wheel-28s25mu9'
       cwd: C:\Users\EG_User\AppData\Local\Temp\pip-install-jccns7o1\bt\
  Complete output (19 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\bt
  copying bt\algos.py -> build\lib.win-amd64-3.7\bt
  copying bt\backtest.py -> build\lib.win-amd64-3.7\bt
  copying bt\core.py -> build\lib.win-amd64-3.7\bt
  copying bt\__init__.py -> build\lib.win-amd64-3.7\bt
  running build_ext
  building 'bt.core' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\bt
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\eg_user\anaconda3\include -Ic:\users\eg_user\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcbt/core.c /Fobuild\temp.win-amd64-3.7\Release\bt/core.obj
  core.c
  c:\users\eg_user\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for bt
  Running setup.py clean for bt
Failed to build bt
Installing collected packages: bt
    Running setup.py install for bt ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\eg_user\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-jccns7o1\\bt\\setup.py'"'"'; __file__='"'"'C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-jccns7o1\\bt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\EG_User\AppData\Local\Temp\pip-record-b93_2xlh\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\eg_user\anaconda3\Include\bt'
         cwd: C:\Users\EG_User\AppData\Local\Temp\pip-install-jccns7o1\bt\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\bt
    copying bt\algos.py -> build\lib.win-amd64-3.7\bt
    copying bt\backtest.py -> build\lib.win-amd64-3.7\bt
    copying bt\core.py -> build\lib.win-amd64-3.7\bt
    copying bt\__init__.py -> build\lib.win-amd64-3.7\bt
    running build_ext
    building 'bt.core' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\bt
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\eg_user\anaconda3\include -Ic:\users\eg_user\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcbt/core.c /Fobuild\temp.win-amd64-3.7\Release\bt/core.obj
    core.c
    c:\users\eg_user\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\eg_user\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-jccns7o1\\bt\\setup.py'"'"'; __file__='"'"'C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-jccns7o1\\bt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\EG_User\AppData\Local\Temp\pip-record-b93_2xlh\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\eg_user\anaconda3\Include\bt' Check the logs for full command output.

**Comment by pearsedoolin** [comment]
I also had troubles pip installing when I was using python 3.9. What version are you using?

**Comment by boyac** [comment]
@pearsedoolin I'm using python 2.7 and 3.5, both works fine.

**Comment by ClovisC86** [comment]
You need to install a Microsoft Visual C++ build tool before installing bt (as bt uses cython).
Make sure the build tool you download is compatible with your python version (@pearsedoolin , I don't think there is a build tool compatible with Python 3.9 yet. Check [here)](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F)
Download the build tool from [here](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019). Click Download under the section "Build tools for visual studio 2019".
