### ISSUE TITLE
trouble making plots

### ISSUE THREAD

**Issue by diegodalvarez** [pmorissette/bt#244]
Hi I just started using bt and I was copying the code from the from page ([here](https://pmorissette.github.io/bt/index.html#what-is-bt)) And I am running matplotlib version 3.2.1 and when I use the .plot() on the backtest.Result object it doesn't give me a plot. When I use the .plot_histogram() that gives an error saying that the 'Rectangle' object has no property 'normed'

**Comment by boyac** [comment]
@diegodalvarez I am using matplotlib 2.2.4, and the plot works just fine, FYI.

**Comment by geofffoster** [comment]
https://github.com/pandas-dev/pandas/issues/24881

in core.py  - line 559 needs to be changed to

        ax = ser.hist(bins=bins, figsize=figsize, density=True, **kwargs)

**Comment by timkpaine** [comment]
please see the version constraints on `setup.py`.
