### ISSUE TITLE
allocate method: "Consider changing exception to warning" 

### ISSUE THREAD

**Issue by ClovisC86** [pmorissette/bt#246]
Hi @JordanPlatts ,
(reposting in new issue for the sake of keeping things separate)
As originally discussed by @Kinzowa, I've had similar issues on transaction cost calculations. Is there anything specific to be aware of to be able to edit the core module? 
I have made my edits to the bt.core.SecurityBase.allocate method (either to change the exception to a simple warning, or to add a break point) but my edits are not reflected when I run the backtest.
I have tried to force a reload of the bt library using importlib.reload(bt) but that does not help either.
I did check that I am running bt and making the core.py edits in the same environment.

python 3.8
spyder 4.1.3
windows 10
bt 0.2.7

Thanks a lot

_Originally posted by @ClovisC86 in https://github.com/pmorissette/bt/issues/228#issuecomment-724828346_

**Comment by ptomecek** [comment]
Because the core file is compiled with cython, if you want to make changes to it, you need to re-compile it. This works for me:
python setup.py clean --all
python setup.py build_ext --inplace

**Comment by ClovisC86** [comment]
hi @ptomecek 
which setup.py file are you referring to?

**Comment by ClovisC86** [comment]
I found out I didn't have a setup.py file because I hadn't pip installed bt in editable mode.
I had to first pip uninstall bt, save a local copy from github and then run pip install in editable mode from within that local folder:
`pip install -e .`
