### ISSUE TITLE
Strategy re-usability when Algos take explicit data

### ISSUE THREAD

**Issue by ptomecek** [pmorissette/bt#248]
Following the pattern in SelectWhere and WeighTarget, I recently added a number of other algos that are constructed with explicit data frames that are related to the specific instrument universe and timelines from the backtest (i.e. ClosePositionsAfterDates, RollPositionsAfterDates, UpdateRisk, ReplayTransactions, SimulateRFQTransactions).

As I was describing to people one of the design advantages of bt, namely that it de-couples that strategy logic from the data and the engine, which encourages modularity and re-use of the strategies, I realize that Algos which take in explicit data re-introduce this coupling. In other words, one can't use exactly the same strategy object on targets with arbitrary security universes/time horizons.

However, I believe there is a relatively elegant solution. Another change I made to support bid/offer spread accounting and coupon-paying instruments was to introduce the "additional_data" argument during backtest construction, which is passed to **kwargs on the setup call on the strategies.  So, one way to maintain decoupling for the algos listed above is to pass the data they depend on through this additional_data argument, which would then already be passed to the underlying strategies for storage. By adding a public interface to this data on the strategy, the algos could then access the data they needed from any target that was set up properly.

For example, instead of passing the backtest-specific signal data frame to SelectWhere, one could pass the string "where", and in creation of the backtest, the additional_data dictionary could have a "where" key which contained the signal data frame. That way, the strategy logic could be re-used as-is across multiple different backtests, as long as they were each instantiated with an appropriate "where" argument. 

To maintain backwards compatibility, we could support the argument being either a data frame or a string key to look up the data frame from the target. 

I am happy to make and test the changes, but feedback is appreciated before I do so (@JordanPlatts @timkpaine ).

**Comment by timkpaine** [comment]
Sounds fine to me

**Comment by ptomecek** [comment]
This is now supported on (almost) all algos, in a backwards-compatible way for existing ones, and as the only way for some of the newer ones. It is not supported on CapitalFlow, because it wasn't clear that it was necessary as the algo takes a float rather than a data frame as the argument. 
Note that even though the legacy algos are backwards compatible, it is always preferable to use the decoupled way of specifying data because it allows the same strategy to apply to a different basket of securities.
