### ISSUE TITLE
Performance attribution per security

### ISSUE THREAD

**Issue by aldeni** [pmorissette/bt#251]
Hi guys,

I'm looking for if there's some way to breakdown the performance per security related to a strategy that will allocate in some stocks over the time. Is this some function or procedure regarding this?

Many tks!!!

**Comment by ptomecek** [comment]
Yes, it's all saved on the strategy and it's children, i.e. if you have a backtest object "b", you have access to b.strategy.children[ security_name ].values where "security_name" is the name of the security whose performance you are interested in.
