### ISSUE TITLE
fixed_income.ipynb

### ISSUE THREAD

**Issue by geofffoster** [pmorissette/bt#252]
I when running fixed_income.ipynb I get the following error when generating the the synthetic data. I'm using pandas 1.1.0

ValueError                                Traceback (most recent call last)
~/anaconda3/envs/backtrader/lib/python3.8/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    543                 try:
--> 544                     arr = np.array(data, dtype=dtype, copy=copy)
    545                 except (ValueError, TypeError) as err:

ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-9-5f6b642c7477> in <module>
     32 govt_yield.loc[:,:] = govt_yield_ts
     33 
---> 34 govt_mat = pd.DataFrame( columns = govt_data.index, index=timeline, data=pd.NaT )
     35 govt_mat.loc[:,:] = govt_data['mat_date'].values.T
     36 govt_ttm = (govt_mat - timeline.values.reshape(-1,1))/pd.Timedelta('1Y')

~/anaconda3/envs/backtrader/lib/python3.8/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    548                         f"incompatible data and dtype: {err}"
    549                     )
--> 550                     raise exc from err
    551 
    552                 if arr.ndim != 0:

TypeError: DataFrame constructor called with incompatible data and dtype: cannot convert float NaN to integer

**Comment by timkpaine** [comment]
@geofffoster can you see if it works with "pandas<1", probably a pandas issues

**Comment by geofffoster** [comment]
thanks - works now.
