### ISSUE TITLE
does Backtest's data argument only accept pandas DataFrame data with adjusted closing price?

### ISSUE THREAD

**Issue by blenderben2** [pmorissette/bt#253]
Hi, does `bt.Backtest`'s `data` argument only accept pandas DataFrame data with adjusted closing price (one feature)? What if I want to include volume data in my pandas DataFrame? 

For example I might have a algo that takes into account the volume data in addition to the price data.

**Comment by aldeni** [comment]
Hello, I'm not expert using bt but as per your request I think that you should build your trading signal before then use it as a trigger to open/close position.

As exposed in the website the following example build the trading signals then use it as a 'target weight' into bt.

`
# first let's create a helper function to create a ma cross backtest
def ma_cross(ticker, start='2010-01-01',
             short_ma=50, long_ma=200, name='ma_cross'):
    # these are all the same steps as above
    data = bt.get(ticker, start=start)
    short_sma = data.rolling(short_ma).mean()
    long_sma  = data.rolling(long_ma).mean()

    **# target weights
    tw = long_sma.copy()
    tw[short_sma > long_sma] = 1.0
    tw[short_sma <= long_sma] = -1.0
    tw[long_sma.isnull()] = 0.0**

    # here we specify the children (3rd) arguemnt to make sure the strategy
    # has the proper universe. This is necessary in strategies of strategies
    s = bt.Strategy(name, [WeighTarget(tw), bt.algos.Rebalance()], [ticker])

    return bt.Backtest(s, data)
`

**Comment by blenderben2** [comment]
thanks for the input, but I have decided to just assume all `Backtest`/`Algo` related defaults to data being close price only. Hence if I have a custom Algo I would follow the [SMA Strategy](http://pmorissette.github.io/bt/examples.html) example approach where I preprocess a separate data dataframe with volume inside.
