### ISSUE TITLE
Is there a way to trade in lots?

### ISSUE THREAD

**Issue by turmeric-blend** [pmorissette/bt#264]
is there a way to trade in lots? for example a minimum of 1 lot = 100 shares/units

**Comment by ptomecek** [comment]
I believe that is what the "multiplier" argument is for when you create a Security. i.e. pass in multiplier=100 and then whenever you trade a quantity of 1, it will trade 100 underlying shares.  When you combine this with the setting integer_positions=True, you will then only trade whole lots when rebalancing.

**Comment by turmeric-blend** [comment]
how do you use the `Security` in `bt`? I can't find a clear example on it

**Comment by ptomecek** [comment]
When you instantiate a Strategy, use the "children" argument, and pass it a list of bt.Security objects, which you have created with names matching the columns of the data frame you have, and a multiplier argument of 100. Unfortunately I can't find a good example of this in the repo except in fixed_income.ipynb which is also doing a lot of other complicated stuff.
