### ISSUE TITLE
Import Error with matplotlib >=3.3

### ISSUE THREAD

**Issue by s4bhatna** [pmorissette/bt#265]
There is an import error with bt when using it with matplotlib version 3.3.

This is due to use argument being deprecated. (See warning below)

`MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.`

Work around:
Install Matplotlib 3.2
`pip install matplotlib==3.2`

Hopefully this fix helps for the time being before the issue is resolved

**Comment by timkpaine** [comment]
This is a resolved on master of ffn already.
