### ISSUE TITLE
Failed building wheel for bt issue

### ISSUE THREAD

**Issue by bruno-albuquerque-solcap** [pmorissette/bt#272]
Hi, i'm having a issue with to install bt on jupyter notebook. On Google Colab i'm installing without any problem at all. I found the same issue in this session 2 years ago, i did the same steps, but the error persists.

![image](https://user-images.githubusercontent.com/73185969/106322094-0ffdd380-6254-11eb-80f4-5e57986e76b2.png)

**Comment by anusar80** [comment]
Did you figure out the solution? Trying to install bt on my remote instance. Keep running into the same error.
<img width="692" alt="Screen Shot 2022-04-23 at 8 31 46 PM" src="https://user-images.githubusercontent.com/45157990/164950663-f46d3468-d86d-458c-9e08-8f3f731b3889.png">

**Comment by timkpaine** [comment]
@anusar80 you're using conda so I would use the conda build of `bt`. https://github.com/conda-forge/bt-feedstock

**Comment by anusar80** [comment]
<img width="657" alt="Screen Shot 2022-04-23 at 8 43 37 PM" src="https://user-images.githubusercontent.com/45157990/164950880-65997b27-6e42-441b-99c2-52d91479e0a4.png">

followed the instructions on that page. Still not working. :(

**Comment by timkpaine** [comment]
there's no aarch64 build. if you want that you'll need to install from source with working compilers

**Comment by anusar80** [comment]
<img width="589" alt="Screen Shot 2022-04-23 at 8 57 47 PM" src="https://user-images.githubusercontent.com/45157990/164951144-d5105c22-07ad-422f-acfb-ff36f571435f.png">

Cloned it and tried to install it directly. More errors. Maybe I am missing something obvious?

**Comment by timkpaine** [comment]
clone and build this one, not the feedstock. and make sure you've installed a working gcc first

**Comment by anusar80** [comment]
Thanks. Let me try that.

**Comment by anusar80** [comment]
<img width="702" alt="Screen Shot 2022-04-23 at 9 17 59 PM" src="https://user-images.githubusercontent.com/45157990/164951565-dd0a0fab-1bdf-4dd4-b7e7-bc357bf4085d.png">
Says gcc is installed. But when I try to install, it shows up the same error.

**Comment by timkpaine** [comment]
Thats not a valid gcc command, idk why its generating bad compiler commands but its nothing to do with bt.

**Comment by timkpaine** [comment]
https://github.com/mrjbq7/ta-lib/issues/514
