### ISSUE TITLE
Graph issue 

### ISSUE THREAD

**Issue by Jacques2101** [pmorissette/bt#280]
Hi I tried to run the simple example from the doc: 
```
import bt
import pandas as pd

# fetch some data
data = bt.get('spy,agg', start='2010-01-01')
print(data.tail())

s = bt.Strategy('s1', [bt.algos.RunMonthly(),
                       bt.algos.SelectAll(),
                       bt.algos.WeighEqually(),
                       bt.algos.Rebalance()])

# create a backtest and run it
test = bt.Backtest(s, data)
res = bt.run(test)

# first let's see an equity curve
res.plot()
```

But no graph appears as indicated in the manual. I just get: 
```
<AxesSubplot:title={'center':'Equity Progression'}>
```

Then with 
```
res.plot_histogram()
```

I get an error message: 
```
AttributeError: 'Rectangle' object has no property 'normed'
````

and with: 
```
res.plot_security_weights()
```
Nothing happens. 

Any suggestion ?
Thx.

**Comment by timkpaine** [comment]
Since matplotlib is used, you may need to show the plot based on the context. So `plt.show()` from a tty or a program, `%matplotlib inline` from jupyter, etc.

As for the error, you likely have an incompatible version of matplotlib. Please post your versions of matplotlib/ffn/bt and we can double check.

**Comment by Jacques2101** [comment]
With `%matplotlib inline` it works but still an error message with `res.plot_histogram()` ie: 
`AttributeError: 'Rectangle' object has no property 'normed'` but with the graph displayed (strange !) 

Matplolib version: 3.3.2  
ffn version: 0.3.5 
bt version: 0.2.8

**Comment by timkpaine** [comment]
looks like the `normed` argument was deprecated as of at least 3.1 and removed in [3.3](https://github.com/matplotlib/matplotlib/blob/ba1e0633f3e5763dcf5ce5bbcc47af60831886c6/doc/users/prev_whats_new/github_stats_3.3.0.rst). Try downgrading to < 3.3.

**Comment by Jacques2101** [comment]
I downgraded to 3.1 and now have a warning message but works properly: 
```
/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/site-packages/pandas/plotting/_matplotlib/hist.py:338: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  ax.hist(values, bins=bins, **kwds)
```

Any idea when it will be updated to 3.3 Matplotlib version ? 
thx.

**Comment by timkpaine** [comment]
Thanks for confirming, I'll take a look later today

**Comment by venatiodecorus** [comment]
i'm also seeing this issue. could be worth mentioning `%matplotlib inline` in the docs somewhere for us python noobs :)

**Comment by geofffoster** [comment]
normed : bool, optional
    Deprecated; use the density keyword argument instead

ffn/core.py

        ax = ser.hist(bins=bins, figsize=figsize, **density**=True, **kwargs)

**Comment by timkpaine** [comment]
this was fixed a while ago
![Screen Shot 2021-05-15 at 14 26 47](https://user-images.githubusercontent.com/3105306/118374345-96cb8780-b589-11eb-9580-3b05fe5c1856.png)

**Comment by timkpaine** [comment]
https://github.com/pmorissette/ffn/blob/0575a43cdfd4d66eb3d8cc638f45d9595e889022/ffn/core.py#L693
