### ISSUE TITLE
res = bt.run(t) - error: 'Series' objects are mutable, thus they cannot be hashed

### ISSUE THREAD

**Issue by GS-LATAM** [pmorissette/bt#282]
Hello;

At first, Kudos for this must have script. It does what it promises for saving time.

Then, I'm pretty sure it's something stupid by my side, but I couldn't figure it out for God sake.

I have 10y data for closure such as: 

df_test.head()
	FECHAMENTO	day
DATA		
2021-01-04	2891.0	0
2021-01-05	3004.0	1
2021-01-06	3007.0	2
2021-01-07	3100.0	3
2021-01-08	3112.0	4

I'm testing a strategy to act at days named 4. So...

s = bt.Strategy('weekday', [bt.algos.SelectWhere(df_test.day == 4), 
                            bt.algos.WeighEqually(), 
                            bt.algos.Rebalance(),
                            bt.algos.RunWeekly()])

t = bt.Backtest(s, df_test)

So far so good.

But when I try to run....

res = bt.run(t)

I got:

TypeError                                 Traceback (most recent call last)
<ipython-input-126-4e30dca4e5a4> in <module>
      1 # and let's run it!
----> 2 res = bt.run(t)

C:\conda\lib\site-packages\bt\backtest.py in run(*backtests)
     26     # run each backtest
     27     for bkt in backtests:
---> 28         bkt.run()
     29 
     30     return Result(*backtests)

C:\conda\lib\site-packages\bt\backtest.py in run(self)
    224 
    225             if not self.strategy.bankrupt:
--> 226                 self.strategy.run()
    227                 # need update after to save weights, values and such
    228                 self.strategy.update(dt)

C:\conda\lib\site-packages\bt\core.cp37-win_amd64.pyd in bt.core.Strategy.run()

C:\conda\lib\site-packages\bt\core.cp37-win_amd64.pyd in bt.core.AlgoStack.__call__()

C:\conda\lib\site-packages\bt\algos.py in __call__(self, target)
    741             signal = self.signal
    742         else:
--> 743             signal = target.get_data( self.signal_name )
    744 
    745         if target.now in signal.index:

C:\conda\lib\site-packages\bt\core.cp37-win_amd64.pyd in bt.core.StrategyBase.get_data()

C:\conda\lib\site-packages\pandas\core\generic.py in __hash__(self)
   1884         raise TypeError(
   1885             "{0!r} objects are mutable, thus they cannot be"
-> 1886             " hashed".format(self.__class__.__name__)
   1887         )
   1888 

TypeError: 'Series' objects are mutable, thus they cannot be hashed

FYI, the following code works for me: 

data = bt.get('aapl,msft,c,gs,ge', start = '2010-01-01')
sma = data.rolling(50).mean()
s = bt.Strategy('above50sma', [bt.algos.SelectWhere(data > sma),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()])
t = bt.Backtest(s, data)
res = bt.run(t)

please tell me what I'm doing wrong! thank you!

**Comment by samuel-poon** [comment]
`SelectWhere` sets the securities for `temp['selected']`, but is not designed to run the Strategy on specific dates. The best way to do this would probably be to write your own Algo.

Try something like this:

```
class RunOnDay(bt.core.Algo):
    def __init__(self, run_day):
        super(RunOnDay, self).__init__()
        self.run_day = run_day

    def __call__(self, target):
        if target.now is None:
            return False
        
        if target.now.day == self.run_day:
            return True
        return False
```

Then if you want the Strategy to only run on the 4th of each month, start the AlgoStack with `RunOnDay(4)`.

**Comment by GS-LATAM** [comment]
tks!! will try it!
