### ISSUE TITLE
Best practice of using additional daily data (e.g. volumes)?

### ISSUE THREAD

**Issue by changlan** [pmorissette/bt#283]
Hi, I'm looking to use daily volume data for a custom `Algo`, but couldn't find any documents or examples for this. So I was wondering -- are there any best practices of incorporating daily data other than closing price into the strategy? I assume this would be a common use case. Thanks!

**Comment by kgonia** [comment]
@changlan 
I don't know what is best practice but I can tell you how to do it: pass different dataframe to algos (with all additional data that you need) and other to strategy (only with close prices). Algos must return only list on assets, it doesn't matter what data you are using - one requirement is that list from algos match with assets in datafreame with close prices.
