### ISSUE TITLE
Results Dataframe Confusion. 

### ISSUE THREAD

**Issue by Cyrusb01** [pmorissette/bt#287]
I love the package, really enjoying learning a new backtesting framework, just having some issues with utilizing the results. I want to be able to graph the returns, have access to the stats, and all the other bt.results framework functions, but I need them in a pandas dataframe. I am creating a streamlit app, so I am not able to just call the plot function on my `res`, but rather I need the results in a pandas dataframe so that I can feed streamlit the data to plot. I would also like the to display the stats with `res.display()`, but just grabbing that dataframe to give to steramlit. I have not been able to find a way to solve this without using the to.csv, which will not work for my streamlit app, I appreciate any help on how to get the results into a pandas dataframe. Thank you.

**Comment by samuel-poon** [comment]
`res.stats` should give you the same statistics as `res.display()` in a DataFrame.
