### ISSUE TITLE
How to start comparing backtested runs later than the start of the associated data

### ISSUE THREAD

**Issue by notpublius** [pmorissette/bt#288]
Just stumbled across this package and started using it--loving it so far.

I'm curious if there is an easy or standard way to change the starting date of the backtesting performace comparison, without changing the starting period of the time series data.

My use case is when you have an algo that requires a certain period of history (for example 12 mos of returns) to make its decisions. So, I want to feed in extra data prior to the period of comparison to "prime" the algo.

Hopefully that makes sense... if not read on...

Specifically, I am trying to replicate and investigate Antonacci's [ Dual Momentum](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2042750) strategy. I'm starting by comparing against the results presented [on this site](https://robotwealth.com/dual-momentum-review/)

Here is the crux of my code:
```python
start = '2007-01-01'
stop = '2017-02-01'
data = bt.get('spy,cwi', start=start, end=stop)

ref1 = bt.Strategy('spy', [bt.algos.RunOnce(),
                           bt.algos.SelectAll(),
                           bt.algos.SelectRegex(r'spy'),
                           bt.algos.WeighEqually(),
                           bt.algos.Rebalance()])

ref2 = bt.Strategy('cwi', [bt.algos.RunOnce(),
                           bt.algos.SelectAll(),
                           bt.algos.SelectRegex(r'cwi'),
                           bt.algos.WeighEqually(),
                           bt.algos.Rebalance()])

ref1bt = bt.Backtest(ref1, data)
ref2bt = bt.Backtest(ref2, data)

class SelectPositive(bt.algos.Algo):
    def __call__(self, target):
        stat = target.temp["stat"].dropna()
        sel = list(stat[stat>0].index)
        target.temp["selected"] = sel
        return True


dualmo = bt.Strategy('dual', [bt.algos.RunMonthly(),
                              bt.algos.SelectAll(),
                              bt.algos.AlgoStack(
                                  bt.algos.StatTotalReturn(lookback=pd.DateOffset(months=12), lag=pd.DateOffset(0)),
                                  SelectPositive(),
                                  bt.algos.SelectN(1, sort_descending=True, all_or_none=False, filter_selected=True)
                              ),
                              bt.algos.WeighEqually(),
                              bt.algos.Rebalance()])

mom2bt = bt.Backtest(dualmo, data)

res = bt.run(ref1bt, ref2bt, mom2bt)
res.plot()
```

And the results so far:

![image](https://user-images.githubusercontent.com/12476181/110216589-ebfa6700-7e7d-11eb-86a8-07041ef05626.png)

So the problem at hand is that the algo will flat line for a year, waiting for the total return stat to have meaningful data. Ideally, I'd provide an extra 12 months of prior data to the algos, but not start comparing the performance of the backtested runs until a year into the run.

Thoughts on how best to do this?

**Comment by kgonia** [comment]
Did you try with RunAfterDays, RunAfterDate algos?
