### ISSUE TITLE
Tried the example but plot is not working

### ISSUE THREAD

**Issue by sirokinl** [pmorissette/bt#292]
I tried the simple SMA example from the website but the plot is not showing.

Using Spyder IDE and Python 3.8.1

plot = bt.merge(data, sma).plot(figsize=(15, 5))

I don't get any errors either.

**Comment by timkpaine** [comment]
Please consult the matplotlib 101 docs for more info https://matplotlib.org/stable/tutorials/introductory/usage.html#non-interactive-example
