### ISSUE TITLE
Clarity on commissions for bt.backtest

### ISSUE THREAD

**Issue by GlobalBritain** [pmorissette/bt#304]
Firstly, I have to say a big thanks for this backtester. have been looking for a relatively simple backtesting program and this so far is the closest to that. I started using this package this weekend and am picking up a few things. Though I have an issue from the below:

Following on from [this ](https://github.com/pmorissette/bt/issues/36#issuecomment-96745199)response, I am a bit confused as to how the commissions works. 

The below is my code:
```
EMA_short = talib.EMA(price_data['aapl'], timeperiod=10).to_frame()
EMA_long = talib.EMA(price_data['aapl'], timeperiod=40).to_frame()
EMA_short.rename(columns={0:'aapl'}, inplace=True)
EMA_long.rename(columns={0:'aapl'}, inplace=True)
# Construct the signal
signal_ema = EMA_long.copy()
signal_ema[EMA_long.isnull()] = 0.0
signal_ema[EMA_short > EMA_long] = 1 # go long
signal_ema[EMA_short < EMA_long] = -1 # go short
bt_strategy_ema_cross = bt.Strategy('EMA_crossover', 
                                    [bt.algos.WeighTarget(signal_ema), # not using a direct price comparison. 
                                     bt.algos.Rebalance()])
# commission
def my_comm(q, p):
    return abs(q)*0.025

# Create the backtest and run it
bt_backtest_e_c = bt.Backtest(bt_strategy_ema_cross, price_data, initial_capital=1000.0, commissions=my_comm) #lambda q, p: q * 0.095)
bt_result_e_c = bt.run(bt_backtest_e_c)

# Plot the backtest result
bt_result_e_c.plot(title='Backtest result', figsize=(12,9))
plt.show()
```

Do I have to input the quantity? The price/transaction price? or does it happen automatically? Also, why is p not included in the function?

**Comment by samuel-poon** [comment]
The quantity is set when you run the backtest. Your backtest will use `my_comm()` to calculate your commission. In this case, you will pay 2.5c per share.

p is not included in the function because the commission is per-share. The commission structure doesn't care about the price of the stock, so the function doesn't account for it either.

**Comment by Socvest** [comment]
Thanks for your response, I truly appreciate it.

This is partly clarified. Regarding the commissions, is there a way to calculate it on a per trade basis rather than per share? Most brokers these days tend to use spread transaction costs, so cost per trade/transaction rather than per share.

**Comment by GlobalBritain** [comment]
Thanks for clarifying!
