### ISSUE TITLE
Type of license

### ISSUE THREAD

**Issue by vfilimonov** [pmorissette/bt#31]
Hi Philippe,

I think it would be good if you include the type of license in you repo. Especially it is important since this library in most of the cases imply commercial and proprietary use, and you definitely don't want to have any liabilities to those who use your code ;-) By default with no-license your code is protected by the copyright, so: "This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work." 

Unfortunately I could not advise you much here - I'm not a legal specialist. But you can have a look at a rather good summary here: https://tldrlegal.com/ or here: http://choosealicense.com/. Also there's a FAQ here: https://help.github.com/articles/open-source-licensing/.

Personally, I prefer non-restrictive open-source licenses, and license my code under [MIT license](https://tldrlegal.com/license/mit-license). One of the drawback of restrictive GPL-type of licenses is a requirement to keep the license type and pass source code together with binaries when distributing, which often might be a "no-go" for financial applications.

Best regards
Vladimir

**Comment by pmorissette** [comment]
Hey Vladimir,

I added MIT licenses to both ```bt``` and ```ffn```. Thanks for the heads up!

Phil
