### ISSUE TITLE
Is it possible to only start investment of capital after a certain date?

### ISSUE THREAD

**Issue by blenderben2** [pmorissette/bt#316]
For example, start backtest from 2015-10-01, but only start investment of capital at 2016-01-01. This feature is useful for algos that depend on past decisions, but you dont want to make an investment unless you're sure of the algo's decision beforehand.

**Comment by samuel-poon** [comment]
Yes, there's a built-in [`RunAfterDate`](https://pmorissette.github.io/bt/_modules/bt/algos.html#RunAfterDate) Algo.

**Comment by blenderben2** [comment]
`RunAfterDate` dosen't suite my case, I found that if I let it run from 2015 as normal and just [rebase](https://github.com/pmorissette/ffn/blob/0575a43cdfd4d66eb3d8cc638f45d9595e889022/ffn/core.py#L1188) the portfolio price at 2016 during the end when extracting the results, it works too.
