### ISSUE TITLE
Plotting "locked" in visual studio code until unlocked by another non-'bt' plot

### ISSUE THREAD

**Issue by onionhammer** [pmorissette/bt#326]
Related issue: https://github.com/microsoft/vscode-jupyter/issues/7223

## Expected behaviour

A plot should be rendered regardless of order of imports

## Actual behaviour

Plot is only rendered for 'bt' library if a plot has already been rendered previously

## Steps to reproduce:

A notebook with the following cells produces no plots:

```py
### Cell 1
import bt

# download data
data = bt.get('aapl', start='2020-01-01')
sma = data.rolling(50).mean()
plot = bt.merge(data, sma).plot(figsize=(15, 5))
```

A notebook with the following cells produces two plots:

```py
### Cell 1
import matplotlib.pylab as plt
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show()

### Cell 2

import bt

# download data
data = bt.get('aapl', start='2020-01-01')
sma = data.rolling(50).mean()
plot = bt.merge(data, sma).plot(figsize=(15, 5))
```

# Workaround
Add line `%matplotlib inline` to top of notebook

**Comment by timkpaine** [comment]
I don't think this has anything to do with bt, this is just how matplotlib works. You need to plt.show to plot the composed figure, but if you run in in-line it will render the plot (e.g. call show()) when it's the returned value of the cell.

**Comment by onionhammer** [comment]
@timkpaine You dont actually need to call plot.show:

```
AttributeError: 'AxesSubplot' object has no attribute 'show'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_3295/341233879.py in <module>
      5 # let's see what the data looks like - this is by no means a pretty chart, but it does the job
      6 plot = bt.merge(data, sma1, sma2).plot(figsize=(15, 5))
----> 7 plot.show()

AttributeError: 'AxesSubplot' object has no attribute 'show'
```

But fair enough, it's not a bug per se but a note could be added to the readme about how to use bt within notebooks (jupyter/vs code)

**Comment by timkpaine** [comment]
That's not how matplotlib works, you don't call show on the object you call it via pyplot. I suggest going through the matplotlib docs and learning more about the pyplot interface.

**Comment by MDDietz1** [comment]
I believe this is linked to the underlying package FFN overwriting the matplotlib settings. See https://github.com/pmorissette/ffn/issues/141

A workaround is to include something like the following at the very start of your code (before importing BT)
`import os`
`if "DISPLAY" not in os.environ: os.environ['DISPLAY'] = ''`
