### ISSUE TITLE
How to setup simple RSI Strategy

### ISSUE THREAD

**Issue by nathanramoscfa** [pmorissette/bt#338]
Are there any examples of the bt library being used to to run a simple RSI strategy that buys a stock when RSI is below 30 and sells it when it is above 70? I wasn't able to find any detailed examples.

**Comment by Socvest** [comment]
import bt
from talib import * 

data = bt.get('spy', start='2010-01-01')
rsi = RSI(data['spy'], timeperiod=14) #using tablib
tw= rsi.copy().to_frame().rename(columns={0: 'RSI'})

percentiles = [30, 70]
p = np.percentile(rsi.dropna(), percentiles)
short = p[-1]
long = p[0]
tw['position'] = np.where(rsi > short, -1, np.nan)
tw['position'] = np.where(rsi < long, 1, tw['position'])
tw['position'] = tw['position'].ffill()
tw['position'] = tw['position'].fillna(0)

tw.plot(secondary_y = ['position'], figsize=(15,9))

tw.rename(columns={'position': 'spy'}, inplace=True)
rsi_threshold= bt.Strategy('RSI_Thresholds', 
                                            [bt.algos.WeighTarget(tw['spy'].to_frame()),
                                             bt.algos.Rebalance()]) 

t = bt.Backtest(rsi_threshold, data)
res = bt.run(t)
res.plot()


sources: 
1. https://github.com/mjmacarty/alphavantage/blob/main/6-mean_reversion.ipynb
2. https://pmorissette.github.io/bt/examples.html

**Comment by nathanramoscfa** [comment]
Thank you! I edited it a bit to make it run without errors. 

```
%matplotlib inline
import bt
import numpy as np
import matplotlib.pyplot as plt
from talib import *

# simple backtest to test long-only allocation
def long_only_ew(tickers, start, name='long_only_ew'):
    s = bt.Strategy(name, [bt.algos.RunOnce(),
                           bt.algos.SelectAll(),
                           bt.algos.WeighEqually(),
                           bt.algos.Rebalance()])
    data = bt.get(tickers, start=start)
    return bt.Backtest(s, data)

ticker = 'spy'
start_date ='2000-01-01'
data = bt.get(ticker, start=start_date)
rsi = RSI(data[ticker], timeperiod=14) #using tablib
tw= rsi.copy().to_frame().rename(columns={0: 'RSI'})

percentiles = [30, 70]
p = np.percentile(rsi.dropna(), percentiles)
short = p[-1]
long = p[0]
tw['position'] = np.where(rsi > short, -1, np.nan)
tw['position'] = np.where(rsi < long, 1, tw['position'])
tw['position'] = tw['position'].ffill()
tw['position'] = tw['position'].fillna(0)

tw.plot(secondary_y = ['position'], figsize=(15,9))

tw.rename(columns={'position': ticker}, inplace=True)
rsi_threshold= bt.Strategy(
    'RSI_Strategy', [
        bt.algos.WeighTarget(tw[ticker].to_frame()), 
        bt.algos.Rebalance()
    ])
t = bt.Backtest(rsi_threshold, data)
benchmark = long_only_ew(ticker, start_date)
res = bt.run(t, benchmark)
res.plot()
```

**Comment by Socvest** [comment]
Great! glad it works!
