### ISSUE TITLE
Cannot allocate capital to 0 because price is 0 as of 2020-06-25 00:00:00

### ISSUE THREAD

**Issue by CDLim0906** [pmorissette/bt#340]
Hi Phillippe, 
First of all thanks for creating a great package such as BT. I am running into some small hiatus here. Everything seems okay, and I think the data is in Dataframe and it could be shown in a graph. But when I am trying to run Backtest I get an exception message as follow: " 

Exception: Cannot allocate capital to 0 because price is 0 as of 2020-06-25 00:00:00`

"

any help would be highly appreciated. 

Thanks. 

`
# Construct the Signal and plotting it
EMA_short = talib.EMA(price_data['tsla'],
                      timeperiod=10).to_frame()
EMA_long = talib.EMA(price_data['tsla'],
                     timeperiod=40).to_frame()

signal = EMA_long.copy()
signal[EMA_long.isnull()] = 0

signal[EMA_short > EMA_long] = 1
signal[EMA_short < EMA_long] = -1

#Plot the signal, price and MAs
combined_df = bt.merge(signal, price_data, EMA_short, EMA_long)
combined_df.columns = ['Signal', 'Price', 'EMA_short', 'EMA_long']

combined_df.plot(secondary_y=['Signal'])`

![image](https://user-images.githubusercontent.com/16059227/147261138-43cc7bff-b36b-448a-95f3-67ea1c4b04b7.png)

the plot looks okay but I am unable to use bt.run 

`
# Backtest
#Define the strategy
bt_strategy = bt.Strategy('EMA_crossover',
                          [bt.algos.WeighTarget(signal),
                           bt.algos.Rebalance()])

#Create the backtest and run it
bt_backtest = bt.Backtest(bt_strategy, price_data)
bt_result = bt.run(bt_backtest)

#Plot the backtest result
bt_result.plot(title='Backtest result')
`

`
# Return Error
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-78-8b7bad8ad191> in <module>
      6 #Create the backtest and run it
      7 bt_backtest = bt.Backtest(bt_strategy, price_data)
----> 8 bt_result = bt.run(bt_backtest)
      9 
     10 #Plot the backtest result

~/opt/anaconda3/lib/python3.8/site-packages/bt/backtest.py in run(*backtests)
     26     # run each backtest
     27     for bkt in backtests:
---> 28         bkt.run()
     29 
     30     return Result(*backtests)

~/opt/anaconda3/lib/python3.8/site-packages/bt/backtest.py in run(self)
    238 
    239             if not self.strategy.bankrupt:
--> 240                 self.strategy.run()
    241                 # need update after to save weights, values and such
    242                 self.strategy.update(dt)

~/opt/anaconda3/lib/python3.8/site-packages/bt/core.cpython-38-darwin.so in bt.core.Strategy.run()

~/opt/anaconda3/lib/python3.8/site-packages/bt/core.cpython-38-darwin.so in bt.core.AlgoStack.__call__()

~/opt/anaconda3/lib/python3.8/site-packages/bt/algos.py in __call__(self, target)
   1810         # Turn off updating while we rebalance each child
   1811         for item in iteritems(targets):
-> 1812             target.rebalance(item[1], child=item[0], base=base, update=False)
   1813 
   1814         # Now update

~/opt/anaconda3/lib/python3.8/site-packages/bt/core.cpython-38-darwin.so in bt.core.StrategyBase.rebalance()

~/opt/anaconda3/lib/python3.8/site-packages/bt/core.cpython-38-darwin.so in bt.core.SecurityBase.allocate()

Exception: Cannot allocate capital to 0 because price is 0 as of 2020-06-25 00:00:00`

**Comment by timkpaine** [comment]
I've found that most errors occur when the input data has bad records, what does `price_data` look like?

**Comment by CDLim0906** [comment]
Hi, timkpaine, 
thanks for your reply and consideration. My price_data look like 

![image](https://user-images.githubusercontent.com/16059227/148695535-d86c3995-b5bd-4499-a456-89ab1ec77f09.png)

**Comment by timkpaine** [comment]
What about the date in question

**Comment by CDLim0906** [comment]
price_data = bt.get('tsla', start = '2020-5-1', end ='2021-12-1')

**Comment by timkpaine** [comment]
What is the price on the date in the error

**Comment by CDLim0906** [comment]
2020-06-25 
Exception: Cannot allocate capital to 0 because price is 0 as of 2020-06-25 00:00:00`

**Comment by JordanPlatts** [comment]
Man the TSLA price chart is crazy. I recommend debugging it. Are you using pycharm, Jupyter or some other IDE?

**Comment by CDLim0906** [comment]
I do have pycharm but I am not that good at it.

**Comment by Newtoniano** [comment]
@CDLim0906 @flapponi Signal data frame and stock price dataframe need to have the exact same column label otherwise you will get that error when running the backtest. See https://github.com/pmorissette/bt/issues/52#issuecomment-312475721 . That fixed it for me
