### ISSUE TITLE
Error with commissions on higher the initial capital amounts

### ISSUE THREAD

**Issue by Socvest** [pmorissette/bt#342]
I am currently having an issue with the commissions. I have set it as the below using the Interactive brokers model for CFD trading. How it works is that the highest fee is charged. If its greater than one, then the fee derived from 0.0050 will be used, else 1 will be used. 

  ```
        def my_comm(q, p):
            rate = 0.0050
            fee = q * p * rate
            if fee < 1:
                fee = 1
            return fee
```

I keep getting the below error when I use any initial value that is above 7000.

`Exception: The difference between what we have raised with q and the amount we are trying to raise has gotten bigger since last iteration! full_outlay should always be approaching amount! There may be a case where the commission fn is not smooth`

Is there any way to resolve this issue?

**Comment by posidonius** [comment]
@Socvest How did you solve this problem? I'm also experiencing it. Thanks!
