### ISSUE TITLE
backtest.get_security_weights() overwrites values history if the same security is used in multiple sub-strategies

### ISSUE THREAD

**Issue by MDDietz1** [pmorissette/bt#356]
I can access a time series of the values for each security using something like 
`<backtest>.strategy.members[<index>].values`
That is linking to 
https://github.com/pmorissette/bt/blob/99c453e803a816ec6c61daf2135fa8fe6b84e460/bt/core.py#L1241-L1251
If the same security is used in multiple strategies this still works fine (multiple instances of the same security, they have a different .full_name which highlights they sit in different substrategies etc)

Having run a backtest, I did just this - access their values history. Then I run `get_security_weights` then check the values again. For one instance of the duplicate security, the values series has changed and is now in line with the aggregate. As another check something has broken, I can rerun `get_security_weights` (having deleted stored results <backtest>._sweights=None) and get a different results table!

So what seems to happen is:
The backtest function get_security_weights() links to 
https://github.com/pmorissette/bt/blob/99c453e803a816ec6c61daf2135fa8fe6b84e460/bt/backtest.py#L296-L316
and then lines 310 and 312 are passing on a reference to values for the first occurrence of the security and thus overwrite `values` when additional instances of the same security are found.

My assumption was that the `@property` prevents overwriting and just hands over data, but that doesn't seem to be the case here??!!

As a solution, adding `.copy()` to lines 310 and 312 seems to fix the issue for me. However, there might be a better way to fix that in the `def values(self) `function.

**Comment by timkpaine** [comment]
fixed in https://github.com/pmorissette/bt/pull/383
