### ISSUE TITLE
Merging data not from YahooFinance

### ISSUE THREAD

**Issue by nathangourd** [pmorissette/bt#366]
Using bt.get(tickers), one of my tickers does not have any data on yahoo finance- it's a mutual fund (institutional share class). I could probably find data elsewhere, just wondering how I merge it with the existing df of the tickers that do have price data. Is there any easy way to do this? I assume if I download a csv and format it the same as the one created by bt/ffn, it would be something I could .concat() on to the existing df? Just curious how to go about it, or if there's something in the documentation that makes this a bit easier. Thanks in advance!

**Comment by timkpaine** [comment]
This sounds more like a pandas question, you can inspect the result of the get call to see the format and use standard pandas operations to merge in alternative data sources.
