### ISSUE TITLE
Design question for RFQ/non-continuous markets

### ISSUE THREAD

**Issue by notbanker** [pmorissette/bt#39]
Congrats on you work. 

Just pondering how this would be used in R.F.Q. style markets where we only have sporadic buying and selling opportunities and where we compete with other dealers to win a customer order. Supposing we have a trade record of the winning response price/size, I _think_ I would do something like the following:
- Write  class MaybeBuy(Algo):  to return True only when there is a buying opportunity. Similarly for sell opportunities. Write another "Algo" to return suggested bid/offer that fires when MaybeBuy is True. Write another Algo   WinRFQ that returns True if our price is the best. 

[Perhaps combine the above in one algo?]
- Write a Strategy that has member class commision_fn  to mock the actual economics of buying/selling at the price where we won the auction. This would also "allocate" an amount equal to the trade size. 

Can you think of anything I'm missing?

**Comment by pmorissette** [comment]
Hey @notbanker,

Thanks for the kind words!

To be honest, I am not very familiar with RFQ style markets nor am I familiar with the type of data you have. That being said, your approach seems to make sense. You should be able to simulate the market dynamics using custom algos and as long as you factor in the appropriate transactions costs (via commission_fn), then you should be able to have a pretty good model to backtest a given strategy.

I can't think of anything else but perhaps someone with more experience in RFQ markets will be able to chime in.

Cheers,
Phil

**Comment by timkpaine** [comment]
@notbanker if you're still interested all these years later, I would encourage you to talk to @ptomecek (a quick look at his profile will tell you why).

**Comment by timkpaine** [comment]
oh its you Peter :-) had to look at the GitHub logs, didn't realize this was one of your accounts

**Comment by microprediction** [comment]
Ha. Hey, I didn't see cal invite.

**Comment by ptomecek** [comment]
@microprediction It's a small world. I didn't see this until @timkpaine pointed it out to me, but a couple of weeks ago I independently added SimulateRFQTransactions, in addition to a number of other features which you may find useful for fixed income markets (notional weighted strategies, coupon paying instruments, bid/offer tracking, risk tracking, rolling securities and lifecycle handling for expired securities). Let me know if you want to discuss further. Possible tie-in for micro predictions?

**Comment by microprediction** [comment]
Ha !  Hello @ptomecek , @timkpaine    There might indeed be a tie in but even more closely, an example here of optimizing a trading strategy with the [embarrassingly](https://github.com/microprediction/embarrassingly) package might be cute. I'll try to add one there once I get my head back around bt. I'm actually working on something that is supposed to further optimize optimizing, in the case where the objective function is an aggregation (as with trading strategies) and that might be of interest too.

**Comment by microprediction** [comment]
A little hard for this newbie as the examples aren't really examples of making anything new. 

As I understand, an "algo" is a list (or list of lists) of callables that will be executed each period in order. It is a sequence of steps that mutates some structure ... which I'm trying to infer ... with some initialization conventions which I'm also trying to infer. To make a new algorithm one does the following

Create a callable derived from Algo ...

Ensure callable modifies some combination of 
        .temp['selected']         A list of indexes into portfolio, or keys?
        .temp['weights'] 
                                        anything else? 

Am I on the right track?

**Comment by timkpaine** [comment]
@ptomecek ^
