### ISSUE TITLE
Question about dividends

### ISSUE THREAD

**Issue by gabrielfior** [pmorissette/bt#394]
I would like to include dividends in my backtest for 2 tickers: ```ABCP11.SA``` and ```AIEC11.SA```. They have paid dividends in every month (kind of REIT). Please see my implementation for data fetching below:

```
data = bt.get('ABCP11.SA,AIEC11.SA', start='2022-01-01')
print(data.head())
```

This yields:
```
             abcp11sa   aiec11sa
Date                            
2022-03-15  69.217567  72.002869
2022-03-16  69.330429  72.050095
2022-03-17  69.264595  73.088821
2022-03-18  69.038857  73.372116
2022-03-21  69.057655  72.408920
```
However, dividend data is missing. Therefore 2 questions:
- Is there a way to directly retrieve dividend data using bt (maybe extra params on the bt.get function)?
- Is there a way to reinvest dividends automatically as part of a strategy? I am aware of other questions that went in this direction, mainly this [one](https://github.com/pmorissette/bt/issues/88), but still am looking for guidance.
Many thanks!

**Comment by MAhbab** [comment]
1) Yes, you can get fields besides adjusted close (the default field). The only way I've found to work is to pass in the field along with the ticker to `bt.get` separated by a colon. For example, to get dividends for SPY you'd do the following:

`spy_dividends = bt.get('SPY:Dividend')`

2)To simulate reinvesting dividends, you'll want to implement an `Algo` similar to [CapitalFlow](https://github.com/pmorissette/bt/blob/master/bt/algos.py#L1647)`  that adds capital to your strategy without explicitly affecting its returns. Essentially, you'll want the `Algo` to call `Strategy.readjust` and pass in values from a pandas DataFrame/Series of dividends. 

Hope that helps.

**Comment by gabrielfior** [comment]
@MAhbab many thanks, that solves the problem. Closing the issue now.
