### ISSUE TITLE
position error

### ISSUE THREAD

**Issue by yerikzheng** [pmorissette/bt#40]
Hi Philippe,

Thank you so much for sharing your excellent work. I quite like this library and did some experiments on that. I find some weird issues concerning position property.

Here is the code:

import bt
data = bt.get('spy, ashr, agg, eem, ewz', start='2014-01-01', end='2014-02-02')

class PrintAlgo(bt.Algo):
    def __init__(self):
        super(PrintAlgo, self).__init__()
    
    def __call__(self, target):
        print '\n' + '*' * 20 + str(target.now) + '*' * 20
        print target.positions
        print pd.DataFrame({x.name: x.positions for x in target.members
                                 if isinstance(x, bt.core.SecurityBase)})
        return True

s = bt.Strategy('s1', [
                       bt.algos.RunWeekly(),
                       bt.algos.SelectAll(),
                       bt.algos.WeighEqually(),
                       bt.algos.Rebalance(),
                       bt.algos.run_always(PrintAlgo()),
                        ])

test = bt.Backtest(s, data, initial_capital=80000)
res = bt.run(test)

Results:
print target.positions will always give empty dataframe (if print target._positions, it is None), however, if you extract vals (which is the second print) from positions function, it does give the position dataframe.
Any idea about this? It should give positions for all the children like second print when you call the property.

Result print (part)

********************2014-01-02 00:00:00********************
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

********************2014-01-03 00:00:00********************
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

********************2014-01-06 00:00:00********************
Empty DataFrame
Columns: []
Index: []
            agg  ashr  eem  ewz  spy
Date                                
2014-01-02    0     0    0    0    0
2014-01-03    0     0    0    0    0
2014-01-06  155   683  414  392   90

**Comment by pmorissette** [comment]
Hey @yerikzheng,

Sorry for the late reply. I am quite busy lately and I'll try to take a look at this as soon as I can. 

Cheers,
Phil

**Comment by pmorissette** [comment]
Hey @yerikzheng,

Just getting back to you after all this time! Sorry for the long wait. Just fixed this issue. It should now work fine with the latest version.

Thanks for your patience,
Phil
