### ISSUE TITLE
Exception from missing "future" module. 

### ISSUE THREAD

**Issue by FrithiofJensen** [pmorissette/bt#418]
On importing bt, I get this: 
```
Python 3.10.6 (main, Sep  1 2022, 14:20:41) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/..../Source Code/..../venv/lib/python3.10/site-packages/bt/__init__.py", line 1, in <module>
    from . import core
  File "bt\core.py", line 12, in init bt.core
ModuleNotFoundError: No module named 'future'
>>> 
```
I haven't got 'future' installed in my virtual environment, so probably the `from __future__ import division` kicks it off.  

Installing 'future' with `pip3 install future` makes that error go away. 

Obviously, this can be fixed by declaring another requirement in 'setup.py', but should one? 

Is 'futures' still needed?

**Comment by timkpaine** [comment]
future is a builtin
