### ISSUE TITLE
Using CSV files

### ISSUE THREAD

**Issue by skunkwerk** [pmorissette/bt#42]
Is there a way to load data from CSV files instead of Google or Yahoo finance - ie through Pandas?
An example would be great, thanks.

**Comment by pmorissette** [comment]
Hey @skunkwerk,

Pandas can indeed do that:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

Once you have your data loaded in, you can use it in bt as bt works with Pandas DataFrames.

Cheers,
Phil
