### ISSUE TITLE
ImportError: No module named 'core'

### ISSUE THREAD

**Issue by starkrampf** [pmorissette/bt#43]
Hi, I'm a newbie to python, but I'm really interested in using your bt project for backtesting.  I tried to follow the instructions --> install Anaconda for Mac (I used the 64bit version, Python 3.4).  Everything installs fine and I can use Anaconda's python dist via terminal.

Then, I try to import bt but I get this error:

>>> import bt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.4/site-packages/bt/__init__.py", line 1, in <module>
    import core
ImportError: No module named 'core'

What is the core module?  I can't find it.

Thanks!

**Comment by pmorissette** [comment]
Hey @starkrampf,

I haven't tested bt using Python 3 yet so I would first recommend installing the Python 2.7 version of Anaconda to see if that fixes the issue. 

Let me know,
Phil

**Comment by sensharma** [comment]
@pmorissette 
Hey dude, I am having the same problem, both with py 3.4 and 2.7. Any ideas as to what may be the rub?

**Comment by pmorissette** [comment]
Hey @sensharma,

Let me take a look and I'll try to get back to you soon. Mac or Windows?

**Comment by sensharma** [comment]
@pmorissette 
Thanks a lot mate! I'm on Mac (64 bit, El Capitan).

**Comment by pmorissette** [comment]
@sensharma, @starkrampf,

I just tried installing this in a new conda environment and didn't run into any issues (both on Mac and Linux). Just wondering if you had any error messages when installing bt? If so, please post them here. 

I simply installed bt with pip as follows:
```
pip install bt
```

Cheers,
Phil

**Comment by pmorissette** [comment]
Hey @sensharma & @starkrampf,

I made some changes recently - perhaps they can help with this issue. Could you please run ```pip install --upgrade bt``` and let me know if you are still running into errors?

Thanks,
Phil

**Comment by Holfve22** [comment]
Hi,

Im also having issues importing core, running on a windows x64 with python 2.7 (anaconda)

![btpython](https://cloud.githubusercontent.com/assets/12893367/11320759/a08db1f4-90a4-11e5-82f9-21edf2bef88b.png)

Looks like an awesome package tho, hope to try it out soon.

Best regards

**Comment by pmorissette** [comment]
Hey @Holfve22,

What is your bt version? The version number is in the file bt/__init__.py.

Could you also run ```pip install --upgrade bt``` to see if that helps?

Thanks,
Phil

**Comment by Holfve22** [comment]
Looks like I have 0, 1, 12

Running the upgrade it says BT is up to date, but throws errors on all the previous packages that i have, numpy for example. Not sure if thats relevant.

![bt1](https://cloud.githubusercontent.com/assets/12893367/11360244/04a88bb6-9283-11e5-82b5-6a94c7d31eea.png)

Thanks

**Comment by pmorissette** [comment]
Hey @Holfve22,

Can you run the following?

```python
import numpy as np
print np.__version__

import pandas as pd
print pd.__version__

import ffn
print ffn.__version__
```

What's the output? Any errors?

Thanks,
Phil

**Comment by Holfve22** [comment]
Hi Phil,

No errors with the imports

![bt2](https://cloud.githubusercontent.com/assets/12893367/11383610/c0f386e6-9309-11e5-9471-d750d8ef96ff.png)

Regards
Carl

**Comment by Holfve22** [comment]
Hi Phill, 

I managed to get it up and running, i found a core.pyd file in the bt folder. Since the issue was an DLL error I tried removing that file, seemed to have worked. What does that file do?

I also got an error on the backtest at line 123 in the backtest.py file, said something about the index not having a duplicated function. I commented out this part:

#       #if data.columns.duplicated().any():
 #           #cols = data.columns[data.columns.duplicated().tolist()].tolist()
 #           #raise Exception(
 #              # 'data provided has some duplicate column names: \n%s \n'
#               # 'Please remove duplicates!' % cols)

Regards

**Comment by pmorissette** [comment]
Hey @Holfve22,

Sorry I haven't gotten back to you - I've been quite busy lately.

To be honest, I mostly use linux & mac machines, so I don't have much experience on windows with ``bt``. ``bt`` compiles some of its core functionality to c code to speed things up (using cython). Perhaps the issue mentioned above is related. I would have to test it out on a windows machine to see for myself. 

As for the duplicates, this is probably related to the data structure you are passing in. What type of data are you using? Are you using the ``bt.get`` function, or something else?

Cheers,
Phil
