### ISSUE TITLE
Error with running example code in project page

### ISSUE THREAD

**Issue by pwlnow** [pmorissette/bt#441]
Hi, I ran into below error when running the example code in the project page.  I was using jupyter notebook, the error was in line bt.run(test):

...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 2
      1 test = bt.Backtest(s, data)
----> 2 res = bt.run(test)

File ~/projects/backtrader/.env/lib/python3.11/site-packages/bt/backtest.py:28, in run(*backtests)
     26 # run each backtest
     27 for bkt in backtests:
---> 28     bkt.run()
     30 return Result(*backtests)

File ~/projects/backtrader/.env/lib/python3.11/site-packages/bt/backtest.py:258, in Backtest.run(self)
    255         if self.progress_bar:
    256             bar.stop()
--> 258 self.stats = self.strategy.prices.calc_perf_stats()
    259 self._original_prices = self.strategy.prices

File ~/projects/backtrader/.env/lib/python3.11/site-packages/ffn/core.py:1188, in calc_perf_stats(prices)
   1177 def calc_perf_stats(prices):
   1178     """
   1179     Calculates the performance statistics given an object.
   1180     The object should be a Series of prices.
   (...)
   1186 
   1187     """
-> 1188     return PerformanceStats(prices)

File ~/projects/backtrader/.env/lib/python3.11/site-packages/ffn/core.py:64, in PerformanceStats.__init__(self, prices, rf, annualization_factor)
     61 self.rf = rf
     62 self.annualization_factor = annualization_factor
---> 64 self._update(self.prices)

File ~/projects/backtrader/.env/lib/python3.11/site-packages/ffn/core.py:82, in PerformanceStats._update(self, obj)
     80 def _update(self, obj):
     81     # calc
---> 82     self._calculate(obj)
     84     # update derived structure
     85     # return table as dataframe for easier manipulation
     86     self.return_table = pd.DataFrame(self.return_table).T

File ~/projects/backtrader/.env/lib/python3.11/site-packages/ffn/core.py:237, in PerformanceStats._calculate(self, obj)
    234 self.cagr = calc_cagr(dp)
    235 self.incep = self.cagr
--> 237 self.drawdown = dp.to_drawdown_series()
    238 self.max_drawdown = self.drawdown.min()
    239 self.drawdown_details = drawdown_details(self.drawdown)

File ~/projects/backtrader/.env/lib/python3.11/site-packages/ffn/core.py:1235, in to_drawdown_series(prices)
   1232 drawdown = drawdown.ffill()
   1234 # Ignore problems with NaN's in the beginning
-> 1235 drawdown[np.isnan(drawdown)] = -np.Inf
   1237 # Rolling maximum
   1238 if isinstance(drawdown, pd.DataFrame):

File ~/projects/backtrader/.env/lib/python3.11/site-packages/numpy/__init__.py:397, in __getattr__(attr)
    394     raise AttributeError(__former_attrs__[attr])
    396 if attr in __expired_attributes__:
--> 397     raise AttributeError(
    398         f"`np.{attr}` was removed in the NumPy 2.0 release. "
    399         f"{__expired_attributes__[attr]}"
    400     )
    402 if attr == "chararray":
    403     warnings.warn(
    404         "`np.chararray` is deprecated and will be removed from "
    405         "the main namespace in the future. Use an array with a string "
    406         "or bytes dtype instead.", DeprecationWarning, stacklevel=2)

AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

Is this a compatibility issue with NumPy that was i nstalled?    The python version installed is 3.11.6, NumPy version is 2.0.0.
bt was installed using 'pip3 install bt' in virtualenvironment.

**Comment by timkpaine** [comment]
`numpy` 2.0 came out like 3 days ago, I recommend downgrading until libraries get a chance to upgrade.

**Comment by pwlnow** [comment]
Thank you, appreciate the quick response

Regards,
PWL
