### ISSUE TITLE
'Series' object has no attribute 'items'

### ISSUE THREAD

**Issue by jdkcupid** [pmorissette/bt#45]
hello,
I try to run the example code on your website, the "SMA Crossover Strategy".
Things happen in

ma_cross = bt.Strategy('ma_cross', [bt.algos.WeighTarget(tw),
                                    bt.algos.Rebalance()])

t = bt.Backtest(ma_cross, data)
res = bt.run(t)

res.plot()
--
which the error is 

AttributeError                            Traceback (most recent call last)
<ipython-input-2-edd02cae27bf> in <module>()
     25 
     26 t = bt.Backtest(ma_cross, data)
---> 27 res = bt.run(t)
     28 
     29 res.plot()

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/backtest.pyc in run(*backtests)
     24     # run each backtest
     25     for bkt in backtests:
---> 26         bkt.run()
     27 
     28     return Result(*backtests)

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/backtest.pyc in run(self)
    163             self.strategy.update(dt)
    164             if not self.strategy.bankrupt:
--> 165                 self.strategy.run()
    166                 # need update after to save weights, values and such
    167                 self.strategy.update(dt)

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/core.so in bt.core.Strategy.run (bt/core.c:15301)()

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/core.so in bt.core.AlgoStack.__call__ (bt/core.c:14703)()

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/algos.pyc in __call__(self, target)
   1222         # use it as base in rebalance calls
   1223         base = target.value
-> 1224         for item in targets.items():
   1225             target.rebalance(item[1], child=item[0], base=base)
   1226 

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
   2143                 or name in self._metadata
   2144                 or name in self._accessors):
-> 2145             return object.__getattribute__(self, name)
   2146         else:
   2147             if name in self._info_axis:

AttributeError: 'Series' object has no attribute 'items'

**Comment by pmorissette** [comment]
Can you show me the full code snippet you ran as well as your version of bt, pandas and numpy?

Also, could you please use the Github markdown syntax highlighting - makes it easier to read (https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting).

Thanks,
Phil

**Comment by jdkcupid** [comment]
Hello,

the environment is
```
numpy                     1.9.2
python                    2.7.10
pandas                    0.16.2
bt                        0.1.10
```


the code I used is

```
import bt
import pandas as pd
## download some data & calc SMAs
data = bt.get('spy', start='2010-01-01')
sma50 = pd.rolling_mean(data, 50)
sma200 = pd.rolling_mean(data, 200)

## now we need to calculate our target weight DataFrame
# first we will copy the sma200 DataFrame since our weights will have the same strucutre
tw = sma200.copy()
# set appropriate target weights
tw[sma50 > sma200] = 1.0
tw[sma50 <= sma200] = -1.0
# here we will set the weight to 0 - this is because the sma200 needs 200 data points before
# calculating its first point. Therefore, it will start with a bunch of nulls (NaNs).
tw[sma200.isnull()] = 0.0

# plot the target weights + chart of price & SMAs
tmp = bt.merge(tw, data, sma50, sma200)
tmp.columns = ['tw', 'price', 'sma50', 'sma200']
ax = tmp.plot(figsize=(15,5), secondary_y=['tw'])

ma_cross = bt.Strategy('ma_cross', [bt.algos.WeighTarget(tw),
                                    bt.algos.Rebalance()])

t = bt.Backtest(ma_cross, data)
res = bt.run(t)

res.plot()
```

the error message is
```
AttributeError                            Traceback (most recent call last)
<ipython-input-35-432950618976> in <module>()
     25 
     26 t = bt.Backtest(ma_cross, data)
---> 27 res = bt.run(t)
     28 
     29 res.plot()

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/backtest.pyc in run(*backtests)
     24     # run each backtest
     25     for bkt in backtests:
---> 26         bkt.run()
     27 
     28     return Result(*backtests)

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/backtest.pyc in run(self)
    163             self.strategy.update(dt)
    164             if not self.strategy.bankrupt:
--> 165                 self.strategy.run()
    166                 # need update after to save weights, values and such
    167                 self.strategy.update(dt)

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/core.so in bt.core.Strategy.run (bt/core.c:15301)()

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/core.so in bt.core.AlgoStack.__call__ (bt/core.c:14703)()

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/bt/algos.pyc in __call__(self, target)
   1222         # use it as base in rebalance calls
   1223         base = target.value
-> 1224         for item in targets.items():
   1225             target.rebalance(item[1], child=item[0], base=base)
   1226 

/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
   2143                 or name in self._metadata
   2144                 or name in self._accessors):
-> 2145             return object.__getattribute__(self, name)
   2146         else:
   2147             if name in self._info_axis:

AttributeError: 'Series' object has no attribute 'items'
```

**Comment by pmorissette** [comment]
Hey @jdkcupid,

I'm getting the same error on my end - let me look into it.

Thanks for reporting the issue!

Cheers,
Phil

**Comment by pmorissette** [comment]
Hey @jdkcupid,

A bug was introduced during a recent commit - if you upgrade bt everything should now work as expected.

Let me know if you have any other issues/questions.

Cheers,
Phil
