### ISSUE TITLE
Can't Have Sell Points in Backtesting an Algo

### ISSUE THREAD

**Issue by ab123-bruh** [pmorissette/bt#450]
We are trying to create an algo to buy and sell at different price points. From the documentation written in the API, there is no indication to potentially sell at a specific price point. If buying and selling at different price points isn't a feature, it needs to be added

**Comment by posidonius** [comment]
You can do this easily by writing your own algo. This kind of logic is up to you to create. Search the Issues history of this repo for examples of people who have implemented a Limit Order algo. It is not that hard.
