### ISSUE TITLE
module 'yfinance' has no attribute 'pdr_override'

### ISSUE THREAD

**Issue by simoneb** [pmorissette/bt#451]
Running any BT code with `bt.get` today I started getting:

```
module 'yfinance' has no attribute 'pdr_override'
```

**Comment by timkpaine** [comment]
`pdr_override` does not appear in the codebase for `bt`.

Separately, `pandas_datareader` support in `ffn` was removed [here](https://github.com/pmorissette/ffn/pull/239).

**Comment by simoneb** [comment]
Ok but could you please clarify how to bt.get now?
