### ISSUE TITLE
Example for  implementation of CapitalFlow algo

### ISSUE THREAD

**Issue by mosesmc52** [pmorissette/bt#51]
Hi I just started to use the bt backtesting framework. I understand how to use most of the framework, but don't quite understand how to apply the CapitalFlow algo. My understanding is that the CapitalFlow algo inserts an amount specified by the user within every iteration run of the Algo whether daily, monthly or annually. I'm not quite sure how to visualize the results with capital injections. I have only found the plot visualization. I just would like an example how the CapitalFlow algo works. 

Thanks,

moses

**Comment by pmorissette** [comment]
Hey @mosesmc52,

Thanks for you interest! I'm quite busy lately but will try to get back to you as soon as possible.

Thanks for your patience,
Phil

**Comment by pmorissette** [comment]
Hey @mosesmc52,

This algo is quite simple - it just adjusts the capital in the strategy's account. This can be used to simulate systematic inflows/outflows. Then, on the next rebalance period, this new cash will be allocated according to the rest of your algos. 

Just wondering what you want to see other than the standard charts/metrics? 

Cheers,
Phil

**Comment by mosesmc52** [comment]
Hi Phil, 

Sorry for the late response and thanks for asking.

I have been using both [Quantopian's](https://www.quantopian.com) zipline backtesting tool and bt. To indirectly answer your question, I would look at the the library released by quantopian called [pyfolio](https://github.com/quantopian/pyfolio). For my own interest, I would like to see a few additional metrics: Risk Adjusted Sharpe Ratio, Sortino Ratio, and Kelly Criterion. 

One difference I noticed between the output of bt and Quantopian is that bt output for the same algo is a little more optimistic whereas Quantopian return is less. I am rebalancing the algo on a monthly basis and am primarily using ETFs. Do you think the difference is because of the quality of the data?

One additional option I would like the option to extract the the output of the backtest results. To save the securities that traded on that day not just view it using the plot_security_weights method, and view the price data on that day of rebalance. How would I do that?

Moses

**Comment by neerlent** [comment]
I second the request for a simple example using CapitalFlow.  I'd like to use this framework to experiment with dollar cost averaging frequency.  I am new to all of this, and I'm not even sure if this is the correct tool for the job.  I'm assuming CapitalFlow() would be used to simulate regular equity purchases, but my attempts to use this function did not produce the expected results.

More examples would go a long way in illustrating the full capabilities of your cool framework!

Thanks,

Matt

**Comment by zsljulius** [comment]
I have a simple example here for Dollar Cost Average strategy.

```
data = bt.get("spy", start="2017-01-01")
s1 = bt.Strategy("DAC", [bt.algos.SelectAll(), 
                        bt.algos.CapitalFlow(100000),
                        bt.algos.WeighEqually(), 
                        bt.algos.RunWeekly(),
                        bt.algos.Rebalance()])

s2 = bt.Strategy("BnH", [bt.algos.SelectAll(), 
                        bt.algos.WeighEqually(), 
                        bt.algos.RunWeekly(), 
                        bt.algos.Rebalance()],)
t1 = bt.Backtest(s1, data)
t2 = bt.Backtest(s2, data)
res = bt.run(t1, t2)
```

The result looks reasonable. In the bull market of 2017, the DCA strategy obviously underperform the Buy and Hold

```
Stat                 DAC         BnH
-------------------  ----------  ----------
Start                2017-01-02  2017-01-02
End                  2017-12-04  2017-12-04
Risk-free rate       0.00%       0.00%

Total Return         17.68%      18.30%
Daily Sharpe         2.72        2.73
Daily Sortino        3.51        3.55
CAGR                 19.35%      20.04%
Max Drawdown         -2.51%      -2.61%
Calmar Ratio         7.71        7.68

MTD                  -0.32%      -0.33%
3m                   7.03%       7.10%
6m                   9.10%       9.24%
YTD                  17.68%      18.30%
1Y                   -           -
3Y (ann.)            -           -
5Y (ann.)            -           -
10Y (ann.)           -           -
Since Incep. (ann.)  19.35%      20.04%

Daily Sharpe         2.72        2.73
Daily Sortino        3.51        3.55
Daily Mean (ann.)    17.82%      18.41%
Daily Vol (ann.)     6.55%       6.75%
Daily Skew           -0.48       -0.45
Daily Kurt           3.19        3.02
Best Day             1.35%       1.40%
Worst Day            -1.74%      -1.77%

Monthly Sharpe       4.00        3.96
Monthly Sortino      -           -
Monthly Mean (ann.)  17.32%      18.04%
Monthly Vol (ann.)   4.33%       4.56%
Monthly Skew         0.28        0.41
Monthly Kurt         -0.97       -0.58
Best Month           3.56%       3.93%
Worst Month          -0.32%      -0.33%

Yearly Sharpe        -           -
Yearly Sortino       -           -
Yearly Mean          -           -
Yearly Vol           -           -
Yearly Skew          -           -
Yearly Kurt          -           -
Best Year            -           -
Worst Year           -           -

Avg. Drawdown        -0.50%      -0.51%
Avg. Drawdown Days   8.13        7.87
Avg. Up Month        1.62%       1.69%
Avg. Down Month      -0.32%      -0.33%
Win Year %           -           -
Win 12m %            -           -
```

**Comment by MichaelMorrisNZ** [comment]
> > Hey @mosesmc52,
> > This algo is quite simple - it just adjusts the capital in the strategy's account. This can be used to simulate systematic inflows/outflows. Then, on the next rebalance period, this new cash will be allocated according to the rest of your algos.
> > Just wondering what you want to see other than the standard charts/metrics?
> > Cheers, Phil
> 
> @pmorissette Just curious, what if I would like the funds to be invested immediately according to whatever security weights the portfolio current has (I don't want to wait until the next rebalance period), what changes should I make to the CapitalFlow algo?

I second this request please, advise on modelling adhoc flows with simultaneous prorata allocation across child strategies and their instruments would be greatly appreciated!
