### ISSUE TITLE
use BT.get() or ffn.get() to retrieve data for SMI

### ISSUE THREAD

**Issue by jeffereylj** [pmorissette/bt#53]
Hello @pmorissette , I am using BT.get() or ffn.get() to retrieve data to calculate SMI(stochastic momentum index). I like this function as it can get historical intraday high and low for the calculation. 
what I have done is like these

data = bt. get("aapl:close, aapl:high, aapl:low")
closing =data. aaplclose
-- more codes---
bt.backtest(strategy, closing)

But I encounter the problem when running the backtesting function, bt.backtest(strategy, closing). The error message says something like the data "closing" does not have attribute of columns.

Could you please check?

Thanks,

Jun

**Comment by pmorissette** [comment]
Hey @jeffereylj,

I think this is because you are selecting a single column, and Pandas is returning a TimeSeries as opposed to a DataFrame (which bt expects).

Try using this instead:

```python
data = bt.get("aapl:Close,aapl:High,aapl:Low")
close = data[['aaplclose']]
```

In the above example, ```typeof(close)``` will be a DataFrame.

Cheers,
Phil
