### ISSUE TITLE
plot not showing

### ISSUE THREAD

**Issue by J13B** [pmorissette/bt#54]
Hi Philippe,

I'm new to bt but enjoyed playing with it, thanks to the well thought architecture of the project.
After a few adjustments for libraries, I managed to make bt run properly.
The last issue I face is not being able to show plots. It seems to me that this may be a library issue again.
I run Python version 2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2] + Pandas version 0.17.0.

matplotlib looks fine as I can show plots easily directly with basic scripts using matplotlib.
Pandas 0.17.0 recently released on Oct 9. Do you think this can be the issue? (looks like you generate the standard plots from Pandas, pls correct me if I'm wrong).

Thanks a lot for your help.
I'm looking forward to building on bt !!!

**Comment by pmorissette** [comment]
Hey @J13B,

Thanks for the kind words.

Where are you looking to generate the plots? Inside a IPython/Jupyter notebook? If so, you must include the ```%matplotlib inline``` command to display the charts inline. 

If this is not the issue, let me know what is happening - any error messages? 

Cheers,
Phil

**Comment by J13B** [comment]
Hi Phil,

Thanks for your prompt answer.
If I just paste the first example (http://pmorissette.github.io/bt/examples.html) in a py script, and then run it (no ipython or whatever interactive mode, command line only), I can't get the plot to show up.

In this example for the sma strategy, calculations are correct though. In this case, I guess you use the plot from pandas. No error message, nothing: just no plot.

Btw, I implemented a personal strategy, cross validated with Excel, and the results look good.
I just need the plot which is a huge + when designing strategies, and the tree structure is exactly what I need.

Best,
JB

**Comment by J13B** [comment]
Getting closer: 
pandas==0.17.0 + matplotlib==1.5.0

a simple script like this, taken from pandas doc doesn't generate any plot either (again no error msg, same behavior)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()

**Comment by J13B** [comment]
The END.

Sorry for wasting your time. I thought that matplotlib.pyplot.show was not necessary (implicit when called through bt or pandas), when it actually is.
So it works now. You may just have to update the examples (or not ...)

Cheers,
J13B

**Comment by pmorissette** [comment]
Hey @J13B,

No worries!

Cheers,
Phil

**Comment by hmz123** [comment]
Hey ,
i have the same problem 
what do I have to do ?
