### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('numpy>=1.7.0')

### ISSUE THREAD

**Issue by mosesmc52** [pmorissette/bt#55]
Hi I ran the command 
"pip install bt"

on unbuntu 14.4, but I received this error. I'm not sure how to fix it. 
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy>=1.7.0')

I tried to install numpy and pandas using ubuntu app-get command, but that didn't fix the problem. 

Moses

**Comment by pmorissette** [comment]
Hey @mosesmc52,

Could you please tell me which versions of numpy and pandas you have installed? Also, maybe try installing them via pip instead of apt-get.

Let me know,
Phil
