### ISSUE TITLE
Backtesting on intraday data

### ISSUE THREAD

**Issue by TheTradingWarrior** [pmorissette/bt#58]
Hi,

I've been using bt for a while now and I love the framework. However, I have been struggling in using it for intraday data since you'd have two relevant price series when backtesting ( bid + ask and not only the close) . How can I fix this issue when running the backtest ?

Thanks.

**Comment by pmorissette** [comment]
Hey @TheTradingWarrior,

Sorry for the (very) late reply! 

I designed the framework with a single price in mind. I was mostly focused on longer-term strategies, where assuming the close price was not an issue. 

In your case, I'm afraid you would have to write some custom code. The ```allocate``` functions on ```StrategyBase``` and ```SecurityBase``` should be good starting points to see how this all works. 

Basically, you have two options. The best one, in my opinion, would be to re-write/extend the core framework to support bid/ask prices (perhaps with a new BidAskStrategyBase class that inherits from StrategyBase). The logic within ```SecurityBase.allocate``` would have to be rewritten to automatically use the bid or ask depending on the direction of the trade. 

Alternatively, you could write a custom Algo that will analyze the direction of the trade, and overwrite the price at that point in time (with the bid or ask price). This would run right before the Rebalance algo. In this case, you wouldn't have to touch the core framework. This is more of a hack, but it could work. 

I hope this makes sense, and if not, please don't hesitate reach out. 

Cheers,
Phil
