### ISSUE TITLE
how to use commission function?

### ISSUE THREAD

**Issue by candyneng** [pmorissette/bt#61]
here is my code:
data=pd.DataFrame(zz500['close']).truncate(before='2011/1/1')
s=bt.Strategy('Strategy',[bt.algos.SelectWhere(data.pct_change()>0),bt.algos.WeighEqually(),bt.algos.Rebalance()])
bench=bt.Strategy('000001',[bt.algos.RunOnce(),bt.algos.SelectAll(),bt.algos.WeighEqually(),bt.algos.Rebalance()])
test = bt.Backtest(s, data,commissions=lambda p,q: 0.05*p*q)
b = bt.Backtest(bench, data,commissions=lambda p,q: 0.05*p*q)
res = bt.run(test,b)

the final Nav become larger when I add commissions to my code? how can this happen?

Thank you for any help.

**Comment by pmorissette** [comment]
Hey @candyneng,

There is a default commission function ($0.01 per share, with a minimum of $1 per transaction). Depending on the function you pass, you may have a higher/lower ending NAV. By the way, I'm not sure if you had an issue pasting your code, but you commission function does not appear to be valid python:

```python
# this is not valid python 
lambda p,q: 0.05pq
``` 

Hope this helps,
Phil
