### ISSUE TITLE
'Index' object has no attribute 'duplicated'

### ISSUE THREAD

**Issue by smillerd** [pmorissette/bt#62]
I have recently installed bt. I'm super excited about its potential -- however I've run into a problem when I try to call `bt.backtest(strategy, data)`. I'm following along the [examples page](http://pmorissette.github.io/bt/examples.html), and when I call `t = bt.backtest(s, data)` I get an error "'Index' object has no attribute 'duplicated'"

I've tried to remove bt and install it again, no avail. I'm working on a vagrant box, so I destroyed the box and recreated the environment, still nothing. I'm fairly new to python still, otherwise I would try to fix this myself.

The full error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-11602183c4c2> in <module>()
      5 
      6 # now we create the Backtest
----> 7 t = bt.Backtest(s, data)
      8 
      9 res = bt.run(t)

/home/vagrant/anaconda/lib/python2.7/site-packages/bt/backtest.pyc in __init__(self, strategy, data, name, initial_capital, commissions, integer_positions)
    121                  integer_positions=True):
    122 
--> 123         if data.columns.duplicated().any():
    124             cols = data.columns[data.columns.duplicated().tolist()].tolist()
    125             raise Exception(

AttributeError: 'Index' object has no attribute 'duplicated'

**Comment by J13B** [comment]
I got the same problem after an install on a new Linux box.
Working on a Linux box I installed Bt on months ago.

**Comment by smillerd** [comment]
Thanks!
