### ISSUE TITLE
Exception: Cannot allocate capital to XNAS/BLUD because price is nan as of 2011-08-19 00:00:00

### ISSUE THREAD

**Issue by spencerns** [pmorissette/bt#63]
hey guys-

I'm getting an error due to stocks that became de-listed at some time during the simulation. bt is throwing an error when it tries to run `Strategy.close(child)` at the line 716:  `c.allocate(-c.value)` 

Here's some info:
- my data was pulled from the Exchange Data International via the Quandl API directly into pandas using pd.read_csv()
- the relevant area of the data:

```
            XNAS/KMB  XNAS/SHOP  XNAS/BLUD  XNAS/WFT_1_UADJ
Date                                                        `
2011-08-12  61.817510        NaN      26.79           17.295
2011-08-15  62.719193        NaN      26.83           17.685
2011-08-16  62.728684        NaN      26.93           17.200
2011-08-17  62.605296        NaN      26.94           17.380
2011-08-18  62.254114        NaN      26.81           16.010
2011-08-19  62.064286        NaN        NaN           15.010
2011-08-22  62.415468        NaN        NaN           14.690
2011-08-23  63.820196        NaN        NaN           15.510
2011-08-24  64.484594        NaN        NaN           15.600
```
I think the solution (if this is even a real bug) might be that `Strategy.close(child)` (bt.core.py line 704) needs to test whether c.price is not nan like:
```
if isnan(c.value):
    c.allocate(-c._last_value)
else:
    c.allocate(-c.value)
```

I'd love to know if there is an Algo or something for this I skipped over, or if this is an actual bug! Thanks!

**Comment by spencerns** [comment]
Also, thank you so much for bt!! I'm excited to be working with it

**Comment by pmorissette** [comment]
Hey @spencerns,

Thanks for the feedback. Looking into this and will report back. 

Cheers,
Phil

**Comment by s-hood** [comment]
Hey @spencerns and @pmorissette, any update on this problem? I'm getting exactly the same error for the first day a stock is de-listed. 

Cheers!

**Comment by spencerns** [comment]
no update, sorry, i've switched to pyalgotrade

**Comment by pmorissette** [comment]
Hey @s-hood,

I just pushed an update. Can you install the latest version and let me know if you still have the same error?

Thanks,
Phil

**Comment by s-hood** [comment]
Hey, thanks - it's working well now.

**Comment by pmorissette** [comment]
Ok great to hear. Sorry for the slow response.

Cheers,
Phil

**Comment by HornKild** [comment]
Hello, I'm facing the same issue here : `Position is open (non-zero) and latest price is NaN for security...`.
Do you think filling these `NaN` with zero could be a workaround to consider ?
