### ISSUE TITLE
Help with WeighTarget algo

### ISSUE THREAD

**Issue by wlblount** [pmorissette/bt#64]
I am trying to rebalance annually.  If my data starts on 1/1/2000 then the target weights do not kick in until 12/31/2000 so the strat return flatlines from 1/1/2000 until the first rebalance at 12/31/2000.  i am using resample to get the annual tw df.  I do not have this issue with df.to_monthly... it seems the target weights are provided at the beginning of the strat period.  any suggestions on how to handle this?

**Comment by pmorissette** [comment]
Hey @wlblount,

Sorry for the late reply. 

```WeighTarget``` will set the target weights at each point in time in the target weights DataFrame. If the first entry in the target weights DataFrame is on 12/31/2000, ***bt*** will not rebalance until then. You will have to modify your target weights DataFrame to include the dates you are interested in. I'm guessing you are using something like this for the conversion:

```python
tw = data.resample('A').last()
``` 
If this is the case, A means "Year End Frequency". If you want to rebalance right from the start, you could use AS (year start frequency) instead (see http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases for other options). Alternatively, you could keep the year end method but manually insert the first (initial) weights as of the first day in your dataset. 

Hope this helps,
Phil
