### ISSUE TITLE
Resultant weights of backtest not summing to 1

### ISSUE THREAD

**Issue by ceaza** [pmorissette/bt#67]
If I call this after running the backtest, for example: 
`mybacktest = bt.Backtest(long_equity_bt, data=dfp['RI'],initial_capital = 100000000,commissions=lambda q,p:100.0 + 0.003*p*q),`

 `mybacktest.weights.ix[some_date,1:]` is returning 0.9923 and not 1. I understand that this difference is the held back amount for rounding of stocks and fees if any.

This subsequently means that I trade more stocks than I expect. Is this expected behaviour?

On further investigation, if I rebase my desired target weights to the sum of target.children[c].weight for all nodes I get my desired number of trades, but it seems that the return of the strategy in question is impacted by the differential.

Am I using the bt framework correctly?

Going to account for the unallocated capital in strategy and see how that goes.

**Comment by ceaza** [comment]
I think there may be an issue:

If  run the following snippet:

    import bt
    import pandas as pd
    
    def long_only_ew(tickers, start='2010-01-01', name='long_only_ew'):
        s = bt.Strategy(name, [bt.algos.RunOnce(),
                               bt.algos.SelectAll(),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()])
        data = bt.get(tickers, start=start)
        return bt.Backtest(s, data,initial_capital=100000000)
    
    # create the backtests
    tickers = 'aapl,msft,c,gs,ge,aap,gas,aa,all,t,ba,bmy,bby,ccl,fb,goog,googl,\
        xom,amzn,wfc,jnj,mo,ame,amgn,aph,apc,adi,aon,apa,aiv,amat\
        azo,avgo,avb,avy,bhi,bll,bac,bk,bcr,bax,bbt,bdx,bbby,bwa,bxp'
    benchmark = long_only_ew(tickers, name='selected tickers')
    
    # run all the backtest!
    res2 = bt.run(benchmark)
    
    res2.plot()
    
Now one can see that the resultant weight is bigger than what can be explained by rounding.
(the first element is the parent)

    benchmark.weights.sum(axis=1).ix[:,1:]

Over time these errors may be substantial.

**Comment by pmorissette** [comment]
Hey @ceaza,

I'm not quite sure I understand the issue. Could you provide me with a simple example that would highlight this issue?

Thanks,
Phil

**Comment by ceaza** [comment]
Thank you Phil.

I am very grateful for what you have done here, thanks!

It's a simple algo where we have target weights, but only when the deviation from the target is greater than a value are we forced to trade. 
Please excuse the amateurish code but here is my example attached, initially based on your LimitDeltas. Problem is that still end up trading all the stocks, sometimes one, so weight is obviously misspecified.

 I tried to expose as much as possible in a dataframe for use later on:

    # -*- coding: utf-8 -*-
    """
    Created on Sun Jun  5 17:48:56 2016
    
    @author: charles
    """
    import bt
    import pandas as pd
    
    def psum(arr):
        return ((arr>([0.0]*len(arr))).astype(float)*arr).sum()
    
    def nsum(arr):
        return ((arr<=([0.0]*len(arr))).astype(float)*arr).sum()
     
    class LimitDeltas(bt.Algo):
    
        def __init__(self, limit=0.001):
            super(LimitDeltas, self).__init__()
            self.limit = limit
            # determine if global or specific
            self.global_limit = True
            
            if isinstance(limit, dict):
                self.global_limit = False
    
        def __call__(self, target):
            tw = target.temp['weights']
    #        print(target.now)
            positions={}
            if target.now in target.positions.index:
    #            print(target.positions.tail())
                positions=target.positions.ix[target.now,:].dropna().to_dict()
    
            all_keys = set(list(target.children.keys()) + list(tw.keys()))
    
            temp_dict={}
            fields=['price','weight','value','tgt','position']
            for fld in fields:
                t_dict={}
                for c in all_keys:
                    if fld=='tgt':
                        t_dict[c] = tw[c] if c in tw else 0.
                    elif fld=='position':
                        t_dict[c]= positions[c] if c in positions else 0.
                    else:
                        t_dict[c]=getattr(target.children[c], fld) if c in \
                            target.children else 0.
                temp_dict[fld]=t_dict
           
            temp_df=pd.DataFrame(temp_dict) 
    #        temp_df['cur']=temp_df.weight
            temp_df=temp_df.reset_index()
            cols=list(temp_df.columns)
            cols[0]='SYMBOL'
            temp_df.columns=cols
            temp_df['DATE']=target.now
            temp_df=temp_df.set_index(['DATE'])
            temp_df['cur']=(temp_df.position*temp_df.price)/ \
                (temp_df.position*temp_df.price).groupby(level='DATE').transform(sum)
            if temp_df.cur.sum()==0:
                temp_df.loc[:,'cur']=temp_df.tgt
            temp_df['delta']=temp_df.tgt-temp_df.cur
            temp_df['trd']=temp_df.delta.map(lambda x:0. if abs(x)<self.limit else x)
            temp_df['longWgtChg'] =temp_df.trd.groupby(level='DATE').transform(psum)
            temp_df['shortWgtChg']=temp_df.trd.groupby(level='DATE').transform(nsum)
            temp_df['totalWgtChg']=temp_df.longWgtChg+temp_df.shortWgtChg
    
    
            temp_df['trdWgtPct']= \
            (((temp_df.trd>0)*temp_df.trd)/(temp_df.longWgtChg+(temp_df.longWgtChg==0)))+ \
            (((temp_df.trd<0)*temp_df.trd)/(temp_df.shortWgtChg+(temp_df.shortWgtChg==0)))
         
            temp_df['trdFnl']=-(temp_df.trdWgtPct*temp_df.totalWgtChg* \
                (temp_df.totalWgtChg>0)*(temp_df.trd<0))- \
                (temp_df.trdWgtPct*temp_df.totalWgtChg*(temp_df.totalWgtChg<0)* \
                (temp_df.trd>0))+temp_df.trd
                    
            temp_df['final_twgt']=temp_df.cur+temp_df.trdFnl
            temp_df['is_trd']=temp_df.trdFnl>0.
    #        correction_multplier=temp_df.weight.sum() if temp_df.weight.sum()>0. else 1.
    #        temp_df['final_twgt']=temp_df.final_twgt*correction_multplier
            temp_df.to_hdf('/home/charles/python/backtest/trd_algo.hf5','table',append=False)        
    #        target.temp['weights']=(temp_df[temp_df.final_twgt>0]).set_index('SYMBOL').final_twgt.to_dict()
            if temp_df.final_twgt.sum()>0:
                target.temp['weights']=(temp_df[temp_df.final_twgt>0]).set_index('SYMBOL').final_twgt.to_dict()
            else:
                target.temp['weights']=tw
            return True
    
       
    def long_only_ew(tickers, start='2010-01-01', name='long_only_ew'):
        s = bt.Strategy(name, [bt.algos.RunMonthly(),
                               bt.algos.SelectAll(),
                               bt.algos.WeighEqually(),
                               LimitDeltas(), 
                               bt.algos.Rebalance()])
        data = bt.get(tickers, start=start)
        return bt.Backtest(s, data,initial_capital=100000000)
    
    # create the backtests
    tickers = 'aapl,msft,c,gs,ge,aap,gas,aa,all,t,ba,bmy,bby,ccl,fb,goog,googl'#,\
    #        xom,amzn,wfc,jnj,mo,ame,amgn,aph,apc,adi,aon,apa,aiv,amat\
    #        azo,avgo,avb,avy,bhi,bll,bac,bk,bcr,bax,bbt,bdx,bbby,bwa,bxp'
    benchmark = long_only_ew(tickers, name='selected tikers')
    
    # run all the backtests!
    res2 = bt.run(benchmark)
    
    res2.plot()
    
    print(benchmark.weights.ix[:,1:].sum(axis=1))
    
    print('Trades')
    print(benchmark.positions.diff())
    
    df=pd.read_hdf('/home/charles/python/backtest/trd_algo.hf5','table')
    
    print('dataframe of last target calc')
    print(df)
    
Thanks very much,
Charles

**Comment by ceaza** [comment]
Hi Phil

I manage to get the small odd lots down to a minimal amount (but still not perfect) if I work out weights weights again after rounding the positions to the nearest 1 as this is unallocated capital:

    benchmark.positions.diff()[(benchmark.positions.diff()>0).sum(axis=1)>0].T
    Out[40]: 
    Date   2012-06-01  2012-07-02  2012-08-01  2012-09-04  2012-10-01  2012-11-01  \
    aa       742576.0     22124.0         0.0     19724.0         0.0         0.0   
    aap       83436.0     10402.0     -1874.0         0.0      6565.0    -16331.0   
    aapl      79740.0         0.0     -1937.0     -7050.0      5619.0      7691.0   
    all      192555.0         0.0     -7925.0         0.0     -5528.0         0.0   
    ba        96423.0         0.0     -2392.0      3767.0      6280.0     -1777.0   
    bby      368951.0    -46775.0     71114.0         0.0     48206.0     55014.0   
    bmy      198495.0         0.0     -4211.0     18385.0      5830.0         0.0   
    c        233426.0         0.0         0.0    -19501.0     -9489.0    -29064.0   
    ccl      212744.0     -7183.0         0.0         0.0         0.0    -15698.0   
    fb       212206.0     -7648.0     95660.0     56584.0    -54878.0      9923.0   
    gas      186863.0         0.0     -7470.0         0.0     10516.0         0.0   
    ge       363669.0    -15562.0     -8692.0     10155.0    -21835.0     21091.0   
    goog      20624.0      1099.0     -2078.0     -1083.0     -1095.0      1816.0   
    googl     20583.0      1096.0     -2075.0     -1079.0     -1093.0      1812.0   
    gs        67174.0      1427.0     -2983.0     -3095.0     -2605.0     -4154.0   
    msft     231402.0         0.0      4998.0     -5118.0     19453.0         0.0   
    t        213841.0        -1.0    -13078.0      8424.0      5253.0     12475.0   
    
    Date   2012-12-03  2013-01-02  2013-02-01  2013-03-01     ...      2015-09-01  \
    aa        22667.0    -29533.0     45939.0     51743.0     ...             0.0   
    aap        7925.0      3343.0      3828.0     -3801.0     ...         -3257.0   
    aapl          0.0      8359.0     26411.0      5186.0     ...          4026.0   
    all       -6932.0         0.0         0.0     -9554.0     ...         26666.0   
    ba        -6484.0         0.0      7836.0     -4362.0     ...          6332.0   
    bby       76509.0     61042.0   -142853.0    -32787.0     ...        -58356.0   
    bmy           0.0      6052.0    -14256.0         0.0     ...         12478.0   
    c         17274.0    -29886.0      3795.0      3740.0     ...         18768.0   
    ccl           0.0      6521.0         0.0     19511.0     ...          7377.0   
    fb       -70977.0         0.0         0.0     15566.0     ...          3063.0   
    gas           0.0         0.0         0.0     10962.0     ...        -68754.0   
    ge            0.0         0.0         0.0    -10266.0     ...         13239.0   
    goog       -528.0         0.0      -392.0      -751.0     ...             0.0   
    googl      -527.0         0.0      -391.0      -749.0     ...             0.0   
    gs         2052.0     -4419.0     -3620.0         0.0     ...          3821.0   
    msft      22311.0         0.0      8023.0         0.0     ...         14837.0   
    t             0.0      4515.0      6719.0         0.0     ...             0.0   
    
    Date   2015-10-01  2015-11-02  2015-12-01  2016-01-04  2016-02-01  2016-03-01  \
    aa            0.0    149305.0    -57047.0    -60674.0    381789.0   -335791.0   
    aap       -5183.0      2882.0     15528.0      3226.0     -5476.0      3043.0   
    aapl          0.0         0.0      2930.0      9832.0      4970.0     -2574.0   
    all           0.0      7588.0     -7430.0      5218.0     -9913.0     -9300.0   
    ba            0.0     -3565.0         0.0      2334.0      9452.0      3176.0   
    bby       -8718.0     48415.0     50098.0        -1.0        -1.0    -44396.0   
    bmy          -1.0         0.0    -11334.0        -1.0      8446.0     -5545.0   
    c         12758.0         0.0         0.0      8025.0     36877.0     16303.0   
    ccl           0.0         0.0      9133.0    -19278.0     13040.0      5260.0   
    fb            0.0     -7257.0     -4824.0      3270.0    -19515.0      8250.0   
    gas        4250.0     11286.0         0.0    -10176.0    -11989.0      3498.0   
    ge       -17187.0    -32341.0    -11915.0    -20437.0      8769.0     -9943.0   
    goog          0.0     -1370.0     -1186.0         0.0      -784.0      1231.0   
    googl         0.0     -1025.0      -875.0         0.0      -848.0      1077.0   
    gs         4637.0         0.0         0.0      3331.0      4154.0      4336.0   
    msft     -10473.0    -24177.0    -11280.0         0.0    -14064.0     14120.0   
    t         15996.0     14249.0         0.0    -18038.0    -41975.0         0.0   
    
    Date   2016-04-01  2016-05-02  2016-06-01  
    aa            0.0   -187483.0    213961.0  
    aap           0.0      2309.0         0.0  
    aapl      -6213.0     21308.0     -8562.0  
    all           0.0      6761.0     -8191.0  
    ba            0.0     -7366.0      5084.0  
    bby       21143.0        -1.0         0.0  
    bmy        5756.0    -21358.0         0.0  
    c             0.0    -25242.0         0.0  
    ccl       -8534.0     16475.0      5508.0  
    fb            0.0     -4106.0         0.0  
    gas        5999.0         0.0         0.0  
    ge        -9906.0     13663.0      9706.0  
    goog          0.0      1287.0     -1027.0  
    googl         0.0      1413.0      -938.0  
    gs            0.0     -2536.0      2604.0  
    msft          0.0     20086.0    -14297.0  
    t             0.0     -7252.0         0.0 

However if use the default commissions this is the result I get:

    
    Out[43]: 
    Date   2012-06-01  2012-07-02  2012-08-01  2012-09-04  2012-10-01  2012-11-01  \
    aa       742576.0     21872.0         0.0     19653.0        -1.0        -3.0   
    aap       83436.0     10370.0     -1877.0        -1.0      6569.0    -16336.0   
    aapl      79740.0        -1.0     -1966.0     -6983.0      5557.0      7757.0   
    all      192555.0        -1.0     -7991.0        -2.0     -5483.0        -2.0   
    ba        96423.0        -1.0     -2426.0      3762.0      6285.0     -1787.0   
    bby      368951.0    -46353.0     71196.0        -4.0     47580.0     55478.0   
    bmy      198495.0        -1.0     -4282.0     18368.0      5835.0        -2.0   
    c        233426.0         0.0         0.0    -19406.0     -9580.0    -29143.0   
    ccl      212744.0     -7171.0        -1.0        -2.0        -2.0    -15790.0   
    fb       212206.0     -7631.0     96429.0     55649.0    -54347.0      9485.0   
    gas      186863.0        -1.0     -7536.0        -2.0     10519.0        -2.0   
    ge       363669.0    -15502.0     -8877.0     10135.0    -21622.0     21078.0   
    goog      20624.0      1091.0     -2078.0     -1072.0     -1095.0      1822.0   
    googl     20583.0      1088.0     -2074.0     -1069.0     -1093.0      1819.0   
    gs        67174.0      1404.0     -2984.0     -3068.0     -2608.0     -4180.0   
    msft     231402.0        -1.0      4956.0     -5124.0     19423.0        -2.0   
    t        213841.0        -3.0    -13154.0      8414.0      5257.0     12583.0   
    
    Date   2012-12-03  2013-01-02  2013-02-01  2013-03-01     ...      2015-09-01  \
    aa        22814.0    -29264.0     45958.0     51203.0     ...            -2.0   
    aap        7988.0      3272.0      3869.0     -3786.0     ...         -3282.0   
    aapl         -1.0      8275.0     26692.0      4886.0     ...          3974.0   
    all       -6987.0        -2.0        -2.0     -9393.0     ...         26595.0   
    ba        -6484.0        -1.0      7920.0     -4386.0     ...          5519.0   
    bby       76522.0     60386.0   -142782.0    -32247.0     ...        -58475.0   
    bmy          -2.0      6031.0    -14246.0        -2.0     ...         12394.0   
    c         17409.0    -29557.0      3354.0      3708.0     ...         18696.0   
    ccl          -2.0      6514.0        -2.0     19499.0     ...          7294.0   
    fb       -71036.0        -4.0        -6.0     15561.0     ...          3001.0   
    gas          -2.0        -2.0        -2.0     10935.0     ...        -66212.0   
    ge           -2.0        -2.0        -2.0    -10335.0     ...         13018.0   
    goog       -547.0        -1.0      -391.0      -737.0     ...            -1.0   
    googl      -546.0        -1.0      -390.0      -736.0     ...            -1.0   
    gs         2068.0     -4366.0     -3689.0        -1.0     ...          3797.0   
    msft      22456.0        -2.0      7911.0        -2.0     ...         14738.0   
    t            -5.0      4384.0      6790.0        -4.0     ...            -5.0   
    
    Date   2015-10-01  2015-11-02  2015-12-01  2016-01-04  2016-02-01  2016-03-01  \
    aa           -1.0    148253.0    -56548.0    -60946.0    383094.0   -334937.0   
    aap       -5178.0      2880.0     15507.0      3236.0     -5486.0      3037.0   
    aapl         -1.0        -1.0      2922.0      9862.0      4940.0     -2578.0   
    all          -1.0      7546.0     -7364.0      5177.0     -9930.0     -9223.0   
    ba           -1.0     -3534.0        -1.0      2317.0      9472.0      3124.0   
    bby       -8707.0     48353.0     50031.0        -3.0       -11.0    -44034.0   
    bmy          -1.0        -3.0    -11245.0        -1.0      8382.0     -5542.0   
    c         12761.0         0.0         0.0      8004.0     36976.0     16089.0   
    ccl          -1.0        -3.0      9119.0    -19224.0     13048.0      5186.0   
    fb           -1.0     -7198.0     -4839.0      3250.0    -19507.0      8237.0   
    gas        4257.0     11258.0        -1.0    -10148.0    -11996.0      3492.0   
    ge       -17183.0    -32072.0    -12056.0    -20447.0      8754.0     -9906.0   
    goog         -1.0     -1378.0     -1186.0        -1.0      -790.0      1230.0   
    googl        -1.0     -1034.0      -874.0        -1.0      -853.0      1076.0   
    gs         4642.0        -1.0        -1.0      3327.0      4153.0      4308.0   
    msft     -10477.0    -23979.0    -11363.0        -2.0    -14120.0     14098.0   
    t         15887.0     14190.0        -4.0    -17987.0    -41960.0        -8.0   
    
    Date   2016-04-01  2016-05-02  2016-06-01  
    aa            0.0   -188531.0    212568.0  
    aap          -1.0      2307.0        -1.0  
    aapl      -6152.0     21208.0     -8506.0  
    all          -1.0      6687.0     -8141.0  
    ba           -1.0     -7310.0      5029.0  
    bby       20804.0        -6.0        -5.0  
    bmy        5709.0    -21197.0        -3.0  
    c             0.0    -25055.0         0.0  
    ccl       -8422.0     16350.0      5494.0  
    fb           -1.0     -4074.0        -2.0  
    gas        5990.0        -3.0        -3.0  
    ge        -9853.0     13535.0      9681.0  
    goog         -1.0      1286.0     -1021.0  
    googl        -1.0      1411.0      -931.0  
    gs           -1.0     -2516.0      2582.0  
    msft         -1.0     20060.0    -14205.0  

We can now see lots of small trades I don't want which we are paying fixed fees on.

Any suggestions on how to get round this? Do I need a rebalance algorithm or does the core need to change to deal with my requirement?

Thanks
Charles
