### ISSUE TITLE
Using WeighTarget()

### ISSUE THREAD

**Issue by puyash** [pmorissette/bt#76]
I have a separate process generating my signals (weights). As on will generate a dictionary (of dictionaries) with weights for the dates where re balancing is to occur. Between those dates the balance should progress according to the progression of returns.

It seems like the WeightTarget() algo is the way to go. But I get nothing. Am I using it correctly?

In summary: What I am after is to:
1. Set initial weights -> progress without re balancing until next set of weights.
2. Re balance according to next set of weights on the associated date -> progress
---

<code>
import bt
import pandas

%matplotlib inline

data = bt.get('spy,agg, aapl', start='2010-01-01', end = '2011-01-01')
print data.head()

signals = {'2010-01-04' : {'spy' : 0.2, 'agg' : 0.3, 'aapl' : 0.5},
           '2001-03-05' : {'spy' : 0.3, 'agg' : 0.4, 'aapl' : 0.3},
           '2001-10-11' : {'spy' : 0.8, 'agg' : 0.1, 'aapl' : 0.1}}

signal_frame = pandas.DataFrame(signals).T

s = bt.Strategy('s1', [bt.algos.RunDaily(),
                       bt.algos.SelectAll(),
                       bt.algos.WeighTarget(signal_frame),
                       bt.algos.Rebalance()
                       ])

test = bt.Backtest(s, data)
res = bt.run(test)

res.plot()
res.display()
res.plot_weights()

</code>

**Comment by puyash** [comment]
Problem solved by specifying index-type to datetime:
signal_frame.index = pandas.to_datetime(signal_frame.index)

**Comment by boyac** [comment]
a quick question, what should be feeding into WeightTarget()? a dictionary or DataFrame? Thanks
