### ISSUE TITLE
Simplification of long short strategy like in SIT R

### ISSUE THREAD

**Issue by potholiday** [pmorissette/bt#78]
I have used systemic investor toolbox (SIT) package in R and its very good for backtesting. In that package creating signal for long, short  or long-short strategy is [very easy](https://inovancetech.com/backtesttutorialr.html).

```
#long only strategy
signal<-ifelse(RSI3 < 30 & CCI20 > -290 & CCI20 < -100 & DEMA10c > -40 & DEMA10c < -20,1,NA)

#short only strategy
signal<-ifelse(RSI3 >30 & CCI20 > -290 & CCI20 > -100 & DEMA10c < -40 & DEMA10c > -20,-1,NA)

#long and short strategy
signal<-ifelse(RSI3 < 30 & CCI20 > -290 & CCI20 < -100 & DEMA10c > -40 & DEMA10c < -20,1,-1)

```

and then pass the signal to a backtest function

```
data$weight[] = NA
data$weight[] = signal
models$result = bt.run.share(data, clean.signal=T, trade.summary = TRUE)
```

It would be easier if **bt** also has similar simplified functions.

**Comment by pmorissette** [comment]
Hey @potholiday,

This is also easy with `bt`. Please see the `WeighTarget` or `SelectWhere` algos. You will basically use Pandas to create a signal / weight matrix that will be passed to the strategy. 

Cheers,
Phil

**Comment by potholiday** [comment]
Hey thanks for the reply . I have tried this code https://github.com/pmorissette/bt/issues/59 and I am getting the same error. Any idea why its happening.

**Comment by pmorissette** [comment]
Hey @potholiday ,

Can you try running this code:

```python
import bt
import pandas as pd

data = bt.get('HYG', start = '2000-01-01')

sma = data.rolling(200).mean()
plot = bt.merge(data,sma).plot(figsize=(15,5))

signal = data > sma

s = bt.Strategy('above200sma', [
        bt.algos.SelectWhere(data > sma),
        bt.algos.WeighEqually(), 
        bt.algos.Rebalance()])

t = bt.Backtest(s, data)
res = bt.run(t)
res.display()
```

This works fine on my end. Also, have you updated to the latest version of `bt`? You can run:
```
pip install --upgrade bt
```

Let me know if you still run into the issue.

Cheers,
Phil

**Comment by potholiday** [comment]
Thank you it worked without upgrading.

**Comment by potholiday** [comment]
@pmorissette Can you please answer my last question that is what is the right way to get both *long and short* signals together and pass it to the *strategy* in bt.

**Comment by pmorissette** [comment]
Hey @potholiday,

The simplest way is to use `bt.algos.WeighTarget`. It's similar to SelectWhere, but you end up setting the target weights directly.

See http://pmorissette.github.io/bt/examples.html#sma-crossover-strategy - I think this is what you are looking for. Basically, you tell `bt` what you want your portfolio to look like at each point in time (weights), and it will take care of the rebalancing. 

Cheers,
Phil

**Comment by potholiday** [comment]
Ok so is this correct . its not showing any error.

```
import bt
import pandas as pd

data = bt.get('HYG', start = '2000-01-01')

sma = data.rolling(200).mean()
plot = bt.merge(data,sma).plot(figsize=(15,5))

tw = sma.copy()
signal = data > sma

tw[data> sma] = 1.0
tw[data <= sma] = -1.0
tw[sma.isnull()] = 0.0

cross = bt.Strategy('ma_cross', [bt.algos.WeighTarget(tw),
                                    bt.algos.Rebalance()])
t = bt.Backtest(cross, data)

res = bt.run(t)

res.display()
```

If I want to get `Best Month,Best Year,Yearly Mean,Total Return ,Max Drawdown' as a separate variable or as a list what should I do. Tried this `res.display()[1]` but no luck.

**Comment by pmorissette** [comment]
You will have to put `(` `)` around each condition. This is a `pandas` thing. For the stats, see `res.stats`. Once again, to extract individual stats, refer to the pandas documentation. 

Hope this helps,
Phil

**Comment by potholiday** [comment]
Thank you for clearing my doubts and taking your valuable time for explaining it. Can you please suggest any community or forum where `bt` is actively discussed such a way that I can ask these trivial doubts there. Github is a development platform and I think I should avoid asking such questions here.

**Comment by pmorissette** [comment]
Hey @potholiday,

I am not aware of any such places. I just wrote this code a while back and put it up on Github for others to use / report bugs / submit PRs, etc. 

My advice, if you are interested in this library, is to get comfortable with Python, pandas and numpy. You can also browse through `bt`'s code to get an idea on how the library works (if you want to write your own algos). 

You might want to check out `zipline`, another python backtesting framework used to power Quantopian. I'm sure this project has a bigger community / more tutorials, but might not have the same features / structure as `bt`.

Hope this helps,
Phil

**Comment by potholiday** [comment]
I have tired many other back-testing modules in python  before quantopian, backtrader, pyalgotrader are a few but I find your backtester `bt` to be simpler to code comparing to others.  This really is an awesome backtester but its really sad that not many people doesn't know about it. 

Can I give you a small recommendation, As well using this (example)[http://pmorissette.github.io/bt/examples.html) can you add similar simpler code to your example page. Your example code is a little bit complex for a average programmer like me but the below code I can understand easily. 

```
import bt
import pandas as pd

data = bt.get('HYG', start = '2000-01-01')

sma50 = data.rolling(50).mean()
sma200 = data.rolling(200).mean()
plot = bt.merge(data,sma200).plot(figsize=(15,5))

tw = sma200.copy()


tw[(data> sma50)&(data>sma200)] = 1.0
tw[(data <= sma50)|(data<=sma200)] = -1.0
tw[sma200.isnull()] = 0.0

cross = bt.Strategy('ma_cross', [bt.algos.WeighTarget(tw),
                                    bt.algos.Rebalance()])
t = bt.Backtest(cross, data)

res = bt.run(t)

res.display()
res.stats

```

Any way keep up the good work once more thank you for taking your valuable time

**Comment by pmorissette** [comment]
Hey @potholiday,

Thanks for the kind words and I'm glad to hear you like `bt`! I will add your example to the documentation website as I'm sure it will help others. 

Thanks again,
Phil
