### ISSUE TITLE
[Question] Get transactions

### ISSUE THREAD

**Issue by aaronroman** [pmorissette/bt#79]
Hello, 

there are any easy way to get the complete transaction list? I mean, [Date, Ticker, Amount, Price] or similar?

Nice work, keep it up 👍 

Thanks

**Comment by sven337** [comment]
Request seconded. I would like bt to give me a list of the tickers it selected and when, to use it not only as a backtest but also to drive future investments.
What I originally did was to make my Select algo fill in a "selection list", but bt appears to do a deepcopy, such that you can't pass a list to the strategy constructor and have the algos fill it in. So I settled on a global list that is modified directly by the Select algo. 
This works, but it is obviously not good software design.

**Comment by pmorissette** [comment]
So I added a patch - this info was not readily available previously.

Thanks for bringing this up and let me know if you encounter any issues.

Cheers,
Phil
