### ISSUE TITLE
WeighTarget() Reverting to Equal Weights with/without Commission

### ISSUE THREAD

**Issue by FinQuest** [pmorissette/bt#82]
I'm looking at a very basic algo and am curious as to the trades generated at each rebalance.  If I take a simplified case of a single asset portfolio and reset the weights to 100% each rebalance I would not expect any trades to be generated:

```python
# Simple single asset potfolio rebalancing to 100% once per month
data = bt.get('aapl', start='2016-01-01', end='2016-03-31')
dates = [pd.to_datetime(dte) for dte in ['2016-01-04', '2016-01-29', '2016-02-29']]
weights = pd.DataFrame([1., 1., 1.], index=dates, columns=data.columns)

strategy = bt.Strategy('example', [bt.algos.RunOnDate(*dates),
                                   bt.algos.WeighTarget(weights),
                                   bt.algos.Rebalance()])                         
                                   
bt_gross = bt.Backtest(strategy, data, integer_positions=False,
                       commissions=lambda q, p: 0, name='gross')
bt_net = bt.Backtest(strategy, data, integer_positions=False,
                     commissions=lambda q, p: abs(q) * p * 0.33, name='net')

result = bt.run(bt_gross, bt_net)
df_merge = bt.merge(result.get_transactions('gross'), result.get_transactions('net'))    
```

Performance:

![figure_1](https://cloud.githubusercontent.com/assets/11697247/23012550/b23751e2-f41e-11e6-9896-ff307c351ad3.png)

Transaction Log:

| date | price gross	| quantity gross | price net | quantity net |
| ---- | ---- | ---- | ---- | ---- |
| 2016-01-04	| 102.61	| 9745.43	| 102.61	| 9745.43 |
| 2016-01-29	| NA	| NA | 94.81 | -2636.84 |
| 2016-02-29	| NA	| NA | 94.69 |-660.06 |

(I was previously unaware the default commission was 1%, 1 USD by default and have updated the above).

Where no commission is applied everything works as I would expect.  

Is there a way of seeing the cash? 
Would the strategy always invest 100% into equity and 'borrow' the commission? (i.e. should the weights be (1-com) at initial rebalance?). Is the cash to cover the commission then raised from the sale of shares at the next rebalance?

[Python 3.5, pip 0.1.15]

Interesting library and great work!

**Comment by pmorissette** [comment]
Hey @FinQuest,

Thanks for the input. I believe this is related to #80. I will investigate and revert back shortly. 

Cheers,
Phil

**Comment by FinQuest** [comment]
Hi @pmorissette and thanks for looking.

I have updated the code in question above to reflect correct implementation of gross and net comm.

I agree it looks like its related to #80 and simply more exaggerated here because I have applied the high commission. In cases where com is sufficiently high, integer_positions will not resolve the issue but mask it.

Interested to hear your views!

Tim

**Comment by FinQuest** [comment]
Hi Phil,

I still have an issue but probably my lack of understanding of the library.

I've update to the latest pip version (2.1) and run the same example as above.  The transaction log has updated as expected.  Guess hard to be 100% invested because you have the flexibility of the user defined commission function.

Should the plot() method plot the strategy or the indexed equity?

![figure_1](https://cloud.githubusercontent.com/assets/11697247/23095845/0233b0aa-f609-11e6-87d8-b00e3a7e4ef8.png)

In the example above both the gross and the net strategy are the same whereas I would expect the net to drop by approximately 24.8% immediately to reflect the negative impact of the traction costs.

Should plot() not chart result.backtests['net'].strategy.prices where the first value is set to the strategy open value.

(Should I be opening this as new issue? Is this the desired behaviour?)

Thanks,

Tim
