### ISSUE TITLE
Commission Handling in Strategy

### ISSUE THREAD

**Issue by FinQuest** [pmorissette/bt#83]
I've update to the latest pip version (2.1) and run the  example code below which is taken from  #82:

```python
# Simple single asset potfolio rebalancing to 100% once per month
data = bt.get('aapl', start='2016-01-01', end='2016-03-31')
dates = [pd.to_datetime(dte) for dte in ['2016-01-04', '2016-01-29', '2016-02-29']]
weights = pd.DataFrame([1., 1., 1.], index=dates, columns=data.columns)

strategy = bt.Strategy('example', [bt.algos.RunOnDate(*dates),
                                   bt.algos.WeighTarget(weights),
                                   bt.algos.Rebalance()])                         
                                   
bt_gross = bt.Backtest(strategy, data, integer_positions=False,
                       commissions=lambda q, p: 0, name='gross')
bt_net = bt.Backtest(strategy, data, integer_positions=False,
                     commissions=lambda q, p: abs(q) * p * 0.33, name='net')

result = bt.run(bt_gross, bt_net)
df_merge = bt.merge(result.get_transactions('gross'), result.get_transactions('net'))    
```

The transaction log has updated as expected to reflect new updates (thank you!).  Guess hard to be 100% invested even with integer_positions=False because you have the flexibility of the user defined commission function.

The plot() method indicates that the performance of both the gross and the net is identical.

![figure_1](https://cloud.githubusercontent.com/assets/11697247/23095845/0233b0aa-f609-11e6-87d8-b00e3a7e4ef8.png)

I would expect the net to drop by approximately 24.8% immediately to reflect the negative impact of the traction costs.  If I look at result.backtests['net'].strategy.prices the data is there and looks good. 

```python
df = bt.merge(result.backtests['gross'].strategy.prices, result.backtests['net'].strategy.prices)
df.iloc[0] = 100
```
![figure_1-1](https://cloud.githubusercontent.com/assets/11697247/23095964/4deb66bc-f60b-11e6-9e59-2641cf3668c3.png)

If I run results.stats() the stats are identical for both strategies too.

Thanks,

Tim

**Comment by FinQuest** [comment]
Phil can you see an issue here?  Would appreciate your help!  Thanks,

**Comment by pmorissette** [comment]
Hi @FinQuest,

This looks strange indeed. Looking into it.

Cheers,
Phil

**Comment by pmorissette** [comment]
Hey @FinQuest 

Thanks for pointing this out! Basically, there was indeed an issue since `time 0` could be updated by actions on `time 0` (the large commission in your example), and they were being ignored in the performance calculations.

To fix this, the Bactest object inserts a blank row at `time0 - 1day` in the passed in `data` object.

Please update to the latest version and let me know if you see anything else. 

Thanks again for reporting this issue.

Cheers,
Phil

**Comment by FinQuest** [comment]
Great thanks again for super fast turn around.  Will take a look this evening.

Cheers,

Tim

**Comment by FinQuest** [comment]
Hi Phil.  Taken a look and seems a bit weird to add a new line prior to index start.  Would this not cause the vol etc. to be understated too as day one is effectively just going to be negative pl from transaction costs and nothing else.

Instead of having this:

```                 gross         net
2016-01-03  100.000000  100.000000
2016-01-04  100.000000   81.392570
2016-01-05   98.120551   79.979572
2016-01-06   96.689605   78.903765
```

Could you not have this for the first value:
```
                 gross         net
2016-01-04  100.000000   100.00000
2016-01-05   98.120551   79.979572
2016-01-06   96.689605   78.903765
```
Regards,

Tim

**Comment by pmorissette** [comment]
Hi @FinQuest,

I think this solution makes sense. At the end of the day, you do have to factor these costs in, the same way they would be accounted for in the 'real world'. 

By adding a blank row at the top of the `data`, I am basically setting the initial state, at t0-1. As you pointed out, in the event of a large commission, the difference is obviously quite large, and was previously ignored. 

Let me know if you can think of a better solution, but I think this one is quite elegant in that it sets the initial state without modifying any of the internals. 

Cheers,
Phil

**Comment by FinQuest** [comment]
I guess I need to get more familiar with library before I can make meaningful contribution / suggestion!
Cheers,
Tim
