### ISSUE TITLE
[AttributeError] 'module' object has no attribute 'get'

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#84]
python 2.7

below script has returned "
AttributeError: 'module' object has no attribute 'get'"

```
import bt
# fetch some data
data = bt.get('spy,agg', start='2010-01-01')

if __name__ == '__main__':
	print data.head()
```

**Comment by pmorissette** [comment]
How did you install bt? What version are you running?

**Comment by boyac** [comment]
bt (0.2.1)
and the python 2.7 was installed via Anacoda. Will this affect?

**Comment by pmorissette** [comment]
I'm not sure how to help you out here. Could be an issue with the way Sublime Text loads / executes python modules. `bt.get` is just an alias for `ffn.get`, defined in `bt/__init__.py`. Worst-case, you can call directly on `ffn`, but I'm just not sure why Sublime would break the alias.
