### ISSUE TITLE
Install Error: Failed building wheel for bt

### ISSUE THREAD

**Issue by FinQuest** [pmorissette/bt#85]
Apologies in advance if not related to bt but trying to install bt using pip install bt on Window 7 and getting error:

cl: Command line error D8003: missing source filename
error: command 'C:\...Microsoft Visual Studio 14.0\VC\bin\x86_amd64\cl.exe' failed with exit status 2.

Is there an alternative way of installing?

Thanks,

**Comment by pmorissette** [comment]
Hey @FinQuest 

Not sure how to help here. I am currently only using bt on linux/mac. I have used it on windows in the past though, so it should work.

Perhaps you could try cloning the repo and manually building the extension (`make`). I'm just using cython and not really doing anything fancy. As far as I know, it should work on windows as well.

Cheers,
Phil

**Comment by FinQuest** [comment]
Built wheel on another machine with pip and just installed from that and seems to work.  Thanks anyway.  My bad!
