### ISSUE TITLE
What is the best/official way of passing metadata into / through the algo stack?

### ISSUE THREAD

**Issue by FinQuest** [pmorissette/bt#86]
If I wanted to pass meta data through the algo stack what is the preferred method?

I have two types of data:

i) Static which is unlikely to change over time or changes on a very irregular basis and stuff like sector, region, country.

ii) daily/weekly/monthly like daily dollar volume, fx, fundamental data.  Can I just add these to data?

Would I just create an algo and assign the relevant variables to temp?

Does anyone have any examples using this functionality they would like to share.

Thanks for any comments/suggestions!

Tim

**Comment by pmorissette** [comment]
Hey @FinQuest 

`Strategy.temp` is used for temporary values. It is cleared on each loop. `Strategy.perm` is a permanent dictionary, so this is where I would store metadata. You algos can simply access `target.perm['your_key']` to retrieve the info. See core.py line 1250 (Strategy.__init__).

So basically, after you create your strategy, you can just set whatever permanent data you want. 

```python
s = bt.Strategy('s', my_algos)
s.perm['metadata'] = metadata
```

Hope this helps,
Phil

**Comment by FinQuest** [comment]
Perfect.  Makes sense.  Thanks again Phil.
