### ISSUE TITLE
no plot functions are visible when using sublime

### ISSUE THREAD

**Issue by grilam14** [pmorissette/bt#91]
I just used the quick example from the bt website word for word. The text data printed normally, but none of the plots work. Is there something else I should do?

**Comment by pmorissette** [comment]
I'm not familiar with Sublime unfortunately. They are simply Matplotlib plots, so nothing special. If there is a way to do that with Sublime, then it should be possible to display them.

I typically run my code within a [Jupyter Notebook](http://jupyter.org/) - perhaps this is something you could look into.
