### ISSUE TITLE
Trading signals

### ISSUE THREAD

**Issue by csaszkow** [pmorissette/bt#92]
Hey Guys,

Based on the Moving Average Crossover example, I created my own trading strategy. It has 3 trading signals (Long, Short, Do nothing) instead of two (Long, Short). I was wondering if there is any way the weightarget class could handle this solution since I get zero division error.

Would you be so kind as to help me on this one?

Many thanks in advane!

**Comment by JordanPlatts** [comment]
Check out some of the examples I posted. I think trend_1 or trend_2 may work depending on what you exactly want. Let me know if you have any other questions.
