### ISSUE TITLE
RunAfterDays(Algo)

### ISSUE THREAD

**Issue by AnthonyFJGarner** [pmorissette/bt#96]
Above does not work correctly. If you select daily re-balancing its fine. If you select any other periodic re-balancing it become "run after month" or quarter or year.

Instead of looking into it properly I used the following solution instead:

bt.algos.RunAfterDate(data.iloc[0].name + DateOffset(months=Params.minVarLookback))

Hope this helps. May look into RunAfterDays "error"(?) in due course.

**Comment by FinQuest** [comment]
Hi Anthony, I think you need to call RunAfterDays() prior to RunWeely/Monthly/Yearly in your AlgoStack. Cheers, Tim

**Comment by AnthonyFJGarner** [comment]
Thanks Tim. What a dumb error at my end!
