### ISSUE TITLE
Using integer_positions=True and SecurityBase.allocate()

### ISSUE THREAD

**Issue by FinQuest** [pmorissette/bt#97]
The allocate(self, amount, update=True) function in core.py seems to ignore integer_positions and decrease q by an integer number of shares until there are sufficient funds to cover the commission.

When running the below,

```python
master = bt.Strategy('master', [bt.algos.RunMonthly(),
                                bt.algos.SelectAll()),
                                bt.algos.WeighEqually(),
                                bt.algos.Rebalance()])

# create the backtest and run it
bt_gross = bt.Backtest(master, data, commissions=comm_fn(0.00), integer_positions=False, name='gross')
bt_net = bt.Backtest(master, data, commissions=comm_fn(0.05), integer_positions=False, name='net')
r = bt.run(bt_gross, bt_net)
```
I would expect/like the security weights to be exactly equal to 1/n if using linear commission function.  If no commission is applied the weights are exactly equal.  If commission is applied, the weights are not equal.

**Comment by FinQuest** [comment]
I attempted to rectify this with pull request #98 and this does ensure that on the initial 'rebalance' event the weights are exactly equal to target weights.

Ideally I wanted to ensure that at every 'rebalance' event, the realised weights are exactly equal to the target weights and the portfolio is fully invested.  The chart below shows the max and min weight across all assets and on inception the weights are equal:

![example](https://cloud.githubusercontent.com/assets/11697247/25886533/e5e4869a-3555-11e7-87d8-c2d7ad20f5ad.png)

After the initial 'rebalance' and the prices evolve independently, the commission will cause the individual asset weights to be slightly different and the weights will never be exactly equal.  I could add multiple bt.algos.Rebalance() events to algo stack and results will converge but this is very ugly, slow and there are not really real trades.

I could introduce a second algo which was called prior to 'rebalance' which would calculate the total comm prior to the rebalance and from the capital and then call 'rebalance' with no commission but this would be reliant on a linear commission function which was homogeneous across all the assets in  the portfolio so also perhaps not appropriate.

@pmorissette would be very interested in your opinion.

Cheers,

Tim

**Comment by FinQuest** [comment]
(Sorry closed in error)

**Comment by pmorissette** [comment]
Hi @FinQuest,

The whole block of code starting at 1062 in `core.py` was introduced to address the issue where the commissions are ignored when determining the quantities. This is initially how it worked, but it essentially created some sort of implicit leverage. For small commissions, it wasn't a huge deal, but it could throw off the performance figures & weights in the case of large commissions.

To address this, I had to basically figure out a way to solve for the quantity including the costs of commissions. Since the commission function can be non-linear, this is a non-trivial problem. To be honest, I'm not too happy with the current solution, but I could not think of anything more robust at the time (definitely open to suggestions here!). That's why I just slowly decrement the quantity by 1 unit at a time and re-evaluate the commission to see if the capital allocated is now sufficient to cover the quantity desired + commissions. Obviously, this is not a very elegant solution, and the unit decrease doesn't make that much sense in a `interger_positions=False` scenario. However, short of having some kind of check for linearity, I'm not sure how to get around this issue. 

I hope this makes sense and I am open to ideas if you have any. 

Cheers,
Phil

**Comment by FinQuest** [comment]
Yeah... Tricky one. The method I proposed in #98  wont work when non-linear and I like the flexibility of your commission logic.  Having explicit variable for linear_comm ugly too.  For me it causes more of an issue when large number of assets in portfolio and leads to significant drag by not being fully invested.  Guess I can just set the notional to be much higher in interim.

Did you try any other ideas?

Thanks,

Tim

**Comment by FinQuest** [comment]
@pmorissette  I agree proposed solution perhaps not ideal due to the non-linear commission issues but I think above is preferable to current implementation perhaps contingent on simple linearity check on commission function.  Any views?

**Comment by JordanPlatts** [comment]
Could you try to recreate this issue now? I think it should be fixed.

**Comment by JordanPlatts** [comment]
I am going to close this issue but let me know if this error crops up again. I don't think it is an error proof solution but I do think it will fail "nicely" if it doesn't work as intended. Let me know what you guys think.

            i = 0
            last_q = q
            last_amount_short = full_outlay - amount
            while not np.isclose(full_outlay, amount, rtol=0.) and q != 0:

                dq_wout_considering_tx_costs = (full_outlay - amount)/(self._price * self.multiplier)
                q = q - dq_wout_considering_tx_costs

                if self.integer_positions:
                    q = math.floor(q)

                full_outlay, _, _ = self.outlay(q)

                # if our q is too low and we have integer positions
                # then we know that the correct quantity is the one  where
                # the outlay of q + 1 < amount. i.e. if we bought one more
                # position then we wouldn't have enough cash
                if self.integer_positions:

                    full_outlay_of_1_more, _, _ = self.outlay(q + 1)

                    if full_outlay < amount and full_outlay_of_1_more > amount:
                        break

                # if not integer positions then we should keep going until
                # full_outlay == amount or is close enough

                i = i + 1
                if i > 1e4:
                    raise Exception(
                        'Potentially infinite loop detected. This occurred '
                        'while trying to reduce the amount of shares purchased'
                        ' to respect the outlay <= amount rule. This is most '
                        'likely due to a commission function that outputs a '
                        'commission that is greater than the amount of cash '
                        'a short sale can raise.')

                if self.integer_positions and last_q == q:
                    raise Exception(
                        'Newton Method like root search for quantity is stuck!'
                        ' q did not change in iterations so it is probably a bug'
                        ' but we are not entirely sure it is wrong! Consider '
                        ' changing to warning.'
                    )
                last_q = q

                if np.abs(full_outlay - amount) > np.abs(last_amount_short):
                    raise Exception(
                        'The difference between what we have raised with q and'
                        ' the amount we are trying to raise has gotten bigger since'
                        ' last iteration! full_outlay should always be approaching'
                        ' amount! There may be a case where the commission fn is'
                        ' not smooth'
                    )
                last_amount_short = full_outlay - amount
