### ISSUE TITLE
I have a problem with installing bt

### ISSUE THREAD

**Issue by hmz123** [pmorissette/bt#99]
Hello,
I have a problem with installing bt, i have Python 2.7 ,anaconda 2,but 
I do not know why it does not work ?

C:\Users\hamza\Anaconda2\conda-meta\tickerData>pip install bt
Collecting bt
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003FAF978>, 'Connection to 10.23.201.11 timed out. (connect timeout=15)')': /simple/bt/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003FAFB70>, 'Connection to 10.23.201.11 timed out. (connect timeout=15)')': /simple/bt/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003FAFE48>, 'Connection to 10.23.201.11 timed out. (connect timeout=15)')': /simple/bt/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003FAFBE0>, 'Connection to 10.23.201.11 timed out. (connect timeout=15)')': /simple/bt/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003FAFD68>, 'Connection to 10.23.201.11 timed out. (connect timeout=15)')': /simple/bt/
  Could not find a version that satisfies the requirement bt (from versions: )
No matching distribution found for bt

**Comment by hmz123** [comment]
I think I used proxy

**Comment by tanzedan** [comment]
unable to install: 
Building wheels for collected packages: bt
  Running setup.py bdist_wheel for bt ... error
  Failed building wheel for bt
  Running setup.py clean for bt
Failed to build bt
Installing collected packages: bt
  Running setup.py install for bt ... error
Exception:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 56: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "D:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "D:\Anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "D:\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "D:\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 56: invalid continuation byte

I don't know what should I do

**Comment by wlblount** [comment]
i am able to install using pip install bt

**Comment by PMonroy1992** [comment]
Hi,

I have the same exception as tanzedan: 

Exception:
Traceback (most recent call last):
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 75: invalid start byte

Is there a solution to this ? I already had problems installing bt with Anaconda Python 2.7

Thanks,

Pierre
